<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MILL09.Models\MILL09.Models.csproj" />
    <ProjectReference Include="..\MILL80.Infrastructure\MILL80.Infrastructure.csproj" />
  </ItemGroup>

</Project>
