// <auto-generated>
//     Generated by the ViewModelsProject template.
// </auto-generated>
#nullable enable

using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;

namespace MILL06.ViewModels
{
    public abstract partial class MenuNodeViewModel : ObservableObject
    {
        [ObservableProperty]
        private string _title = string.Empty;

        [ObservableProperty]
        private bool _isExpanded;

        [ObservableProperty]
        private bool _isSelected;

        public ObservableCollection<MenuNodeViewModel> Children { get; } = new();
    }
}