// <auto-generated>
//     Generated by the ViewModelsProject template.
// </auto-generated>
#nullable enable

using System.Collections.Generic;
using Microsoft.Extensions.DependencyInjection;
using MILL80.Infrastructure;

namespace MILL06.ViewModels
{
    public partial class MenuRegistry
    {
        #region MenuRegistry's Instance Singleton
        public static MenuRegistry Instance =>
            global::MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<MenuRegistry>();

        protected internal MenuRegistry() { }
        #endregion MenuRegistry's Instance Singleton

        public List<MenuNodeViewModel> GetDefaultMenu()
        {
            var menu = new List<MenuNodeViewModel>();

            var dboGroup = new MenuGroupViewModel("dbo");
            dboGroup.Children.Add(new MenuItemViewModel("Addresses", "AddressesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("AddressTypes", "AddressTypesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("AwbuildVersions", "AwbuildVersionsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("BillOfMaterials", "BillOfMaterialsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("BusinessEntities", "BusinessEntitiesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("BusinessEntityAddresses", "BusinessEntityAddressesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("BusinessEntityContacts", "BusinessEntityContactsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ContactTypes", "ContactTypesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("CountryRegions", "CountryRegionsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("CountryRegionCurrencies", "CountryRegionCurrenciesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("CreditCards", "CreditCardsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("Cultures", "CulturesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("Currencies", "CurrenciesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("CurrencyRates", "CurrencyRatesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("Customers", "CustomersViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("DatabaseLogs", "DatabaseLogsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("Departments", "DepartmentsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("EmailAddresses", "EmailAddressesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("Employees", "EmployeesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("EmployeeDepartmentHistories", "EmployeeDepartmentHistoriesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("EmployeePayHistories", "EmployeePayHistoriesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ErrorLogs", "ErrorLogsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("Illustrations", "IllustrationsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("JobCandidates", "JobCandidatesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("Locations", "LocationsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("Passwords", "PasswordsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("Persons", "PersonsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("PersonCreditCards", "PersonCreditCardsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("PersonPhones", "PersonPhonesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("PhoneNumberTypes", "PhoneNumberTypesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("Products", "ProductsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ProductCategories", "ProductCategoriesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ProductCostHistories", "ProductCostHistoriesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ProductDescriptions", "ProductDescriptionsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ProductInventories", "ProductInventoriesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ProductListPriceHistories", "ProductListPriceHistoriesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ProductModels", "ProductModelsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ProductModelIllustrations", "ProductModelIllustrationsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ProductModelProductDescriptionCultures", "ProductModelProductDescriptionCulturesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ProductPhotos", "ProductPhotosViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ProductProductPhotos", "ProductProductPhotosViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ProductReviews", "ProductReviewsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ProductSubcategories", "ProductSubcategoriesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ProductVendors", "ProductVendorsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("PurchaseOrderDetails", "PurchaseOrderDetailsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("PurchaseOrderHeaders", "PurchaseOrderHeadersViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("SalesOrderDetails", "SalesOrderDetailsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("SalesOrderHeaders", "SalesOrderHeadersViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("SalesOrderHeaderSalesReasons", "SalesOrderHeaderSalesReasonsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("SalesPersons", "SalesPersonsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("SalesPersonQuotaHistories", "SalesPersonQuotaHistoriesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("SalesReasons", "SalesReasonsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("SalesTaxRates", "SalesTaxRatesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("SalesTerritories", "SalesTerritoriesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("SalesTerritoryHistories", "SalesTerritoryHistoriesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ScrapReasons", "ScrapReasonsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("Shifts", "ShiftsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ShipMethods", "ShipMethodsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("ShoppingCartItems", "ShoppingCartItemsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("SpecialOffers", "SpecialOffersViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("SpecialOfferProducts", "SpecialOfferProductsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("StateProvinces", "StateProvincesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("Stores", "StoresViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("TransactionHistories", "TransactionHistoriesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("TransactionHistoryArchives", "TransactionHistoryArchivesViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("UnitMeasures", "UnitMeasuresViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("Vendors", "VendorsViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("WorkOrders", "WorkOrdersViewModel"));
            dboGroup.Children.Add(new MenuItemViewModel("WorkOrderRoutings", "WorkOrderRoutingsViewModel"));
            menu.Add(dboGroup);

            CustomizeMenu(ref menu);
            return menu;
        }

        partial void CustomizeMenu(ref List<MenuNodeViewModel> menu);
    }
}
