// <auto-generated>
//     Generated by the ViewModelsProject template.
// </auto-generated>
#nullable enable

using CommunityToolkit.Mvvm.Input;

namespace MILL06.ViewModels
{
    public partial class MenuItemViewModel : MenuNodeViewModel
    {
        public string TargetViewModelName { get; }

        public MenuItemViewModel(string title, string targetViewModelName)
        {
            Title = title;
            TargetViewModelName = targetViewModelName;
        }

        #region Commands
        [RelayCommand]
        private void Activate()
        {
            // TODO: Route TargetViewModelName to the RegionCell for view injection
        }
        #endregion Commands
    }
}