// <auto-generated>
//     Generated by the ViewModelsProject template.
// </auto-generated>
#nullable enable

namespace MILL06.ViewModels
{
    public partial class MenuGroupViewModel : MenuNodeViewModel
    {
        public MenuGroupViewModel(string title)
        {
            Title = title;
        }
    }
}