// <auto-generated>
//     Generated from WorkOrder.g.cs by the ViewModelsProject template.
//     Regenerated whenever the source Model changes.
// </auto-generated>
#nullable enable

using System;
using System.Threading.Tasks;
using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.Input;
using MILL09.Models;
using MILL80.Infrastructure;

namespace MILL06.ViewModels
{
    public partial class WorkOrdersViewModel : BaseViewModel
    {
        // 1. Bridge the View to the MainModel's collection
        public ObservableCollection<WorkOrder> WorkOrders => MainViewModel.Instance.MainModel.WorkOrders;

        #region Commands
        // 2. The toolkit automatically generates an ICommand named 'LoadWorkOrdersCommand'
        [RelayCommand]
        private async Task LoadWorkOrdersAsync()
        {
            await WorkOrder.LoadAllAsync();
            OnPropertyChanged(nameof(WorkOrders));
        }
        #endregion Commands

        #region IDisposing
        // 3. IDisposable implementation (Inherited from BaseViewModel)
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                // Fire the partial method hook for manual cleanup
                OnDisposing();
            }
            base.Dispose(disposing);
        }

        // Hook definition: Erased by the compiler if not implemented in the .Manual.cs file
        partial void OnDisposing();
        #endregion IDisposing
    }
}
