// <auto-generated>
//     Generated from BusinessEntityAddressesViewModel.g.cs by the ViewsProject template.
// </auto-generated>
#nullable enable

using Syncfusion.Maui.DataGrid;

namespace MILL03.Views.Views;

public partial class BusinessEntityAddressesView : ContentView
{
    public BusinessEntityAddressesView()
    {
        InitializeComponent();
    }

    private void SfDataGrid_OnAutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
    {
        // Using a string literal ensures compilation success even if the entity lacks a Rowguid property.
        if (e.Column.MappingName.Equals("Rowguid", System.StringComparison.OrdinalIgnoreCase))
        {
            e.Column.Visible = false;
        }
    }
}
