// <auto-generated>
//     Generated by the DISetup template. Do not edit — regenerated on every run.
//     Declares how a type registers itself with the DI container.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using Microsoft.Extensions.DependencyInjection;

namespace MILL80.Infrastructure;

/// <summary>
/// Marks a class for automatic DI registration. Applied to the implementation; the
/// service type defaults to the class itself when not given.
///
/// The class needs a PUBLIC constructor — the scan activates it by reflection. A type
/// with an internal or protected constructor registers through a factory in a
/// hand-written ServiceCollectionExtensions.Manual.cs instead.
///
/// AllowMultiple, so one class can be resolvable under several interfaces.
/// </summary>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
public sealed class RegisterAttribute : Attribute {

    public Type? ServiceType { get; }
    public ServiceLifetime Lifetime { get; }

    public RegisterAttribute(ServiceLifetime lifetime = ServiceLifetime.Singleton) {
        Lifetime = lifetime;
    }

    public RegisterAttribute(Type serviceType, ServiceLifetime lifetime = ServiceLifetime.Singleton) {
        ServiceType = serviceType;
        Lifetime = lifetime;
    }
}
