// <auto-generated>
//     Generated by the DISetup template. Do not edit — regenerated on every run.
//     DI entry point for this project.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using Microsoft.Extensions.DependencyInjection;

namespace MILL09.Models;

public static partial class ServiceCollectionExtensions {

    /// <summary>
    /// Registers this project and everything it depends on. Direct dependencies only —
    /// transitivity handles the rest. Calls are fully qualified with global:: because
    /// every project declares a method of the same name, and a project whose own
    /// namespace nests a segment matching a dependency's root would otherwise resolve
    /// the call relative to itself.
    /// </summary>
    public static IServiceCollection AddRegistrations(this IServiceCollection services) {
        global::MILL12.Services.ServiceCollectionExtensions.AddRegistrations(services);
        global::MILL80.Infrastructure.ServiceCollectionExtensions.AddRegistrations(services);

        global::MILL80.Infrastructure.RegistrationScanner.ApplyRegistrations(services, typeof(ServiceCollectionExtensions).Assembly);

        // Hand-written registrations the attribute scan cannot express — a factory lambda,
        // an internal constructor, a conditional lifetime. Implement in a separate file;
        // if nothing implements it the call compiles away to nothing.
        AddManualRegistrations(services);

        return services;
    }

    static partial void AddManualRegistrations(IServiceCollection services);
}
