// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Street address information for customers, employees, and vendors.
/// </summary>
public partial class Address
{
    /// <summary>
    /// Primary key for Address records.
    /// </summary>
    public int AddressId { get; set; }

    /// <summary>
    /// First street address line.
    /// </summary>
    public string AddressLine1 { get; set; }

    /// <summary>
    /// Second street address line.
    /// </summary>
    public string AddressLine2 { get; set; }

    /// <summary>
    /// Name of the city.
    /// </summary>
    public string City { get; set; }

    /// <summary>
    /// Unique identification number for the state or province. Foreign key to StateProvince table.
    /// </summary>
    public int StateProvinceId { get; set; }

    /// <summary>
    /// Postal code for the street address.
    /// </summary>
    public string PostalCode { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<BusinessEntityAddress> BusinessEntityAddresses { get; set; } = new List<BusinessEntityAddress>();

    public virtual ICollection<SalesOrderHeader> SalesOrderHeaderBillToAddresses { get; set; } = new List<SalesOrderHeader>();

    public virtual ICollection<SalesOrderHeader> SalesOrderHeaderShipToAddresses { get; set; } = new List<SalesOrderHeader>();

    public virtual StateProvince StateProvince { get; set; }
}

[Register(typeof(IEntitySetLoader<MILL09.Models.Address>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.Address>), ServiceLifetime.Transient)]
public class AddressRepository : IEntitySetLoader<MILL09.Models.Address>, IEntitySaver<MILL09.Models.Address>
{
    private readonly AdventureWorks2019Context _dbContext;

    public AddressRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.Address>
    public async Task<IReadOnlyList<MILL09.Models.Address>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<Address>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.Address
        {
            AddressId = db.AddressId,
            AddressLine1 = db.AddressLine1,
            AddressLine2 = db.AddressLine2,
            City = db.City,
            ModifiedDate = db.ModifiedDate,
            PostalCode = db.PostalCode,
            Rowguid = db.Rowguid,
            StateProvinceId = db.StateProvinceId,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.Address>

    #region IEntitySaver<MILL09.Models.Address>
    public Task SaveAsync(MILL09.Models.Address entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.Address>
}
