// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Street address information for customers, employees, and vendors.
/// </summary>
public partial class Address
{    /// <summary>
    /// Primary key for Address records.
    /// </summary>
    public int AddressId { get; set; }

    /// <summary>
    /// First street address line.
    /// </summary>
    public string AddressLine1 { get; set; }

    /// <summary>
    /// Second street address line.
    /// </summary>
    public string AddressLine2 { get; set; }

    /// <summary>
    /// Name of the city.
    /// </summary>
    public string City { get; set; }

    /// <summary>
    /// Unique identification number for the state or province. Foreign key to StateProvince table.
    /// </summary>
    public int StateProvinceId { get; set; }

    /// <summary>
    /// Postal code for the street address.
    /// </summary>
    public string PostalCode { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<BusinessEntityAddress> BusinessEntityAddresses { get; set; } = new List<BusinessEntityAddress>();

    public virtual ICollection<SalesOrderHeader> SalesOrderHeaderBillToAddresses { get; set; } = new List<SalesOrderHeader>();

    public virtual ICollection<SalesOrderHeader> SalesOrderHeaderShipToAddresses { get; set; } = new List<SalesOrderHeader>();

    public virtual StateProvince StateProvince { get; set; }
}

[Register(ServiceLifetime.Transient)]
public class AddressRepository : IEntitySetLoader<Address>, IEntitySaver<Address>
{
    private readonly AdventureWorks2019Context _dbContext;

    public AddressRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<Address>
    public async Task<IReadOnlyList<Address>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<Address>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<Address>

    #region IEntitySaver<Address>
    public async Task SaveAsync(Address entity, CancellationToken ct)
    {
        _dbContext.Set<Address>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<Address>
}

