// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Current version number of the AdventureWorks 2016 sample database. 
/// </summary>
public partial class AwbuildVersion
{    /// <summary>
    /// Primary key for AWBuildVersion records.
    /// </summary>
    public byte SystemInformationId { get; set; }

    /// <summary>
    /// Version number of the database in 9.yy.mm.dd.00 format.
    /// </summary>
    public string DatabaseVersion { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime VersionDate { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }
}

[Register(ServiceLifetime.Transient)]
public class AwbuildVersionRepository : IEntitySetLoader<AwbuildVersion>, IEntitySaver<AwbuildVersion>
{
    private readonly AdventureWorks2019Context _dbContext;

    public AwbuildVersionRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<AwbuildVersion>
    public async Task<IReadOnlyList<AwbuildVersion>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<AwbuildVersion>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<AwbuildVersion>

    #region IEntitySaver<AwbuildVersion>
    public async Task SaveAsync(AwbuildVersion entity, CancellationToken ct)
    {
        _dbContext.Set<AwbuildVersion>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<AwbuildVersion>
}

