// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Cross-reference table mapping stores, vendors, and employees to people
/// </summary>
public partial class BusinessEntityContact
{
    public static string SqlSchema => "Person";
    public static string SqlTableName => "BusinessEntityContact";

    /// <summary>
    /// Primary key. Foreign key to BusinessEntity.BusinessEntityID.
    /// </summary>
    public int BusinessEntityId { get; set; }

    /// <summary>
    /// Primary key. Foreign key to Person.BusinessEntityID.
    /// </summary>
    public int PersonId { get; set; }

    /// <summary>
    /// Primary key.  Foreign key to ContactType.ContactTypeID.
    /// </summary>
    public int ContactTypeId { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual BusinessEntity BusinessEntity { get; set; }

    public virtual ContactType ContactType { get; set; }

    public virtual Person Person { get; set; }
}

[Register(typeof(IEntitySetLoader<MILL09.Models.BusinessEntityContact>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.BusinessEntityContact>), ServiceLifetime.Transient)]
public class BusinessEntityContactRepository : IEntitySetLoader<MILL09.Models.BusinessEntityContact>, IEntitySaver<MILL09.Models.BusinessEntityContact>
{
    private readonly AdventureWorks2019Context _dbContext;

    public BusinessEntityContactRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.BusinessEntityContact>
    public async Task<IReadOnlyList<MILL09.Models.BusinessEntityContact>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<BusinessEntityContact>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.BusinessEntityContact
        {
            BusinessEntityId = db.BusinessEntityId,
            PersonId = db.PersonId,
            ContactTypeId = db.ContactTypeId,
            ModifiedDate = db.ModifiedDate,
            Rowguid = db.Rowguid,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.BusinessEntityContact>

    #region IEntitySaver<MILL09.Models.BusinessEntityContact>
    public Task SaveAsync(MILL09.Models.BusinessEntityContact entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.BusinessEntityContact>
}
