// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Source of the ID that connects vendors, customers, and employees with address and contact information.
/// </summary>
public partial class BusinessEntity
{
    /// <summary>
    /// Primary key for all customers, vendors, and employees.
    /// </summary>
    public int BusinessEntityId { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<BusinessEntityAddress> BusinessEntityAddresses { get; set; } = new List<BusinessEntityAddress>();

    public virtual ICollection<BusinessEntityContact> BusinessEntityContacts { get; set; } = new List<BusinessEntityContact>();

    public virtual Person Person { get; set; }

    public virtual Store Store { get; set; }

    public virtual Vendor Vendor { get; set; }
}

[Register(typeof(IEntitySetLoader<MILL09.Models.BusinessEntity>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.BusinessEntity>), ServiceLifetime.Transient)]
public class BusinessEntityRepository : IEntitySetLoader<MILL09.Models.BusinessEntity>, IEntitySaver<MILL09.Models.BusinessEntity>
{
    private readonly AdventureWorks2019Context _dbContext;

    public BusinessEntityRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.BusinessEntity>
    public async Task<IReadOnlyList<MILL09.Models.BusinessEntity>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<BusinessEntity>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.BusinessEntity
        {
            BusinessEntityId = db.BusinessEntityId,
            ModifiedDate = db.ModifiedDate,
            Rowguid = db.Rowguid,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.BusinessEntity>

    #region IEntitySaver<MILL09.Models.BusinessEntity>
    public Task SaveAsync(MILL09.Models.BusinessEntity entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.BusinessEntity>
}
