// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Lookup table containing the types of business entity contacts.
/// </summary>
public partial class ContactType
{
    public static string SqlSchema => "Person";
    public static string SqlTableName => "ContactType";

    /// <summary>
    /// Primary key for ContactType records.
    /// </summary>
    public int ContactTypeId { get; set; }

    /// <summary>
    /// Contact type description.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<BusinessEntityContact> BusinessEntityContacts { get; set; } = new List<BusinessEntityContact>();
}

[Register(typeof(IEntitySetLoader<MILL09.Models.ContactType>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.ContactType>), ServiceLifetime.Transient)]
public class ContactTypeRepository : IEntitySetLoader<MILL09.Models.ContactType>, IEntitySaver<MILL09.Models.ContactType>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ContactTypeRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.ContactType>
    public async Task<IReadOnlyList<MILL09.Models.ContactType>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<ContactType>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.ContactType
        {
            ContactTypeId = db.ContactTypeId,
            ModifiedDate = db.ModifiedDate,
            Name = db.Name,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.ContactType>

    #region IEntitySaver<MILL09.Models.ContactType>
    public Task SaveAsync(MILL09.Models.ContactType entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.ContactType>
}
