// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Cross-reference table mapping ISO currency codes to a country or region.
/// </summary>
public partial class CountryRegionCurrency
{    /// <summary>
    /// ISO code for countries and regions. Foreign key to CountryRegion.CountryRegionCode.
    /// </summary>
    public string CountryRegionCode { get; set; }

    /// <summary>
    /// ISO standard currency code. Foreign key to Currency.CurrencyCode.
    /// </summary>
    public string CurrencyCode { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual CountryRegion CountryRegionCodeNavigation { get; set; }

    public virtual Currency CurrencyCodeNavigation { get; set; }
}

[Register(ServiceLifetime.Transient)]
public class CountryRegionCurrencyRepository : IEntitySetLoader<CountryRegionCurrency>, IEntitySaver<CountryRegionCurrency>
{
    private readonly AdventureWorks2019Context _dbContext;

    public CountryRegionCurrencyRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<CountryRegionCurrency>
    public async Task<IReadOnlyList<CountryRegionCurrency>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<CountryRegionCurrency>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<CountryRegionCurrency>

    #region IEntitySaver<CountryRegionCurrency>
    public async Task SaveAsync(CountryRegionCurrency entity, CancellationToken ct)
    {
        _dbContext.Set<CountryRegionCurrency>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<CountryRegionCurrency>
}

