// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Lookup table containing the ISO standard codes for countries and regions.
/// </summary>
public partial class CountryRegion
{    /// <summary>
    /// ISO standard code for countries and regions.
    /// </summary>
    public string CountryRegionCode { get; set; }

    /// <summary>
    /// Country or region name.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<CountryRegionCurrency> CountryRegionCurrencies { get; set; } = new List<CountryRegionCurrency>();

    public virtual ICollection<SalesTerritory> SalesTerritories { get; set; } = new List<SalesTerritory>();

    public virtual ICollection<StateProvince> StateProvinces { get; set; } = new List<StateProvince>();
}

[Register(ServiceLifetime.Transient)]
public class CountryRegionRepository : IEntitySetLoader<CountryRegion>, IEntitySaver<CountryRegion>
{
    private readonly AdventureWorks2019Context _dbContext;

    public CountryRegionRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<CountryRegion>
    public async Task<IReadOnlyList<CountryRegion>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<CountryRegion>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<CountryRegion>

    #region IEntitySaver<CountryRegion>
    public async Task SaveAsync(CountryRegion entity, CancellationToken ct)
    {
        _dbContext.Set<CountryRegion>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<CountryRegion>
}

