// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Customer credit card information.
/// </summary>
public partial class CreditCard
{
    /// <summary>
    /// Primary key for CreditCard records.
    /// </summary>
    public int CreditCardId { get; set; }

    /// <summary>
    /// Credit card name.
    /// </summary>
    public string CardType { get; set; }

    /// <summary>
    /// Credit card number.
    /// </summary>
    public string CardNumber { get; set; }

    /// <summary>
    /// Credit card expiration month.
    /// </summary>
    public byte ExpMonth { get; set; }

    /// <summary>
    /// Credit card expiration year.
    /// </summary>
    public short ExpYear { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<PersonCreditCard> PersonCreditCards { get; set; } = new List<PersonCreditCard>();

    public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; } = new List<SalesOrderHeader>();
}

[Register(typeof(IEntitySetLoader<MILL09.Models.CreditCard>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.CreditCard>), ServiceLifetime.Transient)]
public class CreditCardRepository : IEntitySetLoader<MILL09.Models.CreditCard>, IEntitySaver<MILL09.Models.CreditCard>
{
    private readonly AdventureWorks2019Context _dbContext;

    public CreditCardRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.CreditCard>
    public async Task<IReadOnlyList<MILL09.Models.CreditCard>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<CreditCard>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.CreditCard
        {
            CreditCardId = db.CreditCardId,
            CardNumber = db.CardNumber,
            CardType = db.CardType,
            ExpMonth = db.ExpMonth,
            ExpYear = db.ExpYear,
            ModifiedDate = db.ModifiedDate,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.CreditCard>

    #region IEntitySaver<MILL09.Models.CreditCard>
    public Task SaveAsync(MILL09.Models.CreditCard entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.CreditCard>
}
