// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Lookup table containing the languages in which some AdventureWorks data is stored.
/// </summary>
public partial class Culture
{
    public static string SqlSchema => "Production";
    public static string SqlTableName => "Culture";

    /// <summary>
    /// Primary key for Culture records.
    /// </summary>
    public string CultureId { get; set; }

    /// <summary>
    /// Culture description.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<ProductModelProductDescriptionCulture> ProductModelProductDescriptionCultures { get; set; } = new List<ProductModelProductDescriptionCulture>();
}

[Register(typeof(IEntitySetLoader<MILL09.Models.Culture>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.Culture>), ServiceLifetime.Transient)]
public class CultureRepository : IEntitySetLoader<MILL09.Models.Culture>, IEntitySaver<MILL09.Models.Culture>
{
    private readonly AdventureWorks2019Context _dbContext;

    public CultureRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.Culture>
    public async Task<IReadOnlyList<MILL09.Models.Culture>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<Culture>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.Culture
        {
            CultureId = db.CultureId,
            ModifiedDate = db.ModifiedDate,
            Name = db.Name,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.Culture>

    #region IEntitySaver<MILL09.Models.Culture>
    public Task SaveAsync(MILL09.Models.Culture entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.Culture>
}
