// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Lookup table containing standard ISO currencies.
/// </summary>
public partial class Currency
{
    public static string SqlSchema => "Sales";
    public static string SqlTableName => "Currency";

    /// <summary>
    /// The ISO code for the Currency.
    /// </summary>
    public string CurrencyCode { get; set; }

    /// <summary>
    /// Currency name.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<CountryRegionCurrency> CountryRegionCurrencies { get; set; } = new List<CountryRegionCurrency>();

    public virtual ICollection<CurrencyRate> CurrencyRateFromCurrencyCodeNavigations { get; set; } = new List<CurrencyRate>();

    public virtual ICollection<CurrencyRate> CurrencyRateToCurrencyCodeNavigations { get; set; } = new List<CurrencyRate>();
}

[Register(typeof(IEntitySetLoader<MILL09.Models.Currency>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.Currency>), ServiceLifetime.Transient)]
public class CurrencyRepository : IEntitySetLoader<MILL09.Models.Currency>, IEntitySaver<MILL09.Models.Currency>
{
    private readonly AdventureWorks2019Context _dbContext;

    public CurrencyRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.Currency>
    public async Task<IReadOnlyList<MILL09.Models.Currency>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<Currency>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.Currency
        {
            CurrencyCode = db.CurrencyCode,
            ModifiedDate = db.ModifiedDate,
            Name = db.Name,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.Currency>

    #region IEntitySaver<MILL09.Models.Currency>
    public Task SaveAsync(MILL09.Models.Currency entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.Currency>
}
