// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Lookup table containing the departments within the Adventure Works Cycles company.
/// </summary>
public partial class Department
{
    /// <summary>
    /// Primary key for Department records.
    /// </summary>
    public short DepartmentId { get; set; }

    /// <summary>
    /// Name of the department.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Name of the group to which the department belongs.
    /// </summary>
    public string GroupName { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<EmployeeDepartmentHistory> EmployeeDepartmentHistories { get; set; } = new List<EmployeeDepartmentHistory>();
}

[Register(typeof(IEntitySetLoader<MILL09.Models.Department>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.Department>), ServiceLifetime.Transient)]
public class DepartmentRepository : IEntitySetLoader<MILL09.Models.Department>, IEntitySaver<MILL09.Models.Department>
{
    private readonly AdventureWorks2019Context _dbContext;

    public DepartmentRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.Department>
    public async Task<IReadOnlyList<MILL09.Models.Department>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<Department>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.Department
        {
            DepartmentId = db.DepartmentId,
            GroupName = db.GroupName,
            ModifiedDate = db.ModifiedDate,
            Name = db.Name,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.Department>

    #region IEntitySaver<MILL09.Models.Department>
    public Task SaveAsync(MILL09.Models.Department entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.Department>
}
