// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Where to send a person email.
/// </summary>
public partial class EmailAddress
{
    public static string SqlSchema => "Person";
    public static string SqlTableName => "EmailAddress";

    /// <summary>
    /// Primary key. Person associated with this email address.  Foreign key to Person.BusinessEntityID
    /// </summary>
    public int BusinessEntityId { get; set; }

    /// <summary>
    /// Primary key. ID of this email address.
    /// </summary>
    public int EmailAddressId { get; set; }

    /// <summary>
    /// E-mail address for the person.
    /// </summary>
    public string EmailAddress1 { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Person BusinessEntity { get; set; }
}

[Register(typeof(IEntitySetLoader<MILL09.Models.EmailAddress>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.EmailAddress>), ServiceLifetime.Transient)]
public class EmailAddressRepository : IEntitySetLoader<MILL09.Models.EmailAddress>, IEntitySaver<MILL09.Models.EmailAddress>
{
    private readonly AdventureWorks2019Context _dbContext;

    public EmailAddressRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.EmailAddress>
    public async Task<IReadOnlyList<MILL09.Models.EmailAddress>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<EmailAddress>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.EmailAddress
        {
            BusinessEntityId = db.BusinessEntityId,
            EmailAddressId = db.EmailAddressId,
            EmailAddress1 = db.EmailAddress1,
            ModifiedDate = db.ModifiedDate,
            Rowguid = db.Rowguid,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.EmailAddress>

    #region IEntitySaver<MILL09.Models.EmailAddress>
    public Task SaveAsync(MILL09.Models.EmailAddress entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.EmailAddress>
}
