// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Employee department transfers.
/// </summary>
public partial class EmployeeDepartmentHistory
{    /// <summary>
    /// Employee identification number. Foreign key to Employee.BusinessEntityID.
    /// </summary>
    public int BusinessEntityId { get; set; }

    /// <summary>
    /// Department in which the employee worked including currently. Foreign key to Department.DepartmentID.
    /// </summary>
    public short DepartmentId { get; set; }

    /// <summary>
    /// Identifies which 8-hour shift the employee works. Foreign key to Shift.Shift.ID.
    /// </summary>
    public byte ShiftId { get; set; }

    /// <summary>
    /// Date the employee started work in the department.
    /// </summary>
    public DateOnly StartDate { get; set; }

    /// <summary>
    /// Date the employee left the department. NULL = Current department.
    /// </summary>
    public DateOnly? EndDate { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Employee BusinessEntity { get; set; }

    public virtual Department Department { get; set; }

    public virtual Shift Shift { get; set; }
}

[Register(ServiceLifetime.Transient)]
public class EmployeeDepartmentHistoryRepository : IEntitySetLoader<EmployeeDepartmentHistory>, IEntitySaver<EmployeeDepartmentHistory>
{
    private readonly AdventureWorks2019Context _dbContext;

    public EmployeeDepartmentHistoryRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<EmployeeDepartmentHistory>
    public async Task<IReadOnlyList<EmployeeDepartmentHistory>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<EmployeeDepartmentHistory>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<EmployeeDepartmentHistory>

    #region IEntitySaver<EmployeeDepartmentHistory>
    public async Task SaveAsync(EmployeeDepartmentHistory entity, CancellationToken ct)
    {
        _dbContext.Set<EmployeeDepartmentHistory>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<EmployeeDepartmentHistory>
}

