// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Employee information such as salary, department, and title.
/// </summary>
public partial class Employee
{
    public static string SqlSchema => "HumanResources";
    public static string SqlTableName => "Employee";

    /// <summary>
    /// Primary key for Employee records.  Foreign key to BusinessEntity.BusinessEntityID.
    /// </summary>
    public int BusinessEntityId { get; set; }

    /// <summary>
    /// Unique national identification number such as a social security number.
    /// </summary>
    public string NationalIdnumber { get; set; }

    /// <summary>
    /// Network login.
    /// </summary>
    public string LoginId { get; set; }

    /// <summary>
    /// The depth of the employee in the corporate hierarchy.
    /// </summary>
    public short? OrganizationLevel { get; set; }

    /// <summary>
    /// Work title such as Buyer or Sales Representative.
    /// </summary>
    public string JobTitle { get; set; }

    /// <summary>
    /// Date of birth.
    /// </summary>
    public DateOnly BirthDate { get; set; }

    /// <summary>
    /// M = Married, S = Single
    /// </summary>
    public string MaritalStatus { get; set; }

    /// <summary>
    /// M = Male, F = Female
    /// </summary>
    public string Gender { get; set; }

    /// <summary>
    /// Employee hired on this date.
    /// </summary>
    public DateOnly HireDate { get; set; }

    /// <summary>
    /// Job classification. 0 = Hourly, not exempt from collective bargaining. 1 = Salaried, exempt from collective bargaining.
    /// </summary>
    public bool SalariedFlag { get; set; }

    /// <summary>
    /// Number of available vacation hours.
    /// </summary>
    public short VacationHours { get; set; }

    /// <summary>
    /// Number of available sick leave hours.
    /// </summary>
    public short SickLeaveHours { get; set; }

    /// <summary>
    /// 0 = Inactive, 1 = Active
    /// </summary>
    public bool CurrentFlag { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Person BusinessEntity { get; set; }

    public virtual ICollection<EmployeeDepartmentHistory> EmployeeDepartmentHistories { get; set; } = new List<EmployeeDepartmentHistory>();

    public virtual ICollection<EmployeePayHistory> EmployeePayHistories { get; set; } = new List<EmployeePayHistory>();

    public virtual ICollection<JobCandidate> JobCandidates { get; set; } = new List<JobCandidate>();

    public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; } = new List<PurchaseOrderHeader>();

    public virtual SalesPerson SalesPerson { get; set; }
}

[Register(typeof(IEntitySetLoader<MILL09.Models.Employee>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.Employee>), ServiceLifetime.Transient)]
public class EmployeeRepository : IEntitySetLoader<MILL09.Models.Employee>, IEntitySaver<MILL09.Models.Employee>
{
    private readonly AdventureWorks2019Context _dbContext;

    public EmployeeRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.Employee>
    public async Task<IReadOnlyList<MILL09.Models.Employee>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<Employee>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.Employee
        {
            BusinessEntityId = db.BusinessEntityId,
            BirthDate = db.BirthDate,
            CurrentFlag = db.CurrentFlag,
            Gender = db.Gender,
            HireDate = db.HireDate,
            JobTitle = db.JobTitle,
            LoginId = db.LoginId,
            MaritalStatus = db.MaritalStatus,
            ModifiedDate = db.ModifiedDate,
            NationalIdnumber = db.NationalIdnumber,
            OrganizationLevel = db.OrganizationLevel,
            Rowguid = db.Rowguid,
            SalariedFlag = db.SalariedFlag,
            SickLeaveHours = db.SickLeaveHours,
            VacationHours = db.VacationHours,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.Employee>

    #region IEntitySaver<MILL09.Models.Employee>
    public Task SaveAsync(MILL09.Models.Employee entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.Employee>
}
