// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Audit table tracking errors in the the AdventureWorks database that are caught by the CATCH block of a TRY...CATCH construct. Data is inserted by stored procedure dbo.uspLogError when it is executed from inside the CATCH block of a TRY...CATCH construct.
/// </summary>
public partial class ErrorLog
{
    /// <summary>
    /// Primary key for ErrorLog records.
    /// </summary>
    public int ErrorLogId { get; set; }

    /// <summary>
    /// The date and time at which the error occurred.
    /// </summary>
    public DateTime ErrorTime { get; set; }

    /// <summary>
    /// The user who executed the batch in which the error occurred.
    /// </summary>
    public string UserName { get; set; }

    /// <summary>
    /// The error number of the error that occurred.
    /// </summary>
    public int ErrorNumber { get; set; }

    /// <summary>
    /// The severity of the error that occurred.
    /// </summary>
    public int? ErrorSeverity { get; set; }

    /// <summary>
    /// The state number of the error that occurred.
    /// </summary>
    public int? ErrorState { get; set; }

    /// <summary>
    /// The name of the stored procedure or trigger where the error occurred.
    /// </summary>
    public string ErrorProcedure { get; set; }

    /// <summary>
    /// The line number at which the error occurred.
    /// </summary>
    public int? ErrorLine { get; set; }

    /// <summary>
    /// The message text of the error that occurred.
    /// </summary>
    public string ErrorMessage { get; set; }
}

[Register(typeof(IEntitySetLoader<MILL09.Models.ErrorLog>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.ErrorLog>), ServiceLifetime.Transient)]
public class ErrorLogRepository : IEntitySetLoader<MILL09.Models.ErrorLog>, IEntitySaver<MILL09.Models.ErrorLog>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ErrorLogRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.ErrorLog>
    public async Task<IReadOnlyList<MILL09.Models.ErrorLog>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<ErrorLog>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.ErrorLog
        {
            ErrorLogId = db.ErrorLogId,
            ErrorLine = db.ErrorLine,
            ErrorMessage = db.ErrorMessage,
            ErrorNumber = db.ErrorNumber,
            ErrorProcedure = db.ErrorProcedure,
            ErrorSeverity = db.ErrorSeverity,
            ErrorState = db.ErrorState,
            ErrorTime = db.ErrorTime,
            UserName = db.UserName,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.ErrorLog>

    #region IEntitySaver<MILL09.Models.ErrorLog>
    public Task SaveAsync(MILL09.Models.ErrorLog entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.ErrorLog>
}
