// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Bicycle assembly diagrams.
/// </summary>
public partial class Illustration
{
    /// <summary>
    /// Primary key for Illustration records.
    /// </summary>
    public int IllustrationId { get; set; }

    /// <summary>
    /// Illustrations used in manufacturing instructions. Stored as XML.
    /// </summary>
    public string Diagram { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<ProductModelIllustration> ProductModelIllustrations { get; set; } = new List<ProductModelIllustration>();
}

[Register(typeof(IEntitySetLoader<MILL09.Models.Illustration>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.Illustration>), ServiceLifetime.Transient)]
public class IllustrationRepository : IEntitySetLoader<MILL09.Models.Illustration>, IEntitySaver<MILL09.Models.Illustration>
{
    private readonly AdventureWorks2019Context _dbContext;

    public IllustrationRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.Illustration>
    public async Task<IReadOnlyList<MILL09.Models.Illustration>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<Illustration>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.Illustration
        {
            IllustrationId = db.IllustrationId,
            Diagram = db.Diagram,
            ModifiedDate = db.ModifiedDate,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.Illustration>

    #region IEntitySaver<MILL09.Models.Illustration>
    public Task SaveAsync(MILL09.Models.Illustration entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.Illustration>
}
