// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Bicycle assembly diagrams.
/// </summary>
public partial class Illustration
{    /// <summary>
    /// Primary key for Illustration records.
    /// </summary>
    public int IllustrationId { get; set; }

    /// <summary>
    /// Illustrations used in manufacturing instructions. Stored as XML.
    /// </summary>
    public string Diagram { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<ProductModelIllustration> ProductModelIllustrations { get; set; } = new List<ProductModelIllustration>();
}

[Register(ServiceLifetime.Transient)]
public class IllustrationRepository : IEntitySetLoader<Illustration>, IEntitySaver<Illustration>
{
    private readonly AdventureWorks2019Context _dbContext;

    public IllustrationRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<Illustration>
    public async Task<IReadOnlyList<Illustration>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<Illustration>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<Illustration>

    #region IEntitySaver<Illustration>
    public async Task SaveAsync(Illustration entity, CancellationToken ct)
    {
        _dbContext.Set<Illustration>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<Illustration>
}

