// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Product inventory and manufacturing locations.
/// </summary>
public partial class Location
{
    public static string SqlSchema => "Production";
    public static string SqlTableName => "Location";

    /// <summary>
    /// Primary key for Location records.
    /// </summary>
    public short LocationId { get; set; }

    /// <summary>
    /// Location description.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Standard hourly cost of the manufacturing location.
    /// </summary>
    public decimal CostRate { get; set; }

    /// <summary>
    /// Work capacity (in hours) of the manufacturing location.
    /// </summary>
    public decimal Availability { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<ProductInventory> ProductInventories { get; set; } = new List<ProductInventory>();

    public virtual ICollection<WorkOrderRouting> WorkOrderRoutings { get; set; } = new List<WorkOrderRouting>();
}

[Register(typeof(IEntitySetLoader<MILL09.Models.Location>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.Location>), ServiceLifetime.Transient)]
public class LocationRepository : IEntitySetLoader<MILL09.Models.Location>, IEntitySaver<MILL09.Models.Location>
{
    private readonly AdventureWorks2019Context _dbContext;

    public LocationRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.Location>
    public async Task<IReadOnlyList<MILL09.Models.Location>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<Location>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.Location
        {
            LocationId = db.LocationId,
            Availability = db.Availability,
            CostRate = db.CostRate,
            ModifiedDate = db.ModifiedDate,
            Name = db.Name,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.Location>

    #region IEntitySaver<MILL09.Models.Location>
    public Task SaveAsync(MILL09.Models.Location entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.Location>
}
