// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Product inventory and manufacturing locations.
/// </summary>
public partial class Location
{    /// <summary>
    /// Primary key for Location records.
    /// </summary>
    public short LocationId { get; set; }

    /// <summary>
    /// Location description.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Standard hourly cost of the manufacturing location.
    /// </summary>
    public decimal CostRate { get; set; }

    /// <summary>
    /// Work capacity (in hours) of the manufacturing location.
    /// </summary>
    public decimal Availability { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<ProductInventory> ProductInventories { get; set; } = new List<ProductInventory>();

    public virtual ICollection<WorkOrderRouting> WorkOrderRoutings { get; set; } = new List<WorkOrderRouting>();
}

[Register(ServiceLifetime.Transient)]
public class LocationRepository : IEntitySetLoader<Location>, IEntitySaver<Location>
{
    private readonly AdventureWorks2019Context _dbContext;

    public LocationRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<Location>
    public async Task<IReadOnlyList<Location>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<Location>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<Location>

    #region IEntitySaver<Location>
    public async Task SaveAsync(Location entity, CancellationToken ct)
    {
        _dbContext.Set<Location>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<Location>
}

