// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// One way hashed authentication information
/// </summary>
public partial class Password
{
    public int BusinessEntityId { get; set; }

    /// <summary>
    /// Password for the e-mail account.
    /// </summary>
    public string PasswordHash { get; set; }

    /// <summary>
    /// Random value concatenated with the password string before the password is hashed.
    /// </summary>
    public string PasswordSalt { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Person BusinessEntity { get; set; }
}

[Register(typeof(IEntitySetLoader<MILL09.Models.Password>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.Password>), ServiceLifetime.Transient)]
public class PasswordRepository : IEntitySetLoader<MILL09.Models.Password>, IEntitySaver<MILL09.Models.Password>
{
    private readonly AdventureWorks2019Context _dbContext;

    public PasswordRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.Password>
    public async Task<IReadOnlyList<MILL09.Models.Password>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<Password>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.Password
        {
            BusinessEntityId = db.BusinessEntityId,
            ModifiedDate = db.ModifiedDate,
            PasswordHash = db.PasswordHash,
            PasswordSalt = db.PasswordSalt,
            Rowguid = db.Rowguid,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.Password>

    #region IEntitySaver<MILL09.Models.Password>
    public Task SaveAsync(MILL09.Models.Password entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.Password>
}
