// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Cross-reference table mapping people to their credit card information in the CreditCard table. 
/// </summary>
public partial class PersonCreditCard
{
    /// <summary>
    /// Business entity identification number. Foreign key to Person.BusinessEntityID.
    /// </summary>
    public int BusinessEntityId { get; set; }

    /// <summary>
    /// Credit card identification number. Foreign key to CreditCard.CreditCardID.
    /// </summary>
    public int CreditCardId { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Person BusinessEntity { get; set; }

    public virtual CreditCard CreditCard { get; set; }
}

[Register(typeof(IEntitySetLoader<MILL09.Models.PersonCreditCard>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.PersonCreditCard>), ServiceLifetime.Transient)]
public class PersonCreditCardRepository : IEntitySetLoader<MILL09.Models.PersonCreditCard>, IEntitySaver<MILL09.Models.PersonCreditCard>
{
    private readonly AdventureWorks2019Context _dbContext;

    public PersonCreditCardRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.PersonCreditCard>
    public async Task<IReadOnlyList<MILL09.Models.PersonCreditCard>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<PersonCreditCard>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.PersonCreditCard
        {
            BusinessEntityId = db.BusinessEntityId,
            CreditCardId = db.CreditCardId,
            ModifiedDate = db.ModifiedDate,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.PersonCreditCard>

    #region IEntitySaver<MILL09.Models.PersonCreditCard>
    public Task SaveAsync(MILL09.Models.PersonCreditCard entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.PersonCreditCard>
}
