// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Type of phone number of a person.
/// </summary>
public partial class PhoneNumberType
{
    /// <summary>
    /// Primary key for telephone number type records.
    /// </summary>
    public int PhoneNumberTypeId { get; set; }

    /// <summary>
    /// Name of the telephone number type
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<PersonPhone> PersonPhones { get; set; } = new List<PersonPhone>();
}

[Register(typeof(IEntitySetLoader<MILL09.Models.PhoneNumberType>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.PhoneNumberType>), ServiceLifetime.Transient)]
public class PhoneNumberTypeRepository : IEntitySetLoader<MILL09.Models.PhoneNumberType>, IEntitySaver<MILL09.Models.PhoneNumberType>
{
    private readonly AdventureWorks2019Context _dbContext;

    public PhoneNumberTypeRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.PhoneNumberType>
    public async Task<IReadOnlyList<MILL09.Models.PhoneNumberType>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<PhoneNumberType>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.PhoneNumberType
        {
            PhoneNumberTypeId = db.PhoneNumberTypeId,
            ModifiedDate = db.ModifiedDate,
            Name = db.Name,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.PhoneNumberType>

    #region IEntitySaver<MILL09.Models.PhoneNumberType>
    public Task SaveAsync(MILL09.Models.PhoneNumberType entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.PhoneNumberType>
}
