// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Changes in the cost of a product over time.
/// </summary>
public partial class ProductCostHistory
{
    /// <summary>
    /// Product identification number. Foreign key to Product.ProductID
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// Product cost start date.
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// Product cost end date.
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// Standard cost of the product.
    /// </summary>
    public decimal StandardCost { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
}

[Register(typeof(IEntitySetLoader<MILL09.Models.ProductCostHistory>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.ProductCostHistory>), ServiceLifetime.Transient)]
public class ProductCostHistoryRepository : IEntitySetLoader<MILL09.Models.ProductCostHistory>, IEntitySaver<MILL09.Models.ProductCostHistory>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ProductCostHistoryRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.ProductCostHistory>
    public async Task<IReadOnlyList<MILL09.Models.ProductCostHistory>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<ProductCostHistory>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.ProductCostHistory
        {
            ProductId = db.ProductId,
            StartDate = db.StartDate,
            EndDate = db.EndDate,
            ModifiedDate = db.ModifiedDate,
            StandardCost = db.StandardCost,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.ProductCostHistory>

    #region IEntitySaver<MILL09.Models.ProductCostHistory>
    public Task SaveAsync(MILL09.Models.ProductCostHistory entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.ProductCostHistory>
}
