// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Product model classification.
/// </summary>
public partial class ProductModel
{
    /// <summary>
    /// Primary key for ProductModel records.
    /// </summary>
    public int ProductModelId { get; set; }

    /// <summary>
    /// Product model description.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Detailed product catalog information in xml format.
    /// </summary>
    public string CatalogDescription { get; set; }

    /// <summary>
    /// Manufacturing instructions in xml format.
    /// </summary>
    public string Instructions { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<ProductModelIllustration> ProductModelIllustrations { get; set; } = new List<ProductModelIllustration>();

    public virtual ICollection<ProductModelProductDescriptionCulture> ProductModelProductDescriptionCultures { get; set; } = new List<ProductModelProductDescriptionCulture>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}

[Register(typeof(IEntitySetLoader<MILL09.Models.ProductModel>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.ProductModel>), ServiceLifetime.Transient)]
public class ProductModelRepository : IEntitySetLoader<MILL09.Models.ProductModel>, IEntitySaver<MILL09.Models.ProductModel>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ProductModelRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.ProductModel>
    public async Task<IReadOnlyList<MILL09.Models.ProductModel>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<ProductModel>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.ProductModel
        {
            ProductModelId = db.ProductModelId,
            CatalogDescription = db.CatalogDescription,
            Instructions = db.Instructions,
            ModifiedDate = db.ModifiedDate,
            Name = db.Name,
            Rowguid = db.Rowguid,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.ProductModel>

    #region IEntitySaver<MILL09.Models.ProductModel>
    public Task SaveAsync(MILL09.Models.ProductModel entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.ProductModel>
}
