// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Changes in the list price of a product over time.
/// </summary>
public partial class ProductListPriceHistory
{    /// <summary>
    /// Product identification number. Foreign key to Product.ProductID
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// List price start date.
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// List price end date
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// Product list price.
    /// </summary>
    public decimal ListPrice { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
}

[Register(ServiceLifetime.Transient)]
public class ProductListPriceHistoryRepository : IEntitySetLoader<ProductListPriceHistory>, IEntitySaver<ProductListPriceHistory>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ProductListPriceHistoryRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<ProductListPriceHistory>
    public async Task<IReadOnlyList<ProductListPriceHistory>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<ProductListPriceHistory>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<ProductListPriceHistory>

    #region IEntitySaver<ProductListPriceHistory>
    public async Task SaveAsync(ProductListPriceHistory entity, CancellationToken ct)
    {
        _dbContext.Set<ProductListPriceHistory>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<ProductListPriceHistory>
}

