// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Cross-reference table mapping product models and illustrations.
/// </summary>
public partial class ProductModelIllustration
{    /// <summary>
    /// Primary key. Foreign key to ProductModel.ProductModelID.
    /// </summary>
    public int ProductModelId { get; set; }

    /// <summary>
    /// Primary key. Foreign key to Illustration.IllustrationID.
    /// </summary>
    public int IllustrationId { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Illustration Illustration { get; set; }

    public virtual ProductModel ProductModel { get; set; }
}

[Register(ServiceLifetime.Transient)]
public class ProductModelIllustrationRepository : IEntitySetLoader<ProductModelIllustration>, IEntitySaver<ProductModelIllustration>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ProductModelIllustrationRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<ProductModelIllustration>
    public async Task<IReadOnlyList<ProductModelIllustration>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<ProductModelIllustration>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<ProductModelIllustration>

    #region IEntitySaver<ProductModelIllustration>
    public async Task SaveAsync(ProductModelIllustration entity, CancellationToken ct)
    {
        _dbContext.Set<ProductModelIllustration>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<ProductModelIllustration>
}

