// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Cross-reference table mapping vendors with the products they supply.
/// </summary>
public partial class ProductVendor
{
    public static string SqlSchema => "Purchasing";
    public static string SqlTableName => "ProductVendor";

    /// <summary>
    /// Primary key. Foreign key to Product.ProductID.
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// Primary key. Foreign key to Vendor.BusinessEntityID.
    /// </summary>
    public int BusinessEntityId { get; set; }

    /// <summary>
    /// The average span of time (in days) between placing an order with the vendor and receiving the purchased product.
    /// </summary>
    public int AverageLeadTime { get; set; }

    /// <summary>
    /// The vendor&apos;s usual selling price.
    /// </summary>
    public decimal StandardPrice { get; set; }

    /// <summary>
    /// The selling price when last purchased.
    /// </summary>
    public decimal? LastReceiptCost { get; set; }

    /// <summary>
    /// Date the product was last received by the vendor.
    /// </summary>
    public DateTime? LastReceiptDate { get; set; }

    /// <summary>
    /// The maximum quantity that should be ordered.
    /// </summary>
    public int MinOrderQty { get; set; }

    /// <summary>
    /// The minimum quantity that should be ordered.
    /// </summary>
    public int MaxOrderQty { get; set; }

    /// <summary>
    /// The quantity currently on order.
    /// </summary>
    public int? OnOrderQty { get; set; }

    /// <summary>
    /// The product&apos;s unit of measure.
    /// </summary>
    public string UnitMeasureCode { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Vendor BusinessEntity { get; set; }

    public virtual Product Product { get; set; }

    public virtual UnitMeasure UnitMeasureCodeNavigation { get; set; }
}

[Register(typeof(IEntitySetLoader<MILL09.Models.ProductVendor>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.ProductVendor>), ServiceLifetime.Transient)]
public class ProductVendorRepository : IEntitySetLoader<MILL09.Models.ProductVendor>, IEntitySaver<MILL09.Models.ProductVendor>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ProductVendorRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.ProductVendor>
    public async Task<IReadOnlyList<MILL09.Models.ProductVendor>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<ProductVendor>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.ProductVendor
        {
            ProductId = db.ProductId,
            BusinessEntityId = db.BusinessEntityId,
            AverageLeadTime = db.AverageLeadTime,
            LastReceiptCost = db.LastReceiptCost,
            LastReceiptDate = db.LastReceiptDate,
            MaxOrderQty = db.MaxOrderQty,
            MinOrderQty = db.MinOrderQty,
            ModifiedDate = db.ModifiedDate,
            OnOrderQty = db.OnOrderQty,
            StandardPrice = db.StandardPrice,
            UnitMeasureCode = db.UnitMeasureCode,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.ProductVendor>

    #region IEntitySaver<MILL09.Models.ProductVendor>
    public Task SaveAsync(MILL09.Models.ProductVendor entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.ProductVendor>
}
