// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Cross-reference table mapping products and product photos.
/// </summary>
public partial class ProductProductPhoto
{    /// <summary>
    /// Product identification number. Foreign key to Product.ProductID.
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// Product photo identification number. Foreign key to ProductPhoto.ProductPhotoID.
    /// </summary>
    public int ProductPhotoId { get; set; }

    /// <summary>
    /// 0 = Photo is not the principal image. 1 = Photo is the principal image.
    /// </summary>
    public bool Primary { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }

    public virtual ProductPhoto ProductPhoto { get; set; }
}

[Register(ServiceLifetime.Transient)]
public class ProductProductPhotoRepository : IEntitySetLoader<ProductProductPhoto>, IEntitySaver<ProductProductPhoto>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ProductProductPhotoRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<ProductProductPhoto>
    public async Task<IReadOnlyList<ProductProductPhoto>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<ProductProductPhoto>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<ProductProductPhoto>

    #region IEntitySaver<ProductProductPhoto>
    public async Task SaveAsync(ProductProductPhoto entity, CancellationToken ct)
    {
        _dbContext.Set<ProductProductPhoto>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<ProductProductPhoto>
}

