// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Product subcategories. See ProductCategory table.
/// </summary>
public partial class ProductSubcategory
{    /// <summary>
    /// Primary key for ProductSubcategory records.
    /// </summary>
    public int ProductSubcategoryId { get; set; }

    /// <summary>
    /// Product category identification number. Foreign key to ProductCategory.ProductCategoryID.
    /// </summary>
    public int ProductCategoryId { get; set; }

    /// <summary>
    /// Subcategory description.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ProductCategory ProductCategory { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}

[Register(ServiceLifetime.Transient)]
public class ProductSubcategoryRepository : IEntitySetLoader<ProductSubcategory>, IEntitySaver<ProductSubcategory>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ProductSubcategoryRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<ProductSubcategory>
    public async Task<IReadOnlyList<ProductSubcategory>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<ProductSubcategory>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<ProductSubcategory>

    #region IEntitySaver<ProductSubcategory>
    public async Task SaveAsync(ProductSubcategory entity, CancellationToken ct)
    {
        _dbContext.Set<ProductSubcategory>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<ProductSubcategory>
}

