// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// High-level product categorization.
/// </summary>
public partial class ProductCategory
{    /// <summary>
    /// Primary key for ProductCategory records.
    /// </summary>
    public int ProductCategoryId { get; set; }

    /// <summary>
    /// Category description.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<ProductSubcategory> ProductSubcategories { get; set; } = new List<ProductSubcategory>();
}

[Register(ServiceLifetime.Transient)]
public class ProductCategoryRepository : IEntitySetLoader<ProductCategory>, IEntitySaver<ProductCategory>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ProductCategoryRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<ProductCategory>
    public async Task<IReadOnlyList<ProductCategory>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<ProductCategory>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<ProductCategory>

    #region IEntitySaver<ProductCategory>
    public async Task SaveAsync(ProductCategory entity, CancellationToken ct)
    {
        _dbContext.Set<ProductCategory>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<ProductCategory>
}

