// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Product inventory information.
/// </summary>
public partial class ProductInventory
{    /// <summary>
    /// Product identification number. Foreign key to Product.ProductID.
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// Inventory location identification number. Foreign key to Location.LocationID. 
    /// </summary>
    public short LocationId { get; set; }

    /// <summary>
    /// Storage compartment within an inventory location.
    /// </summary>
    public string Shelf { get; set; }

    /// <summary>
    /// Storage container on a shelf in an inventory location.
    /// </summary>
    public byte Bin { get; set; }

    /// <summary>
    /// Quantity of products in the inventory location.
    /// </summary>
    public short Quantity { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Location Location { get; set; }

    public virtual Product Product { get; set; }
}

[Register(ServiceLifetime.Transient)]
public class ProductInventoryRepository : IEntitySetLoader<ProductInventory>, IEntitySaver<ProductInventory>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ProductInventoryRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<ProductInventory>
    public async Task<IReadOnlyList<ProductInventory>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<ProductInventory>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<ProductInventory>

    #region IEntitySaver<ProductInventory>
    public async Task SaveAsync(ProductInventory entity, CancellationToken ct)
    {
        _dbContext.Set<ProductInventory>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<ProductInventory>
}

