// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Product images.
/// </summary>
public partial class ProductPhoto
{
    /// <summary>
    /// Primary key for ProductPhoto records.
    /// </summary>
    public int ProductPhotoId { get; set; }

    /// <summary>
    /// Small image of the product.
    /// </summary>
    public byte[] ThumbNailPhoto { get; set; }

    /// <summary>
    /// Small image file name.
    /// </summary>
    public string ThumbnailPhotoFileName { get; set; }

    /// <summary>
    /// Large image of the product.
    /// </summary>
    public byte[] LargePhoto { get; set; }

    /// <summary>
    /// Large image file name.
    /// </summary>
    public string LargePhotoFileName { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<ProductProductPhoto> ProductProductPhotos { get; set; } = new List<ProductProductPhoto>();
}

[Register(typeof(IEntitySetLoader<MILL09.Models.ProductPhoto>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.ProductPhoto>), ServiceLifetime.Transient)]
public class ProductPhotoRepository : IEntitySetLoader<MILL09.Models.ProductPhoto>, IEntitySaver<MILL09.Models.ProductPhoto>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ProductPhotoRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.ProductPhoto>
    public async Task<IReadOnlyList<MILL09.Models.ProductPhoto>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<ProductPhoto>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.ProductPhoto
        {
            ProductPhotoId = db.ProductPhotoId,
            LargePhoto = db.LargePhoto,
            LargePhotoFileName = db.LargePhotoFileName,
            ModifiedDate = db.ModifiedDate,
            ThumbNailPhoto = db.ThumbNailPhoto,
            ThumbnailPhotoFileName = db.ThumbnailPhotoFileName,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.ProductPhoto>

    #region IEntitySaver<MILL09.Models.ProductPhoto>
    public Task SaveAsync(MILL09.Models.ProductPhoto entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.ProductPhoto>
}
