// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Cross-reference table mapping vendors with the products they supply.
/// </summary>
public partial class ProductVendor
{    /// <summary>
    /// Primary key. Foreign key to Product.ProductID.
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// Primary key. Foreign key to Vendor.BusinessEntityID.
    /// </summary>
    public int BusinessEntityId { get; set; }

    /// <summary>
    /// The average span of time (in days) between placing an order with the vendor and receiving the purchased product.
    /// </summary>
    public int AverageLeadTime { get; set; }

    /// <summary>
    /// The vendor&apos;s usual selling price.
    /// </summary>
    public decimal StandardPrice { get; set; }

    /// <summary>
    /// The selling price when last purchased.
    /// </summary>
    public decimal? LastReceiptCost { get; set; }

    /// <summary>
    /// Date the product was last received by the vendor.
    /// </summary>
    public DateTime? LastReceiptDate { get; set; }

    /// <summary>
    /// The maximum quantity that should be ordered.
    /// </summary>
    public int MinOrderQty { get; set; }

    /// <summary>
    /// The minimum quantity that should be ordered.
    /// </summary>
    public int MaxOrderQty { get; set; }

    /// <summary>
    /// The quantity currently on order.
    /// </summary>
    public int? OnOrderQty { get; set; }

    /// <summary>
    /// The product&apos;s unit of measure.
    /// </summary>
    public string UnitMeasureCode { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Vendor BusinessEntity { get; set; }

    public virtual Product Product { get; set; }

    public virtual UnitMeasure UnitMeasureCodeNavigation { get; set; }
}

[Register(ServiceLifetime.Transient)]
public class ProductVendorRepository : IEntitySetLoader<ProductVendor>, IEntitySaver<ProductVendor>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ProductVendorRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<ProductVendor>
    public async Task<IReadOnlyList<ProductVendor>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<ProductVendor>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<ProductVendor>

    #region IEntitySaver<ProductVendor>
    public async Task SaveAsync(ProductVendor entity, CancellationToken ct)
    {
        _dbContext.Set<ProductVendor>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<ProductVendor>
}

