// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// High-level product categorization.
/// </summary>
public partial class ProductCategory
{
    /// <summary>
    /// Primary key for ProductCategory records.
    /// </summary>
    public int ProductCategoryId { get; set; }

    /// <summary>
    /// Category description.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<ProductSubcategory> ProductSubcategories { get; set; } = new List<ProductSubcategory>();
}

[Register(typeof(IEntitySetLoader<MILL09.Models.ProductCategory>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.ProductCategory>), ServiceLifetime.Transient)]
public class ProductCategoryRepository : IEntitySetLoader<MILL09.Models.ProductCategory>, IEntitySaver<MILL09.Models.ProductCategory>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ProductCategoryRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.ProductCategory>
    public async Task<IReadOnlyList<MILL09.Models.ProductCategory>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<ProductCategory>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.ProductCategory
        {
            ProductCategoryId = db.ProductCategoryId,
            ModifiedDate = db.ModifiedDate,
            Name = db.Name,
            Rowguid = db.Rowguid,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.ProductCategory>

    #region IEntitySaver<MILL09.Models.ProductCategory>
    public Task SaveAsync(MILL09.Models.ProductCategory entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.ProductCategory>
}
