// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// General purchase order information. See PurchaseOrderDetail.
/// </summary>
public partial class PurchaseOrderHeader
{
    public static string SqlSchema => "Purchasing";
    public static string SqlTableName => "PurchaseOrderHeader";

    /// <summary>
    /// Primary key.
    /// </summary>
    public int PurchaseOrderId { get; set; }

    /// <summary>
    /// Incremental number to track changes to the purchase order over time.
    /// </summary>
    public byte RevisionNumber { get; set; }

    /// <summary>
    /// Order current status. 1 = Pending; 2 = Approved; 3 = Rejected; 4 = Complete
    /// </summary>
    public byte Status { get; set; }

    /// <summary>
    /// Employee who created the purchase order. Foreign key to Employee.BusinessEntityID.
    /// </summary>
    public int EmployeeId { get; set; }

    /// <summary>
    /// Vendor with whom the purchase order is placed. Foreign key to Vendor.BusinessEntityID.
    /// </summary>
    public int VendorId { get; set; }

    /// <summary>
    /// Shipping method. Foreign key to ShipMethod.ShipMethodID.
    /// </summary>
    public int ShipMethodId { get; set; }

    /// <summary>
    /// Purchase order creation date.
    /// </summary>
    public DateTime OrderDate { get; set; }

    /// <summary>
    /// Estimated shipment date from the vendor.
    /// </summary>
    public DateTime? ShipDate { get; set; }

    /// <summary>
    /// Purchase order subtotal. Computed as SUM(PurchaseOrderDetail.LineTotal)for the appropriate PurchaseOrderID.
    /// </summary>
    public decimal SubTotal { get; set; }

    /// <summary>
    /// Tax amount.
    /// </summary>
    public decimal TaxAmt { get; set; }

    /// <summary>
    /// Shipping cost.
    /// </summary>
    public decimal Freight { get; set; }

    /// <summary>
    /// Total due to vendor. Computed as Subtotal + TaxAmt + Freight.
    /// </summary>
    public decimal TotalDue { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; } = new List<PurchaseOrderDetail>();

    public virtual ShipMethod ShipMethod { get; set; }

    public virtual Vendor Vendor { get; set; }
}

[Register(typeof(IEntitySetLoader<MILL09.Models.PurchaseOrderHeader>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.PurchaseOrderHeader>), ServiceLifetime.Transient)]
public class PurchaseOrderHeaderRepository : IEntitySetLoader<MILL09.Models.PurchaseOrderHeader>, IEntitySaver<MILL09.Models.PurchaseOrderHeader>
{
    private readonly AdventureWorks2019Context _dbContext;

    public PurchaseOrderHeaderRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.PurchaseOrderHeader>
    public async Task<IReadOnlyList<MILL09.Models.PurchaseOrderHeader>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<PurchaseOrderHeader>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.PurchaseOrderHeader
        {
            PurchaseOrderId = db.PurchaseOrderId,
            EmployeeId = db.EmployeeId,
            Freight = db.Freight,
            ModifiedDate = db.ModifiedDate,
            OrderDate = db.OrderDate,
            RevisionNumber = db.RevisionNumber,
            ShipDate = db.ShipDate,
            ShipMethodId = db.ShipMethodId,
            Status = db.Status,
            SubTotal = db.SubTotal,
            TaxAmt = db.TaxAmt,
            TotalDue = db.TotalDue,
            VendorId = db.VendorId,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.PurchaseOrderHeader>

    #region IEntitySaver<MILL09.Models.PurchaseOrderHeader>
    public Task SaveAsync(MILL09.Models.PurchaseOrderHeader entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.PurchaseOrderHeader>
}
