// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Individual products associated with a specific purchase order. See PurchaseOrderHeader.
/// </summary>
public partial class PurchaseOrderDetail
{
    /// <summary>
    /// Primary key. Foreign key to PurchaseOrderHeader.PurchaseOrderID.
    /// </summary>
    public int PurchaseOrderId { get; set; }

    /// <summary>
    /// Primary key. One line number per purchased product.
    /// </summary>
    public int PurchaseOrderDetailId { get; set; }

    /// <summary>
    /// Date the product is expected to be received.
    /// </summary>
    public DateTime DueDate { get; set; }

    /// <summary>
    /// Quantity ordered.
    /// </summary>
    public short OrderQty { get; set; }

    /// <summary>
    /// Product identification number. Foreign key to Product.ProductID.
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// Vendor&apos;s selling price of a single product.
    /// </summary>
    public decimal UnitPrice { get; set; }

    /// <summary>
    /// Per product subtotal. Computed as OrderQty * UnitPrice.
    /// </summary>
    public decimal LineTotal { get; set; }

    /// <summary>
    /// Quantity actually received from the vendor.
    /// </summary>
    public decimal ReceivedQty { get; set; }

    /// <summary>
    /// Quantity rejected during inspection.
    /// </summary>
    public decimal RejectedQty { get; set; }

    /// <summary>
    /// Quantity accepted into inventory. Computed as ReceivedQty - RejectedQty.
    /// </summary>
    public decimal StockedQty { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }

    public virtual PurchaseOrderHeader PurchaseOrder { get; set; }
}

[Register(typeof(IEntitySetLoader<MILL09.Models.PurchaseOrderDetail>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.PurchaseOrderDetail>), ServiceLifetime.Transient)]
public class PurchaseOrderDetailRepository : IEntitySetLoader<MILL09.Models.PurchaseOrderDetail>, IEntitySaver<MILL09.Models.PurchaseOrderDetail>
{
    private readonly AdventureWorks2019Context _dbContext;

    public PurchaseOrderDetailRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.PurchaseOrderDetail>
    public async Task<IReadOnlyList<MILL09.Models.PurchaseOrderDetail>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<PurchaseOrderDetail>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.PurchaseOrderDetail
        {
            PurchaseOrderId = db.PurchaseOrderId,
            PurchaseOrderDetailId = db.PurchaseOrderDetailId,
            DueDate = db.DueDate,
            LineTotal = db.LineTotal,
            ModifiedDate = db.ModifiedDate,
            OrderQty = db.OrderQty,
            ProductId = db.ProductId,
            ReceivedQty = db.ReceivedQty,
            RejectedQty = db.RejectedQty,
            StockedQty = db.StockedQty,
            UnitPrice = db.UnitPrice,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.PurchaseOrderDetail>

    #region IEntitySaver<MILL09.Models.PurchaseOrderDetail>
    public Task SaveAsync(MILL09.Models.PurchaseOrderDetail entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.PurchaseOrderDetail>
}
