// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Sales representative transfers to other sales territories.
/// </summary>
public partial class SalesTerritoryHistory
{    /// <summary>
    /// Primary key. The sales rep.  Foreign key to SalesPerson.BusinessEntityID.
    /// </summary>
    public int BusinessEntityId { get; set; }

    /// <summary>
    /// Primary key. Territory identification number. Foreign key to SalesTerritory.SalesTerritoryID.
    /// </summary>
    public int TerritoryId { get; set; }

    /// <summary>
    /// Primary key. Date the sales representive started work in the territory.
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// Date the sales representative left work in the territory.
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual SalesPerson BusinessEntity { get; set; }

    public virtual SalesTerritory Territory { get; set; }
}

[Register(ServiceLifetime.Transient)]
public class SalesTerritoryHistoryRepository : IEntitySetLoader<SalesTerritoryHistory>, IEntitySaver<SalesTerritoryHistory>
{
    private readonly AdventureWorks2019Context _dbContext;

    public SalesTerritoryHistoryRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<SalesTerritoryHistory>
    public async Task<IReadOnlyList<SalesTerritoryHistory>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<SalesTerritoryHistory>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<SalesTerritoryHistory>

    #region IEntitySaver<SalesTerritoryHistory>
    public async Task SaveAsync(SalesTerritoryHistory entity, CancellationToken ct)
    {
        _dbContext.Set<SalesTerritoryHistory>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<SalesTerritoryHistory>
}

