// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Cross-reference table mapping sales orders to sales reason codes.
/// </summary>
public partial class SalesOrderHeaderSalesReason
{
    /// <summary>
    /// Primary key. Foreign key to SalesOrderHeader.SalesOrderID.
    /// </summary>
    public int SalesOrderId { get; set; }

    /// <summary>
    /// Primary key. Foreign key to SalesReason.SalesReasonID.
    /// </summary>
    public int SalesReasonId { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual SalesOrderHeader SalesOrder { get; set; }

    public virtual SalesReason SalesReason { get; set; }
}

[Register(typeof(IEntitySetLoader<MILL09.Models.SalesOrderHeaderSalesReason>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.SalesOrderHeaderSalesReason>), ServiceLifetime.Transient)]
public class SalesOrderHeaderSalesReasonRepository : IEntitySetLoader<MILL09.Models.SalesOrderHeaderSalesReason>, IEntitySaver<MILL09.Models.SalesOrderHeaderSalesReason>
{
    private readonly AdventureWorks2019Context _dbContext;

    public SalesOrderHeaderSalesReasonRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.SalesOrderHeaderSalesReason>
    public async Task<IReadOnlyList<MILL09.Models.SalesOrderHeaderSalesReason>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<SalesOrderHeaderSalesReason>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.SalesOrderHeaderSalesReason
        {
            SalesOrderId = db.SalesOrderId,
            SalesReasonId = db.SalesReasonId,
            ModifiedDate = db.ModifiedDate,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.SalesOrderHeaderSalesReason>

    #region IEntitySaver<MILL09.Models.SalesOrderHeaderSalesReason>
    public Task SaveAsync(MILL09.Models.SalesOrderHeaderSalesReason entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.SalesOrderHeaderSalesReason>
}
