// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Sales representative current information.
/// </summary>
public partial class SalesPerson
{    /// <summary>
    /// Primary key for SalesPerson records. Foreign key to Employee.BusinessEntityID
    /// </summary>
    public int BusinessEntityId { get; set; }

    /// <summary>
    /// Territory currently assigned to. Foreign key to SalesTerritory.SalesTerritoryID.
    /// </summary>
    public int? TerritoryId { get; set; }

    /// <summary>
    /// Projected yearly sales.
    /// </summary>
    public decimal? SalesQuota { get; set; }

    /// <summary>
    /// Bonus due if quota is met.
    /// </summary>
    public decimal Bonus { get; set; }

    /// <summary>
    /// Commision percent received per sale.
    /// </summary>
    public decimal CommissionPct { get; set; }

    /// <summary>
    /// Sales total year to date.
    /// </summary>
    public decimal SalesYtd { get; set; }

    /// <summary>
    /// Sales total of previous year.
    /// </summary>
    public decimal SalesLastYear { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Employee BusinessEntity { get; set; }

    public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; } = new List<SalesOrderHeader>();

    public virtual ICollection<SalesPersonQuotaHistory> SalesPersonQuotaHistories { get; set; } = new List<SalesPersonQuotaHistory>();

    public virtual ICollection<SalesTerritoryHistory> SalesTerritoryHistories { get; set; } = new List<SalesTerritoryHistory>();

    public virtual ICollection<Store> Stores { get; set; } = new List<Store>();

    public virtual SalesTerritory Territory { get; set; }
}

[Register(ServiceLifetime.Transient)]
public class SalesPersonRepository : IEntitySetLoader<SalesPerson>, IEntitySaver<SalesPerson>
{
    private readonly AdventureWorks2019Context _dbContext;

    public SalesPersonRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<SalesPerson>
    public async Task<IReadOnlyList<SalesPerson>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<SalesPerson>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<SalesPerson>

    #region IEntitySaver<SalesPerson>
    public async Task SaveAsync(SalesPerson entity, CancellationToken ct)
    {
        _dbContext.Set<SalesPerson>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<SalesPerson>
}

