// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Sales territory lookup table.
/// </summary>
public partial class SalesTerritory
{
    public static string SqlSchema => "Sales";
    public static string SqlTableName => "SalesTerritory";

    /// <summary>
    /// Primary key for SalesTerritory records.
    /// </summary>
    public int TerritoryId { get; set; }

    /// <summary>
    /// Sales territory description
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// ISO standard country or region code. Foreign key to CountryRegion.CountryRegionCode. 
    /// </summary>
    public string CountryRegionCode { get; set; }

    /// <summary>
    /// Geographic area to which the sales territory belong.
    /// </summary>
    public string Group { get; set; }

    /// <summary>
    /// Sales in the territory year to date.
    /// </summary>
    public decimal SalesYtd { get; set; }

    /// <summary>
    /// Sales in the territory the previous year.
    /// </summary>
    public decimal SalesLastYear { get; set; }

    /// <summary>
    /// Business costs in the territory year to date.
    /// </summary>
    public decimal CostYtd { get; set; }

    /// <summary>
    /// Business costs in the territory the previous year.
    /// </summary>
    public decimal CostLastYear { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual CountryRegion CountryRegionCodeNavigation { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; } = new List<SalesOrderHeader>();

    public virtual ICollection<SalesPerson> SalesPeople { get; set; } = new List<SalesPerson>();

    public virtual ICollection<SalesTerritoryHistory> SalesTerritoryHistories { get; set; } = new List<SalesTerritoryHistory>();

    public virtual ICollection<StateProvince> StateProvinces { get; set; } = new List<StateProvince>();
}

[Register(typeof(IEntitySetLoader<MILL09.Models.SalesTerritory>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.SalesTerritory>), ServiceLifetime.Transient)]
public class SalesTerritoryRepository : IEntitySetLoader<MILL09.Models.SalesTerritory>, IEntitySaver<MILL09.Models.SalesTerritory>
{
    private readonly AdventureWorks2019Context _dbContext;

    public SalesTerritoryRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.SalesTerritory>
    public async Task<IReadOnlyList<MILL09.Models.SalesTerritory>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<SalesTerritory>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.SalesTerritory
        {
            TerritoryId = db.TerritoryId,
            CostLastYear = db.CostLastYear,
            CostYtd = db.CostYtd,
            CountryRegionCode = db.CountryRegionCode,
            Group = db.Group,
            ModifiedDate = db.ModifiedDate,
            Name = db.Name,
            Rowguid = db.Rowguid,
            SalesLastYear = db.SalesLastYear,
            SalesYtd = db.SalesYtd,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.SalesTerritory>

    #region IEntitySaver<MILL09.Models.SalesTerritory>
    public Task SaveAsync(MILL09.Models.SalesTerritory entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.SalesTerritory>
}
