// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Lookup table of customer purchase reasons.
/// </summary>
public partial class SalesReason
{    /// <summary>
    /// Primary key for SalesReason records.
    /// </summary>
    public int SalesReasonId { get; set; }

    /// <summary>
    /// Sales reason description.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Category the sales reason belongs to.
    /// </summary>
    public string ReasonType { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<SalesOrderHeaderSalesReason> SalesOrderHeaderSalesReasons { get; set; } = new List<SalesOrderHeaderSalesReason>();
}

[Register(ServiceLifetime.Transient)]
public class SalesReasonRepository : IEntitySetLoader<SalesReason>, IEntitySaver<SalesReason>
{
    private readonly AdventureWorks2019Context _dbContext;

    public SalesReasonRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<SalesReason>
    public async Task<IReadOnlyList<SalesReason>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<SalesReason>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<SalesReason>

    #region IEntitySaver<SalesReason>
    public async Task SaveAsync(SalesReason entity, CancellationToken ct)
    {
        _dbContext.Set<SalesReason>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<SalesReason>
}

