// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Sales performance tracking.
/// </summary>
public partial class SalesPersonQuotaHistory
{    /// <summary>
    /// Sales person identification number. Foreign key to SalesPerson.BusinessEntityID.
    /// </summary>
    public int BusinessEntityId { get; set; }

    /// <summary>
    /// Sales quota date.
    /// </summary>
    public DateTime QuotaDate { get; set; }

    /// <summary>
    /// Sales quota amount.
    /// </summary>
    public decimal SalesQuota { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual SalesPerson BusinessEntity { get; set; }
}

[Register(ServiceLifetime.Transient)]
public class SalesPersonQuotaHistoryRepository : IEntitySetLoader<SalesPersonQuotaHistory>, IEntitySaver<SalesPersonQuotaHistory>
{
    private readonly AdventureWorks2019Context _dbContext;

    public SalesPersonQuotaHistoryRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<SalesPersonQuotaHistory>
    public async Task<IReadOnlyList<SalesPersonQuotaHistory>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<SalesPersonQuotaHistory>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<SalesPersonQuotaHistory>

    #region IEntitySaver<SalesPersonQuotaHistory>
    public async Task SaveAsync(SalesPersonQuotaHistory entity, CancellationToken ct)
    {
        _dbContext.Set<SalesPersonQuotaHistory>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<SalesPersonQuotaHistory>
}

