// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Manufacturing failure reasons lookup table.
/// </summary>
public partial class ScrapReason
{
    /// <summary>
    /// Primary key for ScrapReason records.
    /// </summary>
    public short ScrapReasonId { get; set; }

    /// <summary>
    /// Failure description.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<WorkOrder> WorkOrders { get; set; } = new List<WorkOrder>();
}

[Register(typeof(IEntitySetLoader<MILL09.Models.ScrapReason>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.ScrapReason>), ServiceLifetime.Transient)]
public class ScrapReasonRepository : IEntitySetLoader<MILL09.Models.ScrapReason>, IEntitySaver<MILL09.Models.ScrapReason>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ScrapReasonRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.ScrapReason>
    public async Task<IReadOnlyList<MILL09.Models.ScrapReason>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<ScrapReason>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.ScrapReason
        {
            ScrapReasonId = db.ScrapReasonId,
            ModifiedDate = db.ModifiedDate,
            Name = db.Name,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.ScrapReason>

    #region IEntitySaver<MILL09.Models.ScrapReason>
    public Task SaveAsync(MILL09.Models.ScrapReason entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.ScrapReason>
}
