// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Shipping company lookup table.
/// </summary>
public partial class ShipMethod
{    /// <summary>
    /// Primary key for ShipMethod records.
    /// </summary>
    public int ShipMethodId { get; set; }

    /// <summary>
    /// Shipping company name.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Minimum shipping charge.
    /// </summary>
    public decimal ShipBase { get; set; }

    /// <summary>
    /// Shipping charge per pound.
    /// </summary>
    public decimal ShipRate { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; } = new List<PurchaseOrderHeader>();

    public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; } = new List<SalesOrderHeader>();
}

[Register(ServiceLifetime.Transient)]
public class ShipMethodRepository : IEntitySetLoader<ShipMethod>, IEntitySaver<ShipMethod>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ShipMethodRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<ShipMethod>
    public async Task<IReadOnlyList<ShipMethod>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<ShipMethod>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<ShipMethod>

    #region IEntitySaver<ShipMethod>
    public async Task SaveAsync(ShipMethod entity, CancellationToken ct)
    {
        _dbContext.Set<ShipMethod>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<ShipMethod>
}

