// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Contains online customer orders until the order is submitted or cancelled.
/// </summary>
public partial class ShoppingCartItem
{    /// <summary>
    /// Primary key for ShoppingCartItem records.
    /// </summary>
    public int ShoppingCartItemId { get; set; }

    /// <summary>
    /// Shopping cart identification number.
    /// </summary>
    public string ShoppingCartId { get; set; }

    /// <summary>
    /// Product quantity ordered.
    /// </summary>
    public int Quantity { get; set; }

    /// <summary>
    /// Product ordered. Foreign key to Product.ProductID.
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// Date the time the record was created.
    /// </summary>
    public DateTime DateCreated { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
}

[Register(ServiceLifetime.Transient)]
public class ShoppingCartItemRepository : IEntitySetLoader<ShoppingCartItem>, IEntitySaver<ShoppingCartItem>
{
    private readonly AdventureWorks2019Context _dbContext;

    public ShoppingCartItemRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<ShoppingCartItem>
    public async Task<IReadOnlyList<ShoppingCartItem>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<ShoppingCartItem>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<ShoppingCartItem>

    #region IEntitySaver<ShoppingCartItem>
    public async Task SaveAsync(ShoppingCartItem entity, CancellationToken ct)
    {
        _dbContext.Set<ShoppingCartItem>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<ShoppingCartItem>
}

