// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Cross-reference table mapping products to special offer discounts.
/// </summary>
public partial class SpecialOfferProduct
{    /// <summary>
    /// Primary key for SpecialOfferProduct records.
    /// </summary>
    public int SpecialOfferId { get; set; }

    /// <summary>
    /// Product identification number. Foreign key to Product.ProductID.
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; } = new List<SalesOrderDetail>();

    public virtual SpecialOffer SpecialOffer { get; set; }
}

[Register(ServiceLifetime.Transient)]
public class SpecialOfferProductRepository : IEntitySetLoader<SpecialOfferProduct>, IEntitySaver<SpecialOfferProduct>
{
    private readonly AdventureWorks2019Context _dbContext;

    public SpecialOfferProductRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<SpecialOfferProduct>
    public async Task<IReadOnlyList<SpecialOfferProduct>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<SpecialOfferProduct>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<SpecialOfferProduct>

    #region IEntitySaver<SpecialOfferProduct>
    public async Task SaveAsync(SpecialOfferProduct entity, CancellationToken ct)
    {
        _dbContext.Set<SpecialOfferProduct>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<SpecialOfferProduct>
}

