// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Cross-reference table mapping products to special offer discounts.
/// </summary>
public partial class SpecialOfferProduct
{
    /// <summary>
    /// Primary key for SpecialOfferProduct records.
    /// </summary>
    public int SpecialOfferId { get; set; }

    /// <summary>
    /// Product identification number. Foreign key to Product.ProductID.
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; } = new List<SalesOrderDetail>();

    public virtual SpecialOffer SpecialOffer { get; set; }
}

[Register(typeof(IEntitySetLoader<MILL09.Models.SpecialOfferProduct>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.SpecialOfferProduct>), ServiceLifetime.Transient)]
public class SpecialOfferProductRepository : IEntitySetLoader<MILL09.Models.SpecialOfferProduct>, IEntitySaver<MILL09.Models.SpecialOfferProduct>
{
    private readonly AdventureWorks2019Context _dbContext;

    public SpecialOfferProductRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.SpecialOfferProduct>
    public async Task<IReadOnlyList<MILL09.Models.SpecialOfferProduct>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<SpecialOfferProduct>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.SpecialOfferProduct
        {
            SpecialOfferId = db.SpecialOfferId,
            ProductId = db.ProductId,
            ModifiedDate = db.ModifiedDate,
            Rowguid = db.Rowguid,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.SpecialOfferProduct>

    #region IEntitySaver<MILL09.Models.SpecialOfferProduct>
    public Task SaveAsync(MILL09.Models.SpecialOfferProduct entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.SpecialOfferProduct>
}
