// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Sale discounts lookup table.
/// </summary>
public partial class SpecialOffer
{
    /// <summary>
    /// Primary key for SpecialOffer records.
    /// </summary>
    public int SpecialOfferId { get; set; }

    /// <summary>
    /// Discount description.
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Discount precentage.
    /// </summary>
    public decimal DiscountPct { get; set; }

    /// <summary>
    /// Discount type category.
    /// </summary>
    public string Type { get; set; }

    /// <summary>
    /// Group the discount applies to such as Reseller or Customer.
    /// </summary>
    public string Category { get; set; }

    /// <summary>
    /// Discount start date.
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// Discount end date.
    /// </summary>
    public DateTime EndDate { get; set; }

    /// <summary>
    /// Minimum discount percent allowed.
    /// </summary>
    public int MinQty { get; set; }

    /// <summary>
    /// Maximum discount percent allowed.
    /// </summary>
    public int? MaxQty { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<SpecialOfferProduct> SpecialOfferProducts { get; set; } = new List<SpecialOfferProduct>();
}

[Register(typeof(IEntitySetLoader<MILL09.Models.SpecialOffer>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.SpecialOffer>), ServiceLifetime.Transient)]
public class SpecialOfferRepository : IEntitySetLoader<MILL09.Models.SpecialOffer>, IEntitySaver<MILL09.Models.SpecialOffer>
{
    private readonly AdventureWorks2019Context _dbContext;

    public SpecialOfferRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.SpecialOffer>
    public async Task<IReadOnlyList<MILL09.Models.SpecialOffer>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<SpecialOffer>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.SpecialOffer
        {
            SpecialOfferId = db.SpecialOfferId,
            Category = db.Category,
            Description = db.Description,
            DiscountPct = db.DiscountPct,
            EndDate = db.EndDate,
            MaxQty = db.MaxQty,
            MinQty = db.MinQty,
            ModifiedDate = db.ModifiedDate,
            Rowguid = db.Rowguid,
            StartDate = db.StartDate,
            Type = db.Type,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.SpecialOffer>

    #region IEntitySaver<MILL09.Models.SpecialOffer>
    public Task SaveAsync(MILL09.Models.SpecialOffer entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.SpecialOffer>
}
