// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Record of each purchase order, sales order, or work order transaction year to date.
/// </summary>
public partial class TransactionHistory
{
    /// <summary>
    /// Primary key for TransactionHistory records.
    /// </summary>
    public int TransactionId { get; set; }

    /// <summary>
    /// Product identification number. Foreign key to Product.ProductID.
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// Purchase order, sales order, or work order identification number.
    /// </summary>
    public int ReferenceOrderId { get; set; }

    /// <summary>
    /// Line number associated with the purchase order, sales order, or work order.
    /// </summary>
    public int ReferenceOrderLineId { get; set; }

    /// <summary>
    /// Date and time of the transaction.
    /// </summary>
    public DateTime TransactionDate { get; set; }

    /// <summary>
    /// W = WorkOrder, S = SalesOrder, P = PurchaseOrder
    /// </summary>
    public string TransactionType { get; set; }

    /// <summary>
    /// Product quantity.
    /// </summary>
    public int Quantity { get; set; }

    /// <summary>
    /// Product cost.
    /// </summary>
    public decimal ActualCost { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
}

[Register(typeof(IEntitySetLoader<MILL09.Models.TransactionHistory>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.TransactionHistory>), ServiceLifetime.Transient)]
public class TransactionHistoryRepository : IEntitySetLoader<MILL09.Models.TransactionHistory>, IEntitySaver<MILL09.Models.TransactionHistory>
{
    private readonly AdventureWorks2019Context _dbContext;

    public TransactionHistoryRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.TransactionHistory>
    public async Task<IReadOnlyList<MILL09.Models.TransactionHistory>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<TransactionHistory>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.TransactionHistory
        {
            TransactionId = db.TransactionId,
            ActualCost = db.ActualCost,
            ModifiedDate = db.ModifiedDate,
            ProductId = db.ProductId,
            Quantity = db.Quantity,
            ReferenceOrderId = db.ReferenceOrderId,
            ReferenceOrderLineId = db.ReferenceOrderLineId,
            TransactionDate = db.TransactionDate,
            TransactionType = db.TransactionType,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.TransactionHistory>

    #region IEntitySaver<MILL09.Models.TransactionHistory>
    public Task SaveAsync(MILL09.Models.TransactionHistory entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.TransactionHistory>
}
