// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Unit of measure lookup table.
/// </summary>
public partial class UnitMeasure
{    /// <summary>
    /// Primary key.
    /// </summary>
    public string UnitMeasureCode { get; set; }

    /// <summary>
    /// Unit of measure description.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<BillOfMaterial> BillOfMaterials { get; set; } = new List<BillOfMaterial>();

    public virtual ICollection<Product> ProductSizeUnitMeasureCodeNavigations { get; set; } = new List<Product>();

    public virtual ICollection<ProductVendor> ProductVendors { get; set; } = new List<ProductVendor>();

    public virtual ICollection<Product> ProductWeightUnitMeasureCodeNavigations { get; set; } = new List<Product>();
}

[Register(ServiceLifetime.Transient)]
public class UnitMeasureRepository : IEntitySetLoader<UnitMeasure>, IEntitySaver<UnitMeasure>
{
    private readonly AdventureWorks2019Context _dbContext;

    public UnitMeasureRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<UnitMeasure>
    public async Task<IReadOnlyList<UnitMeasure>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<UnitMeasure>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<UnitMeasure>

    #region IEntitySaver<UnitMeasure>
    public async Task SaveAsync(UnitMeasure entity, CancellationToken ct)
    {
        _dbContext.Set<UnitMeasure>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<UnitMeasure>
}

