// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;

/// <summary>
/// Unit of measure lookup table.
/// </summary>
public partial class UnitMeasure
{
    /// <summary>
    /// Primary key.
    /// </summary>
    public string UnitMeasureCode { get; set; }

    /// <summary>
    /// Unit of measure description.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<BillOfMaterial> BillOfMaterials { get; set; } = new List<BillOfMaterial>();

    public virtual ICollection<Product> ProductSizeUnitMeasureCodeNavigations { get; set; } = new List<Product>();

    public virtual ICollection<ProductVendor> ProductVendors { get; set; } = new List<ProductVendor>();

    public virtual ICollection<Product> ProductWeightUnitMeasureCodeNavigations { get; set; } = new List<Product>();
}

[Register(typeof(IEntitySetLoader<MILL09.Models.UnitMeasure>), ServiceLifetime.Transient)]
[Register(typeof(IEntitySaver<MILL09.Models.UnitMeasure>), ServiceLifetime.Transient)]
public class UnitMeasureRepository : IEntitySetLoader<MILL09.Models.UnitMeasure>, IEntitySaver<MILL09.Models.UnitMeasure>
{
    private readonly AdventureWorks2019Context _dbContext;

    public UnitMeasureRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<MILL09.Models.UnitMeasure>
    public async Task<IReadOnlyList<MILL09.Models.UnitMeasure>> LoadAllAsync(CancellationToken ct)
    {
        var dbEntities = await _dbContext.Set<UnitMeasure>()
            .AsNoTracking()
            .ToListAsync(ct);

        var uiEntities = dbEntities.Select(db => new MILL09.Models.UnitMeasure
        {
            UnitMeasureCode = db.UnitMeasureCode,
            ModifiedDate = db.ModifiedDate,
            Name = db.Name,
        }).ToList();

        return uiEntities;
    }
    #endregion IEntitySetLoader<MILL09.Models.UnitMeasure>

    #region IEntitySaver<MILL09.Models.UnitMeasure>
    public Task SaveAsync(MILL09.Models.UnitMeasure entity, CancellationToken ct)
    {
        // Stubbed until write operations are implemented
        throw new NotImplementedException();
    }
    #endregion IEntitySaver<MILL09.Models.UnitMeasure>
}
