// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Companies from whom Adventure Works Cycles purchases parts or other goods.
/// </summary>
public partial class Vendor
{    /// <summary>
    /// Primary key for Vendor records.  Foreign key to BusinessEntity.BusinessEntityID
    /// </summary>
    public int BusinessEntityId { get; set; }

    /// <summary>
    /// Vendor account (identification) number.
    /// </summary>
    public string AccountNumber { get; set; }

    /// <summary>
    /// Company name.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 1 = Superior, 2 = Excellent, 3 = Above average, 4 = Average, 5 = Below average
    /// </summary>
    public byte CreditRating { get; set; }

    /// <summary>
    /// 0 = Do not use if another vendor is available. 1 = Preferred over other vendors supplying the same product.
    /// </summary>
    public bool PreferredVendorStatus { get; set; }

    /// <summary>
    /// 0 = Vendor no longer used. 1 = Vendor is actively used.
    /// </summary>
    public bool ActiveFlag { get; set; }

    /// <summary>
    /// Vendor URL.
    /// </summary>
    public string PurchasingWebServiceUrl { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual BusinessEntity BusinessEntity { get; set; }

    public virtual ICollection<ProductVendor> ProductVendors { get; set; } = new List<ProductVendor>();

    public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; } = new List<PurchaseOrderHeader>();
}

[Register(ServiceLifetime.Transient)]
public class VendorRepository : IEntitySetLoader<Vendor>, IEntitySaver<Vendor>
{
    private readonly AdventureWorks2019Context _dbContext;

    public VendorRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<Vendor>
    public async Task<IReadOnlyList<Vendor>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<Vendor>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<Vendor>

    #region IEntitySaver<Vendor>
    public async Task SaveAsync(Vendor entity, CancellationToken ct)
    {
        _dbContext.Set<Vendor>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<Vendor>
}

