// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MILL06.Data.Entities.Entities;
/// <summary>
/// Manufacturing work orders.
/// </summary>
public partial class WorkOrder
{    /// <summary>
    /// Primary key for WorkOrder records.
    /// </summary>
    public int WorkOrderId { get; set; }

    /// <summary>
    /// Product identification number. Foreign key to Product.ProductID.
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// Product quantity to build.
    /// </summary>
    public int OrderQty { get; set; }

    /// <summary>
    /// Quantity built and put in inventory.
    /// </summary>
    public int StockedQty { get; set; }

    /// <summary>
    /// Quantity that failed inspection.
    /// </summary>
    public short ScrappedQty { get; set; }

    /// <summary>
    /// Work order start date.
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// Work order end date.
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// Work order due date.
    /// </summary>
    public DateTime DueDate { get; set; }

    /// <summary>
    /// Reason for inspection failure.
    /// </summary>
    public short? ScrapReasonId { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }

    public virtual ScrapReason ScrapReason { get; set; }

    public virtual ICollection<WorkOrderRouting> WorkOrderRoutings { get; set; } = new List<WorkOrderRouting>();
}

[Register(ServiceLifetime.Transient)]
public class WorkOrderRepository : IEntitySetLoader<WorkOrder>, IEntitySaver<WorkOrder>
{
    private readonly AdventureWorks2019Context _dbContext;

    public WorkOrderRepository(AdventureWorks2019Context dbContext)
    {
        _dbContext = dbContext;
    }

    #region IEntitySetLoader<WorkOrder>
    public async Task<IReadOnlyList<WorkOrder>> LoadAllAsync(CancellationToken ct)
    {
        return await _dbContext.Set<WorkOrder>()
            .AsNoTracking()
            .ToListAsync(ct);
    }
    #endregion IEntitySetLoader<WorkOrder>

    #region IEntitySaver<WorkOrder>
    public async Task SaveAsync(WorkOrder entity, CancellationToken ct)
    {
        _dbContext.Set<WorkOrder>().Update(entity);
        await _dbContext.SaveChangesAsync(ct);
    }
    #endregion IEntitySaver<WorkOrder>
}

