// <auto-generated>
//     Generated by the ModelsProject template. Do not edit — regenerated on every run.
//     A live filtered projection over an ObservableCollection.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;

namespace MILL80.Infrastructure.Services;

public sealed class LiveFilteredCollection<T> : ObservableCollection<T>, IDisposable where T : INotifyPropertyChanged {

    private readonly ObservableCollection<T> _source;
    private readonly Func<T, bool> _filter;
    private readonly HashSet<string> _watchedProperties;
    private bool _disposed;

    public LiveFilteredCollection(ObservableCollection<T> source, Func<T, bool> filter, params string[] watchedProperties) {
        _source = source;
        _filter = filter;
        _watchedProperties = new HashSet<string>(watchedProperties, StringComparer.Ordinal);

        foreach (var item in _source) {
            item.PropertyChanged += OnSourceItemPropertyChanged;
            if (_filter(item)) Add(item);
        }
        _source.CollectionChanged += OnSourceCollectionChanged;
    }

    private void OnSourceCollectionChanged(object sender, NotifyCollectionChangedEventArgs e) {
        if (e.NewItems != null) {
            foreach (T item in e.NewItems) {
                item.PropertyChanged += OnSourceItemPropertyChanged;
                if (_filter(item) && !Contains(item)) Add(item);
            }
        }
        if (e.OldItems != null) {
            foreach (T item in e.OldItems) {
                item.PropertyChanged -= OnSourceItemPropertyChanged;
                if (Contains(item)) Remove(item);
            }
        }
    }

    private void OnSourceItemPropertyChanged(object sender, PropertyChangedEventArgs e) {
        if (sender is not T item) return;
        if (e.PropertyName != null && !_watchedProperties.Contains(e.PropertyName)) return;

        bool matches = _filter(item);
        bool currentlyIncluded = Contains(item);
        if (matches && !currentlyIncluded) Add(item);
        else if (!matches && currentlyIncluded) Remove(item);
    }

    public void Dispose() {
        if (_disposed) return;
        _disposed = true;

        _source.CollectionChanged -= OnSourceCollectionChanged;
        foreach (var item in _source) item.PropertyChanged -= OnSourceItemPropertyChanged;
    }
}
