// <auto-generated>
//     Generated by the ModelsProject template. Do not edit — regenerated on every run.
//     The load/save contract the generated entities resolve through.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

namespace MILL09.Models.Interfaces;

public interface IEntitySetLoader<T> {
    Task<IReadOnlyList<T>> LoadAllAsync(CancellationToken ct);
}

public interface IEntitySaver<T> {
    Task SaveAsync(T entity, CancellationToken ct);
}
