// <auto-generated>
//     Generated from Address.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class Address : ModelEntityBase
{
    [ObservableProperty]
    private int _addressId;

    [ObservableProperty]
    private string _addressLine1 = null!;

    [ObservableProperty]
    private string _addressLine2 = null!;

    [ObservableProperty]
    private string _city = null!;

    [ObservableProperty]
    private int _stateProvinceId;

    [ObservableProperty]
    private string _postalCode = null!;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public StateProvince? StateProvince => MainModel.Instance.StateProvinces.FirstOrDefault(x => x.StateProvinceId == this.StateProvinceId);

    private ObservableCollection<BusinessEntityAddress>? _businessEntityAddresses;
    public ObservableCollection<BusinessEntityAddress> BusinessEntityAddresses
    {
        get { if (_businessEntityAddresses == null) BusinessEntityAddresses = new LiveFilteredCollection<BusinessEntityAddress>(MainModel.Instance.BusinessEntityAddresses, x => x.AddressId == this.AddressId, nameof(BusinessEntityAddress.AddressId)); return _businessEntityAddresses!; }
        private set => SetProperty(ref _businessEntityAddresses, value);
    }

    private ObservableCollection<SalesOrderHeader>? _salesOrderHeaderBillToAddresses;
    public ObservableCollection<SalesOrderHeader> SalesOrderHeaderBillToAddresses
    {
        // TODO: could not auto-detect the foreign key linking SalesOrderHeader back to Address.
        // Example: new LiveFilteredCollection<SalesOrderHeader>(MainModel.Instance.SalesOrderHeaders, x => /* match condition */, nameof(SalesOrderHeader.SomeProperty))
        get { if (_salesOrderHeaderBillToAddresses == null) SalesOrderHeaderBillToAddresses = new ObservableCollection<SalesOrderHeader>(); return _salesOrderHeaderBillToAddresses!; }
        private set => SetProperty(ref _salesOrderHeaderBillToAddresses, value);
    }

    private ObservableCollection<SalesOrderHeader>? _salesOrderHeaderShipToAddresses;
    public ObservableCollection<SalesOrderHeader> SalesOrderHeaderShipToAddresses
    {
        // TODO: could not auto-detect the foreign key linking SalesOrderHeader back to Address.
        // Example: new LiveFilteredCollection<SalesOrderHeader>(MainModel.Instance.SalesOrderHeaders, x => /* match condition */, nameof(SalesOrderHeader.SomeProperty))
        get { if (_salesOrderHeaderShipToAddresses == null) SalesOrderHeaderShipToAddresses = new ObservableCollection<SalesOrderHeader>(); return _salesOrderHeaderShipToAddresses!; }
        private set => SetProperty(ref _salesOrderHeaderShipToAddresses, value);
    }

    public static bool IsAddressesLoaded => MainModel.Instance.IsAddressesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsAddressesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<Address>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.AddressId).ToHashSet();
        var collection = MainModel.Instance.Addresses;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.AddressId, freshItem.AddressId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].AddressId)) collection.RemoveAt(i);
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadAddressesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(Address fresh)
    {
        AddressId = fresh.AddressId;
        AddressLine1 = fresh.AddressLine1;
        AddressLine2 = fresh.AddressLine2;
        City = fresh.City;
        StateProvinceId = fresh.StateProvinceId;
        PostalCode = fresh.PostalCode;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<Address>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<Address>? _addresses;
    public ObservableCollection<Address> Addresses
    {
        get { if (_addresses == null) Addresses = new ObservableCollection<Address>(); return _addresses!; }
        private set
        {
            SetProperty(ref _addresses, value);
            OnPropertyChanged(nameof(IsAddressesLoaded));
        }
    }

    public bool IsAddressesLoaded => _addresses != null;

    internal void UnloadAddressesStorage()
    {
        if (_addresses == null) return;
        _addresses = null;
        OnPropertyChanged(nameof(Addresses));
        OnPropertyChanged(nameof(IsAddressesLoaded));
    }
}
}
