// <auto-generated>
//     Generated from AddressType.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class AddressType : ModelEntityBase
{
    [ObservableProperty]
    private int _addressTypeId;

    [ObservableProperty]
    private string _name = null!;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    private ObservableCollection<BusinessEntityAddress>? _businessEntityAddresses;
    public ObservableCollection<BusinessEntityAddress> BusinessEntityAddresses
    {
        get { if (_businessEntityAddresses == null) BusinessEntityAddresses = new LiveFilteredCollection<BusinessEntityAddress>(MainModel.Instance.BusinessEntityAddresses, x => x.AddressTypeId == this.AddressTypeId, nameof(BusinessEntityAddress.AddressTypeId)); return _businessEntityAddresses!; }
        private set => SetProperty(ref _businessEntityAddresses, value);
    }

    public static bool IsAddressTypesLoaded => MainModel.Instance.IsAddressTypesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsAddressTypesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<AddressType>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<AddressType>)MainModel.Instance.AddressTypes).ReplaceRange(fresh);

        MainModel.Instance.IsAddressTypesLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadAddressTypesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(AddressType fresh)
    {
        AddressTypeId = fresh.AddressTypeId;
        Name = fresh.Name;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<AddressType>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<AddressType>? _addressTypes;
    public ObservableRangeCollection<AddressType> AddressTypes
    {
        get { if (_addressTypes == null) AddressTypes = new ObservableRangeCollection<AddressType>(); return _addressTypes!; }
        private set => SetProperty(ref _addressTypes, value);
    }

    private bool _isAddressTypesLoaded;
    public bool IsAddressTypesLoaded
    {
        get => _isAddressTypesLoaded;
        internal set => SetProperty(ref _isAddressTypesLoaded, value);
    }

    internal void UnloadAddressTypesStorage()
    {
        if (_addressTypes == null) return;
        _addressTypes = null;
        OnPropertyChanged(nameof(AddressTypes));

        IsAddressTypesLoaded = false;
    }
}
}
