// <auto-generated>
//     Generated from BillOfMaterial.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class BillOfMaterial : ModelEntityBase
{
    [ObservableProperty]
    private int _billOfMaterialsId;

    [ObservableProperty]
    private int? _productAssemblyId;

    [ObservableProperty]
    private int _componentId;

    [ObservableProperty]
    private DateTime _startDate;

    [ObservableProperty]
    private DateTime? _endDate;

    [ObservableProperty]
    private string _unitMeasureCode = null!;

    [ObservableProperty]
    private short _bomlevel;

    [ObservableProperty]
    private decimal _perAssemblyQty;

    [ObservableProperty]
    private DateTime _modifiedDate;

    // TODO: could not auto-detect the foreign key for 'Component' -> Product.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Product? Component => MainModel.Instance.Products.FirstOrDefault(x => /* match condition */);

    // TODO: could not auto-detect the foreign key for 'ProductAssembly' -> Product.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Product? ProductAssembly => MainModel.Instance.Products.FirstOrDefault(x => /* match condition */);

    public UnitMeasure? UnitMeasureCodeNavigation => MainModel.Instance.UnitMeasures.FirstOrDefault(x => x.UnitMeasureCode == this.UnitMeasureCode);

    public static bool IsBillOfMaterialsLoaded => MainModel.Instance.IsBillOfMaterialsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsBillOfMaterialsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<BillOfMaterial>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.BillOfMaterialsId).ToHashSet();
        var collection = MainModel.Instance.BillOfMaterials;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.BillOfMaterialsId, freshItem.BillOfMaterialsId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].BillOfMaterialsId)) collection.RemoveAt(i);
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadBillOfMaterialsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(BillOfMaterial fresh)
    {
        BillOfMaterialsId = fresh.BillOfMaterialsId;
        ProductAssemblyId = fresh.ProductAssemblyId;
        ComponentId = fresh.ComponentId;
        StartDate = fresh.StartDate;
        EndDate = fresh.EndDate;
        UnitMeasureCode = fresh.UnitMeasureCode;
        Bomlevel = fresh.Bomlevel;
        PerAssemblyQty = fresh.PerAssemblyQty;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<BillOfMaterial>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<BillOfMaterial>? _billOfMaterials;
    public ObservableCollection<BillOfMaterial> BillOfMaterials
    {
        get { if (_billOfMaterials == null) BillOfMaterials = new ObservableCollection<BillOfMaterial>(); return _billOfMaterials!; }
        private set
        {
            SetProperty(ref _billOfMaterials, value);
            OnPropertyChanged(nameof(IsBillOfMaterialsLoaded));
        }
    }

    public bool IsBillOfMaterialsLoaded => _billOfMaterials != null;

    internal void UnloadBillOfMaterialsStorage()
    {
        if (_billOfMaterials == null) return;
        _billOfMaterials = null;
        OnPropertyChanged(nameof(BillOfMaterials));
        OnPropertyChanged(nameof(IsBillOfMaterialsLoaded));
    }
}
}
