// <auto-generated>
//     Generated from BusinessEntityContact.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class BusinessEntityContact : ModelEntityBase
{
    public static string SqlSchema => "Person";
    public static string SqlTableName => "BusinessEntityContact";
    [ObservableProperty]
    private int _businessEntityId;

    [ObservableProperty]
    private int _personId;

    [ObservableProperty]
    private int _contactTypeId;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public BusinessEntity? BusinessEntity => MainModel.Instance.BusinessEntities.FirstOrDefault(x => x.BusinessEntityId == this.BusinessEntityId);

    public ContactType? ContactType => MainModel.Instance.ContactTypes.FirstOrDefault(x => x.ContactTypeId == this.ContactTypeId);

    // TODO: could not auto-detect the foreign key for 'Person' -> Person.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Person? Person => MainModel.Instance.Persons.FirstOrDefault(x => /* match condition */);

    public static bool IsBusinessEntityContactsLoaded => MainModel.Instance.IsBusinessEntityContactsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsBusinessEntityContactsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<BusinessEntityContact>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<BusinessEntityContact>)MainModel.Instance.BusinessEntityContacts).ReplaceRange(fresh);

        MainModel.Instance.IsBusinessEntityContactsLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadBusinessEntityContactsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(BusinessEntityContact fresh)
    {
        BusinessEntityId = fresh.BusinessEntityId;
        PersonId = fresh.PersonId;
        ContactTypeId = fresh.ContactTypeId;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<BusinessEntityContact>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<BusinessEntityContact>? _businessEntityContacts;
    public ObservableRangeCollection<BusinessEntityContact> BusinessEntityContacts
    {
        get { if (_businessEntityContacts == null) BusinessEntityContacts = new ObservableRangeCollection<BusinessEntityContact>(); return _businessEntityContacts!; }
        private set => SetProperty(ref _businessEntityContacts, value);
    }

    private bool _isBusinessEntityContactsLoaded;
    public bool IsBusinessEntityContactsLoaded
    {
        get => _isBusinessEntityContactsLoaded;
        internal set => SetProperty(ref _isBusinessEntityContactsLoaded, value);
    }

    internal void UnloadBusinessEntityContactsStorage()
    {
        if (_businessEntityContacts == null) return;
        _businessEntityContacts = null;
        OnPropertyChanged(nameof(BusinessEntityContacts));

        IsBusinessEntityContactsLoaded = false;
    }
}
}
