// <auto-generated>
//     Generated from ContactType.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class ContactType : ModelEntityBase
{
    [ObservableProperty]
    private int _contactTypeId;

    [ObservableProperty]
    private string _name = null!;

    [ObservableProperty]
    private DateTime _modifiedDate;

    private ObservableCollection<BusinessEntityContact>? _businessEntityContacts;
    public ObservableCollection<BusinessEntityContact> BusinessEntityContacts
    {
        get { if (_businessEntityContacts == null) BusinessEntityContacts = new LiveFilteredCollection<BusinessEntityContact>(MainModel.Instance.BusinessEntityContacts, x => x.ContactTypeId == this.ContactTypeId, nameof(BusinessEntityContact.ContactTypeId)); return _businessEntityContacts!; }
        private set => SetProperty(ref _businessEntityContacts, value);
    }

    public static bool IsContactTypesLoaded => MainModel.Instance.IsContactTypesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsContactTypesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<ContactType>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.ContactTypeId).ToHashSet();
        var collection = MainModel.Instance.ContactTypes;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.ContactTypeId, freshItem.ContactTypeId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].ContactTypeId)) collection.RemoveAt(i);
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadContactTypesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(ContactType fresh)
    {
        ContactTypeId = fresh.ContactTypeId;
        Name = fresh.Name;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<ContactType>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<ContactType>? _contactTypes;
    public ObservableCollection<ContactType> ContactTypes
    {
        get { if (_contactTypes == null) ContactTypes = new ObservableCollection<ContactType>(); return _contactTypes!; }
        private set
        {
            SetProperty(ref _contactTypes, value);
            OnPropertyChanged(nameof(IsContactTypesLoaded));
        }
    }

    public bool IsContactTypesLoaded => _contactTypes != null;

    internal void UnloadContactTypesStorage()
    {
        if (_contactTypes == null) return;
        _contactTypes = null;
        OnPropertyChanged(nameof(ContactTypes));
        OnPropertyChanged(nameof(IsContactTypesLoaded));
    }
}
}
