// <auto-generated>
//     Generated from CountryRegionCurrency.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class CountryRegionCurrency : ModelEntityBase
{
    [ObservableProperty]
    private string _countryRegionCode = null!;

    [ObservableProperty]
    private string _currencyCode = null!;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public CountryRegion? CountryRegionCodeNavigation => MainModel.Instance.CountryRegions.FirstOrDefault(x => x.CountryRegionCode == this.CountryRegionCode);

    public Currency? CurrencyCodeNavigation => MainModel.Instance.Currencies.FirstOrDefault(x => x.CurrencyCode == this.CurrencyCode);

    public static bool IsCountryRegionCurrenciesLoaded => MainModel.Instance.IsCountryRegionCurrenciesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsCountryRegionCurrenciesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<CountryRegionCurrency>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<CountryRegionCurrency>)MainModel.Instance.CountryRegionCurrencies).ReplaceRange(fresh);

        MainModel.Instance.IsCountryRegionCurrenciesLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadCountryRegionCurrenciesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(CountryRegionCurrency fresh)
    {
        CountryRegionCode = fresh.CountryRegionCode;
        CurrencyCode = fresh.CurrencyCode;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<CountryRegionCurrency>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<CountryRegionCurrency>? _countryRegionCurrencies;
    public ObservableRangeCollection<CountryRegionCurrency> CountryRegionCurrencies
    {
        get { if (_countryRegionCurrencies == null) CountryRegionCurrencies = new ObservableRangeCollection<CountryRegionCurrency>(); return _countryRegionCurrencies!; }
        private set => SetProperty(ref _countryRegionCurrencies, value);
    }

    private bool _isCountryRegionCurrenciesLoaded;
    public bool IsCountryRegionCurrenciesLoaded
    {
        get => _isCountryRegionCurrenciesLoaded;
        internal set => SetProperty(ref _isCountryRegionCurrenciesLoaded, value);
    }

    internal void UnloadCountryRegionCurrenciesStorage()
    {
        if (_countryRegionCurrencies == null) return;
        _countryRegionCurrencies = null;
        OnPropertyChanged(nameof(CountryRegionCurrencies));

        IsCountryRegionCurrenciesLoaded = false;
    }
}
}
