// <auto-generated>
//     Generated from CountryRegion.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class CountryRegion : ModelEntityBase
{
    [ObservableProperty]
    private string _countryRegionCode = null!;

    [ObservableProperty]
    private string _name = null!;

    [ObservableProperty]
    private DateTime _modifiedDate;

    private ObservableCollection<CountryRegionCurrency>? _countryRegionCurrencies;
    public ObservableCollection<CountryRegionCurrency> CountryRegionCurrencies
    {
        get { if (_countryRegionCurrencies == null) CountryRegionCurrencies = new LiveFilteredCollection<CountryRegionCurrency>(MainModel.Instance.CountryRegionCurrencies, x => x.CountryRegionCode == this.CountryRegionCode, nameof(CountryRegionCurrency.CountryRegionCode)); return _countryRegionCurrencies!; }
        private set => SetProperty(ref _countryRegionCurrencies, value);
    }

    private ObservableCollection<SalesTerritory>? _salesTerritories;
    public ObservableCollection<SalesTerritory> SalesTerritories
    {
        get { if (_salesTerritories == null) SalesTerritories = new LiveFilteredCollection<SalesTerritory>(MainModel.Instance.SalesTerritories, x => x.CountryRegionCode == this.CountryRegionCode, nameof(SalesTerritory.CountryRegionCode)); return _salesTerritories!; }
        private set => SetProperty(ref _salesTerritories, value);
    }

    private ObservableCollection<StateProvince>? _stateProvinces;
    public ObservableCollection<StateProvince> StateProvinces
    {
        get { if (_stateProvinces == null) StateProvinces = new LiveFilteredCollection<StateProvince>(MainModel.Instance.StateProvinces, x => x.CountryRegionCode == this.CountryRegionCode, nameof(StateProvince.CountryRegionCode)); return _stateProvinces!; }
        private set => SetProperty(ref _stateProvinces, value);
    }

    public static bool IsCountryRegionsLoaded => MainModel.Instance.IsCountryRegionsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsCountryRegionsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<CountryRegion>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.CountryRegionCode).ToHashSet();
        var collection = MainModel.Instance.CountryRegions;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.CountryRegionCode, freshItem.CountryRegionCode));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].CountryRegionCode)) collection.RemoveAt(i);

        // Explicitly flag the collection as loaded after a successful database query
        MainModel.Instance.IsCountryRegionsLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadCountryRegionsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(CountryRegion fresh)
    {
        CountryRegionCode = fresh.CountryRegionCode;
        Name = fresh.Name;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<CountryRegion>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<CountryRegion>? _countryRegions;
    public ObservableCollection<CountryRegion> CountryRegions
    {
        get { if (_countryRegions == null) CountryRegions = new ObservableCollection<CountryRegion>(); return _countryRegions!; }
        private set => SetProperty(ref _countryRegions, value);
    }

    private bool _isCountryRegionsLoaded;
    public bool IsCountryRegionsLoaded
    {
        get => _isCountryRegionsLoaded;
        internal set => SetProperty(ref _isCountryRegionsLoaded, value);
    }

    internal void UnloadCountryRegionsStorage()
    {
        if (_countryRegions == null) return;
        _countryRegions = null;
        OnPropertyChanged(nameof(CountryRegions));

        // Reset the load state flag
        IsCountryRegionsLoaded = false;
    }
}
}
