// <auto-generated>
//     Generated from CreditCard.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class CreditCard : ModelEntityBase
{
    [ObservableProperty]
    private int _creditCardId;

    [ObservableProperty]
    private string _cardType = null!;

    [ObservableProperty]
    private string _cardNumber = null!;

    [ObservableProperty]
    private byte _expMonth;

    [ObservableProperty]
    private short _expYear;

    [ObservableProperty]
    private DateTime _modifiedDate;

    private ObservableCollection<PersonCreditCard>? _personCreditCards;
    public ObservableCollection<PersonCreditCard> PersonCreditCards
    {
        get { if (_personCreditCards == null) PersonCreditCards = new LiveFilteredCollection<PersonCreditCard>(MainModel.Instance.PersonCreditCards, x => x.CreditCardId == this.CreditCardId, nameof(PersonCreditCard.CreditCardId)); return _personCreditCards!; }
        private set => SetProperty(ref _personCreditCards, value);
    }

    private ObservableCollection<SalesOrderHeader>? _salesOrderHeaders;
    public ObservableCollection<SalesOrderHeader> SalesOrderHeaders
    {
        get { if (_salesOrderHeaders == null) SalesOrderHeaders = new LiveFilteredCollection<SalesOrderHeader>(MainModel.Instance.SalesOrderHeaders, x => x.CreditCardId == this.CreditCardId, nameof(SalesOrderHeader.CreditCardId)); return _salesOrderHeaders!; }
        private set => SetProperty(ref _salesOrderHeaders, value);
    }

    public static bool IsCreditCardsLoaded => MainModel.Instance.IsCreditCardsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsCreditCardsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<CreditCard>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.CreditCardId).ToHashSet();
        var collection = MainModel.Instance.CreditCards;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.CreditCardId, freshItem.CreditCardId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].CreditCardId)) collection.RemoveAt(i);
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadCreditCardsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(CreditCard fresh)
    {
        CreditCardId = fresh.CreditCardId;
        CardType = fresh.CardType;
        CardNumber = fresh.CardNumber;
        ExpMonth = fresh.ExpMonth;
        ExpYear = fresh.ExpYear;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<CreditCard>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<CreditCard>? _creditCards;
    public ObservableCollection<CreditCard> CreditCards
    {
        get { if (_creditCards == null) CreditCards = new ObservableCollection<CreditCard>(); return _creditCards!; }
        private set
        {
            SetProperty(ref _creditCards, value);
            OnPropertyChanged(nameof(IsCreditCardsLoaded));
        }
    }

    public bool IsCreditCardsLoaded => _creditCards != null;

    internal void UnloadCreditCardsStorage()
    {
        if (_creditCards == null) return;
        _creditCards = null;
        OnPropertyChanged(nameof(CreditCards));
        OnPropertyChanged(nameof(IsCreditCardsLoaded));
    }
}
}
