// <auto-generated>
//     Generated from CurrencyRate.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class CurrencyRate : ModelEntityBase
{
    [ObservableProperty]
    private int _currencyRateId;

    [ObservableProperty]
    private DateTime _currencyRateDate;

    [ObservableProperty]
    private string _fromCurrencyCode = null!;

    [ObservableProperty]
    private string _toCurrencyCode = null!;

    [ObservableProperty]
    private decimal _averageRate;

    [ObservableProperty]
    private decimal _endOfDayRate;

    [ObservableProperty]
    private DateTime _modifiedDate;

    // TODO: could not auto-detect the foreign key for 'FromCurrencyCodeNavigation' -> Currency.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Currency? FromCurrencyCodeNavigation => MainModel.Instance.Currencies.FirstOrDefault(x => /* match condition */);

    // TODO: could not auto-detect the foreign key for 'ToCurrencyCodeNavigation' -> Currency.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Currency? ToCurrencyCodeNavigation => MainModel.Instance.Currencies.FirstOrDefault(x => /* match condition */);

    private ObservableCollection<SalesOrderHeader>? _salesOrderHeaders;
    public ObservableCollection<SalesOrderHeader> SalesOrderHeaders
    {
        get { if (_salesOrderHeaders == null) SalesOrderHeaders = new LiveFilteredCollection<SalesOrderHeader>(MainModel.Instance.SalesOrderHeaders, x => x.CurrencyRateId == this.CurrencyRateId, nameof(SalesOrderHeader.CurrencyRateId)); return _salesOrderHeaders!; }
        private set => SetProperty(ref _salesOrderHeaders, value);
    }

    public static bool IsCurrencyRatesLoaded => MainModel.Instance.IsCurrencyRatesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsCurrencyRatesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<CurrencyRate>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<CurrencyRate>)MainModel.Instance.CurrencyRates).ReplaceRange(fresh);

        MainModel.Instance.IsCurrencyRatesLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadCurrencyRatesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(CurrencyRate fresh)
    {
        CurrencyRateId = fresh.CurrencyRateId;
        CurrencyRateDate = fresh.CurrencyRateDate;
        FromCurrencyCode = fresh.FromCurrencyCode;
        ToCurrencyCode = fresh.ToCurrencyCode;
        AverageRate = fresh.AverageRate;
        EndOfDayRate = fresh.EndOfDayRate;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<CurrencyRate>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<CurrencyRate>? _currencyRates;
    public ObservableRangeCollection<CurrencyRate> CurrencyRates
    {
        get { if (_currencyRates == null) CurrencyRates = new ObservableRangeCollection<CurrencyRate>(); return _currencyRates!; }
        private set => SetProperty(ref _currencyRates, value);
    }

    private bool _isCurrencyRatesLoaded;
    public bool IsCurrencyRatesLoaded
    {
        get => _isCurrencyRatesLoaded;
        internal set => SetProperty(ref _isCurrencyRatesLoaded, value);
    }

    internal void UnloadCurrencyRatesStorage()
    {
        if (_currencyRates == null) return;
        _currencyRates = null;
        OnPropertyChanged(nameof(CurrencyRates));

        IsCurrencyRatesLoaded = false;
    }
}
}
