// <auto-generated>
//     Generated from Currency.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class Currency : ModelEntityBase
{
    [ObservableProperty]
    private string _currencyCode = null!;

    [ObservableProperty]
    private string _name = null!;

    [ObservableProperty]
    private DateTime _modifiedDate;

    private ObservableCollection<CountryRegionCurrency>? _countryRegionCurrencies;
    public ObservableCollection<CountryRegionCurrency> CountryRegionCurrencies
    {
        get { if (_countryRegionCurrencies == null) CountryRegionCurrencies = new LiveFilteredCollection<CountryRegionCurrency>(MainModel.Instance.CountryRegionCurrencies, x => x.CurrencyCode == this.CurrencyCode, nameof(CountryRegionCurrency.CurrencyCode)); return _countryRegionCurrencies!; }
        private set => SetProperty(ref _countryRegionCurrencies, value);
    }

    private ObservableCollection<CurrencyRate>? _currencyRateFromCurrencyCodeNavigations;
    public ObservableCollection<CurrencyRate> CurrencyRateFromCurrencyCodeNavigations
    {
        // TODO: could not auto-detect the foreign key linking CurrencyRate back to Currency.
        // Example: new LiveFilteredCollection<CurrencyRate>(MainModel.Instance.CurrencyRates, x => /* match condition */, nameof(CurrencyRate.SomeProperty))
        get { if (_currencyRateFromCurrencyCodeNavigations == null) CurrencyRateFromCurrencyCodeNavigations = new ObservableCollection<CurrencyRate>(); return _currencyRateFromCurrencyCodeNavigations!; }
        private set => SetProperty(ref _currencyRateFromCurrencyCodeNavigations, value);
    }

    private ObservableCollection<CurrencyRate>? _currencyRateToCurrencyCodeNavigations;
    public ObservableCollection<CurrencyRate> CurrencyRateToCurrencyCodeNavigations
    {
        // TODO: could not auto-detect the foreign key linking CurrencyRate back to Currency.
        // Example: new LiveFilteredCollection<CurrencyRate>(MainModel.Instance.CurrencyRates, x => /* match condition */, nameof(CurrencyRate.SomeProperty))
        get { if (_currencyRateToCurrencyCodeNavigations == null) CurrencyRateToCurrencyCodeNavigations = new ObservableCollection<CurrencyRate>(); return _currencyRateToCurrencyCodeNavigations!; }
        private set => SetProperty(ref _currencyRateToCurrencyCodeNavigations, value);
    }

    public static bool IsCurrenciesLoaded => MainModel.Instance.IsCurrenciesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsCurrenciesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<Currency>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.CurrencyCode).ToHashSet();
        var collection = MainModel.Instance.Currencies;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.CurrencyCode, freshItem.CurrencyCode));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].CurrencyCode)) collection.RemoveAt(i);

        // Explicitly flag the collection as loaded after a successful database query
        MainModel.Instance.IsCurrenciesLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadCurrenciesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(Currency fresh)
    {
        CurrencyCode = fresh.CurrencyCode;
        Name = fresh.Name;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<Currency>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<Currency>? _currencies;
    public ObservableCollection<Currency> Currencies
    {
        get { if (_currencies == null) Currencies = new ObservableCollection<Currency>(); return _currencies!; }
        private set => SetProperty(ref _currencies, value);
    }

    private bool _isCurrenciesLoaded;
    public bool IsCurrenciesLoaded
    {
        get => _isCurrenciesLoaded;
        internal set => SetProperty(ref _isCurrenciesLoaded, value);
    }

    internal void UnloadCurrenciesStorage()
    {
        if (_currencies == null) return;
        _currencies = null;
        OnPropertyChanged(nameof(Currencies));

        // Reset the load state flag
        IsCurrenciesLoaded = false;
    }
}
}
