// <auto-generated>
//     Generated from Customer.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class Customer : ModelEntityBase
{
    [ObservableProperty]
    private int _customerId;

    [ObservableProperty]
    private int? _personId;

    [ObservableProperty]
    private int? _storeId;

    [ObservableProperty]
    private int? _territoryId;

    [ObservableProperty]
    private string _accountNumber = null!;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    // TODO: could not auto-detect the foreign key for 'Person' -> Person.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Person? Person => MainModel.Instance.Persons.FirstOrDefault(x => /* match condition */);

    // TODO: could not auto-detect the foreign key for 'Store' -> Store.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Store? Store => MainModel.Instance.Stores.FirstOrDefault(x => /* match condition */);

    // TODO: could not auto-detect the foreign key for 'Territory' -> SalesTerritory.
    // Add a manual implementation in a separate partial file, e.g.:
    // public SalesTerritory? Territory => MainModel.Instance.SalesTerritories.FirstOrDefault(x => /* match condition */);

    private ObservableCollection<SalesOrderHeader>? _salesOrderHeaders;
    public ObservableCollection<SalesOrderHeader> SalesOrderHeaders
    {
        get { if (_salesOrderHeaders == null) SalesOrderHeaders = new LiveFilteredCollection<SalesOrderHeader>(MainModel.Instance.SalesOrderHeaders, x => x.CustomerId == this.CustomerId, nameof(SalesOrderHeader.CustomerId)); return _salesOrderHeaders!; }
        private set => SetProperty(ref _salesOrderHeaders, value);
    }

    public static bool IsCustomersLoaded => MainModel.Instance.IsCustomersLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsCustomersLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<Customer>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.CustomerId).ToHashSet();
        var collection = MainModel.Instance.Customers;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.CustomerId, freshItem.CustomerId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].CustomerId)) collection.RemoveAt(i);
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadCustomersStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(Customer fresh)
    {
        CustomerId = fresh.CustomerId;
        PersonId = fresh.PersonId;
        StoreId = fresh.StoreId;
        TerritoryId = fresh.TerritoryId;
        AccountNumber = fresh.AccountNumber;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<Customer>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<Customer>? _customers;
    public ObservableCollection<Customer> Customers
    {
        get { if (_customers == null) Customers = new ObservableCollection<Customer>(); return _customers!; }
        private set
        {
            SetProperty(ref _customers, value);
            OnPropertyChanged(nameof(IsCustomersLoaded));
        }
    }

    public bool IsCustomersLoaded => _customers != null;

    internal void UnloadCustomersStorage()
    {
        if (_customers == null) return;
        _customers = null;
        OnPropertyChanged(nameof(Customers));
        OnPropertyChanged(nameof(IsCustomersLoaded));
    }
}
}
