// <auto-generated>
//     Generated from EmployeePayHistory.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class EmployeePayHistory : ModelEntityBase
{
    [ObservableProperty]
    private int _businessEntityId;

    [ObservableProperty]
    private DateTime _rateChangeDate;

    [ObservableProperty]
    private decimal _rate;

    [ObservableProperty]
    private byte _payFrequency;

    [ObservableProperty]
    private DateTime _modifiedDate;

    // TODO: could not auto-detect the foreign key for 'BusinessEntity' -> Employee.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Employee? BusinessEntity => MainModel.Instance.Employees.FirstOrDefault(x => /* match condition */);

    public static bool IsEmployeePayHistoriesLoaded => MainModel.Instance.IsEmployeePayHistoriesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsEmployeePayHistoriesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<EmployeePayHistory>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.BusinessEntityId).ToHashSet();
        var collection = MainModel.Instance.EmployeePayHistories;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.BusinessEntityId, freshItem.BusinessEntityId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].BusinessEntityId)) collection.RemoveAt(i);
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadEmployeePayHistoriesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(EmployeePayHistory fresh)
    {
        BusinessEntityId = fresh.BusinessEntityId;
        RateChangeDate = fresh.RateChangeDate;
        Rate = fresh.Rate;
        PayFrequency = fresh.PayFrequency;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<EmployeePayHistory>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<EmployeePayHistory>? _employeePayHistories;
    public ObservableCollection<EmployeePayHistory> EmployeePayHistories
    {
        get { if (_employeePayHistories == null) EmployeePayHistories = new ObservableCollection<EmployeePayHistory>(); return _employeePayHistories!; }
        private set
        {
            SetProperty(ref _employeePayHistories, value);
            OnPropertyChanged(nameof(IsEmployeePayHistoriesLoaded));
        }
    }

    public bool IsEmployeePayHistoriesLoaded => _employeePayHistories != null;

    internal void UnloadEmployeePayHistoriesStorage()
    {
        if (_employeePayHistories == null) return;
        _employeePayHistories = null;
        OnPropertyChanged(nameof(EmployeePayHistories));
        OnPropertyChanged(nameof(IsEmployeePayHistoriesLoaded));
    }
}
}
