// <auto-generated>
//     Generated from ErrorLog.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class ErrorLog : ModelEntityBase
{
    public static string SqlSchema => "dbo";
    public static string SqlTableName => "ErrorLog";
    [ObservableProperty]
    private int _errorLogId;

    [ObservableProperty]
    private DateTime _errorTime;

    [ObservableProperty]
    private string _userName = null!;

    [ObservableProperty]
    private int _errorNumber;

    [ObservableProperty]
    private int? _errorSeverity;

    [ObservableProperty]
    private int? _errorState;

    [ObservableProperty]
    private string _errorProcedure = null!;

    [ObservableProperty]
    private int? _errorLine;

    [ObservableProperty]
    private string _errorMessage = null!;

    public static bool IsErrorLogsLoaded => MainModel.Instance.IsErrorLogsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsErrorLogsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<ErrorLog>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<ErrorLog>)MainModel.Instance.ErrorLogs).ReplaceRange(fresh);

        MainModel.Instance.IsErrorLogsLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadErrorLogsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(ErrorLog fresh)
    {
        ErrorLogId = fresh.ErrorLogId;
        ErrorTime = fresh.ErrorTime;
        UserName = fresh.UserName;
        ErrorNumber = fresh.ErrorNumber;
        ErrorSeverity = fresh.ErrorSeverity;
        ErrorState = fresh.ErrorState;
        ErrorProcedure = fresh.ErrorProcedure;
        ErrorLine = fresh.ErrorLine;
        ErrorMessage = fresh.ErrorMessage;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<ErrorLog>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<ErrorLog>? _errorLogs;
    public ObservableRangeCollection<ErrorLog> ErrorLogs
    {
        get { if (_errorLogs == null) ErrorLogs = new ObservableRangeCollection<ErrorLog>(); return _errorLogs!; }
        private set => SetProperty(ref _errorLogs, value);
    }

    private bool _isErrorLogsLoaded;
    public bool IsErrorLogsLoaded
    {
        get => _isErrorLogsLoaded;
        internal set => SetProperty(ref _isErrorLogsLoaded, value);
    }

    internal void UnloadErrorLogsStorage()
    {
        if (_errorLogs == null) return;
        _errorLogs = null;
        OnPropertyChanged(nameof(ErrorLogs));

        IsErrorLogsLoaded = false;
    }
}
}
