// <auto-generated>
//     Generated from Password.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class Password : ModelEntityBase
{
    public static string SqlSchema => "Person";
    public static string SqlTableName => "Password";
    [ObservableProperty]
    private int _businessEntityId;

    [ObservableProperty]
    private string _passwordHash = null!;

    [ObservableProperty]
    private string _passwordSalt = null!;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    // TODO: could not auto-detect the foreign key for 'BusinessEntity' -> Person.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Person? BusinessEntity => MainModel.Instance.Persons.FirstOrDefault(x => /* match condition */);

    public static bool IsPasswordsLoaded => MainModel.Instance.IsPasswordsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsPasswordsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<Password>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<Password>)MainModel.Instance.Passwords).ReplaceRange(fresh);

        MainModel.Instance.IsPasswordsLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadPasswordsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(Password fresh)
    {
        BusinessEntityId = fresh.BusinessEntityId;
        PasswordHash = fresh.PasswordHash;
        PasswordSalt = fresh.PasswordSalt;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<Password>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<Password>? _passwords;
    public ObservableRangeCollection<Password> Passwords
    {
        get { if (_passwords == null) Passwords = new ObservableRangeCollection<Password>(); return _passwords!; }
        private set => SetProperty(ref _passwords, value);
    }

    private bool _isPasswordsLoaded;
    public bool IsPasswordsLoaded
    {
        get => _isPasswordsLoaded;
        internal set => SetProperty(ref _isPasswordsLoaded, value);
    }

    internal void UnloadPasswordsStorage()
    {
        if (_passwords == null) return;
        _passwords = null;
        OnPropertyChanged(nameof(Passwords));

        IsPasswordsLoaded = false;
    }
}
}
