// <auto-generated>
//     Generated from Person.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class Person : ModelEntityBase
{
    public static string SqlSchema => "Person";
    public static string SqlTableName => "Person";
    [ObservableProperty]
    private int _businessEntityId;

    [ObservableProperty]
    private string _personType = null!;

    [ObservableProperty]
    private bool _nameStyle;

    [ObservableProperty]
    private string _title = null!;

    [ObservableProperty]
    private string _firstName = null!;

    [ObservableProperty]
    private string _middleName = null!;

    [ObservableProperty]
    private string _lastName = null!;

    [ObservableProperty]
    private string _suffix = null!;

    [ObservableProperty]
    private int _emailPromotion;

    [ObservableProperty]
    private string _additionalContactInfo = null!;

    [ObservableProperty]
    private string _demographics = null!;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public BusinessEntity? BusinessEntity => MainModel.Instance.BusinessEntities.FirstOrDefault(x => x.BusinessEntityId == this.BusinessEntityId);

    // TODO: could not auto-detect the foreign key for 'Employee' -> Employee.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Employee? Employee => MainModel.Instance.Employees.FirstOrDefault(x => /* match condition */);

    // TODO: could not auto-detect the foreign key for 'Password' -> Password.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Password? Password => MainModel.Instance.Passwords.FirstOrDefault(x => /* match condition */);

    private ObservableCollection<BusinessEntityContact>? _businessEntityContacts;
    public ObservableCollection<BusinessEntityContact> BusinessEntityContacts
    {
        // TODO: could not auto-detect the foreign key linking BusinessEntityContact back to Person.
        // Example: new LiveFilteredCollection<BusinessEntityContact>(MainModel.Instance.BusinessEntityContacts, x => /* match condition */, nameof(BusinessEntityContact.SomeProperty))
        get { if (_businessEntityContacts == null) BusinessEntityContacts = new ObservableCollection<BusinessEntityContact>(); return _businessEntityContacts!; }
        private set => SetProperty(ref _businessEntityContacts, value);
    }

    private ObservableCollection<Customer>? _customers;
    public ObservableCollection<Customer> Customers
    {
        // TODO: could not auto-detect the foreign key linking Customer back to Person.
        // Example: new LiveFilteredCollection<Customer>(MainModel.Instance.Customers, x => /* match condition */, nameof(Customer.SomeProperty))
        get { if (_customers == null) Customers = new ObservableCollection<Customer>(); return _customers!; }
        private set => SetProperty(ref _customers, value);
    }

    private ObservableCollection<EmailAddress>? _emailAddresses;
    public ObservableCollection<EmailAddress> EmailAddresses
    {
        // TODO: could not auto-detect the foreign key linking EmailAddress back to Person.
        // Example: new LiveFilteredCollection<EmailAddress>(MainModel.Instance.EmailAddresses, x => /* match condition */, nameof(EmailAddress.SomeProperty))
        get { if (_emailAddresses == null) EmailAddresses = new ObservableCollection<EmailAddress>(); return _emailAddresses!; }
        private set => SetProperty(ref _emailAddresses, value);
    }

    private ObservableCollection<PersonCreditCard>? _personCreditCards;
    public ObservableCollection<PersonCreditCard> PersonCreditCards
    {
        // TODO: could not auto-detect the foreign key linking PersonCreditCard back to Person.
        // Example: new LiveFilteredCollection<PersonCreditCard>(MainModel.Instance.PersonCreditCards, x => /* match condition */, nameof(PersonCreditCard.SomeProperty))
        get { if (_personCreditCards == null) PersonCreditCards = new ObservableCollection<PersonCreditCard>(); return _personCreditCards!; }
        private set => SetProperty(ref _personCreditCards, value);
    }

    private ObservableCollection<PersonPhone>? _personPhones;
    public ObservableCollection<PersonPhone> PersonPhones
    {
        // TODO: could not auto-detect the foreign key linking PersonPhone back to Person.
        // Example: new LiveFilteredCollection<PersonPhone>(MainModel.Instance.PersonPhones, x => /* match condition */, nameof(PersonPhone.SomeProperty))
        get { if (_personPhones == null) PersonPhones = new ObservableCollection<PersonPhone>(); return _personPhones!; }
        private set => SetProperty(ref _personPhones, value);
    }

    public static bool IsPersonsLoaded => MainModel.Instance.IsPersonsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsPersonsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<Person>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<Person>)MainModel.Instance.Persons).ReplaceRange(fresh);

        MainModel.Instance.IsPersonsLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadPersonsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(Person fresh)
    {
        BusinessEntityId = fresh.BusinessEntityId;
        PersonType = fresh.PersonType;
        NameStyle = fresh.NameStyle;
        Title = fresh.Title;
        FirstName = fresh.FirstName;
        MiddleName = fresh.MiddleName;
        LastName = fresh.LastName;
        Suffix = fresh.Suffix;
        EmailPromotion = fresh.EmailPromotion;
        AdditionalContactInfo = fresh.AdditionalContactInfo;
        Demographics = fresh.Demographics;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<Person>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<Person>? _persons;
    public ObservableRangeCollection<Person> Persons
    {
        get { if (_persons == null) Persons = new ObservableRangeCollection<Person>(); return _persons!; }
        private set => SetProperty(ref _persons, value);
    }

    private bool _isPersonsLoaded;
    public bool IsPersonsLoaded
    {
        get => _isPersonsLoaded;
        internal set => SetProperty(ref _isPersonsLoaded, value);
    }

    internal void UnloadPersonsStorage()
    {
        if (_persons == null) return;
        _persons = null;
        OnPropertyChanged(nameof(Persons));

        IsPersonsLoaded = false;
    }
}
}
