// <auto-generated>
//     Generated from PersonCreditCard.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class PersonCreditCard : ModelEntityBase
{
    [ObservableProperty]
    private int _businessEntityId;

    [ObservableProperty]
    private int _creditCardId;

    [ObservableProperty]
    private DateTime _modifiedDate;

    // TODO: could not auto-detect the foreign key for 'BusinessEntity' -> Person.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Person? BusinessEntity => MainModel.Instance.Persons.FirstOrDefault(x => /* match condition */);

    public CreditCard? CreditCard => MainModel.Instance.CreditCards.FirstOrDefault(x => x.CreditCardId == this.CreditCardId);

    public static bool IsPersonCreditCardsLoaded => MainModel.Instance.IsPersonCreditCardsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsPersonCreditCardsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<PersonCreditCard>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.BusinessEntityId).ToHashSet();
        var collection = MainModel.Instance.PersonCreditCards;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.BusinessEntityId, freshItem.BusinessEntityId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].BusinessEntityId)) collection.RemoveAt(i);

        // Explicitly flag the collection as loaded after a successful database query
        MainModel.Instance.IsPersonCreditCardsLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadPersonCreditCardsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(PersonCreditCard fresh)
    {
        BusinessEntityId = fresh.BusinessEntityId;
        CreditCardId = fresh.CreditCardId;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<PersonCreditCard>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<PersonCreditCard>? _personCreditCards;
    public ObservableCollection<PersonCreditCard> PersonCreditCards
    {
        get { if (_personCreditCards == null) PersonCreditCards = new ObservableCollection<PersonCreditCard>(); return _personCreditCards!; }
        private set => SetProperty(ref _personCreditCards, value);
    }

    private bool _isPersonCreditCardsLoaded;
    public bool IsPersonCreditCardsLoaded
    {
        get => _isPersonCreditCardsLoaded;
        internal set => SetProperty(ref _isPersonCreditCardsLoaded, value);
    }

    internal void UnloadPersonCreditCardsStorage()
    {
        if (_personCreditCards == null) return;
        _personCreditCards = null;
        OnPropertyChanged(nameof(PersonCreditCards));

        // Reset the load state flag
        IsPersonCreditCardsLoaded = false;
    }
}
}
