// <auto-generated>
//     Generated from PersonPhone.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class PersonPhone : ModelEntityBase
{
    public static string SqlSchema => "Person";
    public static string SqlTableName => "PersonPhone";
    [ObservableProperty]
    private int _businessEntityId;

    [ObservableProperty]
    private string _phoneNumber = null!;

    [ObservableProperty]
    private int _phoneNumberTypeId;

    [ObservableProperty]
    private DateTime _modifiedDate;

    // TODO: could not auto-detect the foreign key for 'BusinessEntity' -> Person.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Person? BusinessEntity => MainModel.Instance.Persons.FirstOrDefault(x => /* match condition */);

    public PhoneNumberType? PhoneNumberType => MainModel.Instance.PhoneNumberTypes.FirstOrDefault(x => x.PhoneNumberTypeId == this.PhoneNumberTypeId);

    public static bool IsPersonPhonesLoaded => MainModel.Instance.IsPersonPhonesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsPersonPhonesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<PersonPhone>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<PersonPhone>)MainModel.Instance.PersonPhones).ReplaceRange(fresh);

        MainModel.Instance.IsPersonPhonesLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadPersonPhonesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(PersonPhone fresh)
    {
        BusinessEntityId = fresh.BusinessEntityId;
        PhoneNumber = fresh.PhoneNumber;
        PhoneNumberTypeId = fresh.PhoneNumberTypeId;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<PersonPhone>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<PersonPhone>? _personPhones;
    public ObservableRangeCollection<PersonPhone> PersonPhones
    {
        get { if (_personPhones == null) PersonPhones = new ObservableRangeCollection<PersonPhone>(); return _personPhones!; }
        private set => SetProperty(ref _personPhones, value);
    }

    private bool _isPersonPhonesLoaded;
    public bool IsPersonPhonesLoaded
    {
        get => _isPersonPhonesLoaded;
        internal set => SetProperty(ref _isPersonPhonesLoaded, value);
    }

    internal void UnloadPersonPhonesStorage()
    {
        if (_personPhones == null) return;
        _personPhones = null;
        OnPropertyChanged(nameof(PersonPhones));

        IsPersonPhonesLoaded = false;
    }
}
}
