// <auto-generated>
//     Generated from PhoneNumberType.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class PhoneNumberType : ModelEntityBase
{
    public static string SqlSchema => "Person";
    public static string SqlTableName => "PhoneNumberType";
    [ObservableProperty]
    private int _phoneNumberTypeId;

    [ObservableProperty]
    private string _name = null!;

    [ObservableProperty]
    private DateTime _modifiedDate;

    private ObservableCollection<PersonPhone>? _personPhones;
    public ObservableCollection<PersonPhone> PersonPhones
    {
        get { if (_personPhones == null) PersonPhones = new LiveFilteredCollection<PersonPhone>(MainModel.Instance.PersonPhones, x => x.PhoneNumberTypeId == this.PhoneNumberTypeId, nameof(PersonPhone.PhoneNumberTypeId)); return _personPhones!; }
        private set => SetProperty(ref _personPhones, value);
    }

    public static bool IsPhoneNumberTypesLoaded => MainModel.Instance.IsPhoneNumberTypesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsPhoneNumberTypesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<PhoneNumberType>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<PhoneNumberType>)MainModel.Instance.PhoneNumberTypes).ReplaceRange(fresh);

        MainModel.Instance.IsPhoneNumberTypesLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadPhoneNumberTypesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(PhoneNumberType fresh)
    {
        PhoneNumberTypeId = fresh.PhoneNumberTypeId;
        Name = fresh.Name;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<PhoneNumberType>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<PhoneNumberType>? _phoneNumberTypes;
    public ObservableRangeCollection<PhoneNumberType> PhoneNumberTypes
    {
        get { if (_phoneNumberTypes == null) PhoneNumberTypes = new ObservableRangeCollection<PhoneNumberType>(); return _phoneNumberTypes!; }
        private set => SetProperty(ref _phoneNumberTypes, value);
    }

    private bool _isPhoneNumberTypesLoaded;
    public bool IsPhoneNumberTypesLoaded
    {
        get => _isPhoneNumberTypesLoaded;
        internal set => SetProperty(ref _isPhoneNumberTypesLoaded, value);
    }

    internal void UnloadPhoneNumberTypesStorage()
    {
        if (_phoneNumberTypes == null) return;
        _phoneNumberTypes = null;
        OnPropertyChanged(nameof(PhoneNumberTypes));

        IsPhoneNumberTypesLoaded = false;
    }
}
}
