// <auto-generated>
//     Generated from ProductModelIllustration.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class ProductModelIllustration : ModelEntityBase
{
    public static string SqlSchema => "Production";
    public static string SqlTableName => "ProductModelIllustration";
    [ObservableProperty]
    private int _productModelId;

    [ObservableProperty]
    private int _illustrationId;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public Illustration? Illustration => MainModel.Instance.Illustrations.FirstOrDefault(x => x.IllustrationId == this.IllustrationId);

    public ProductModel? ProductModel => MainModel.Instance.ProductModels.FirstOrDefault(x => x.ProductModelId == this.ProductModelId);

    public static bool IsProductModelIllustrationsLoaded => MainModel.Instance.IsProductModelIllustrationsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsProductModelIllustrationsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<ProductModelIllustration>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<ProductModelIllustration>)MainModel.Instance.ProductModelIllustrations).ReplaceRange(fresh);

        MainModel.Instance.IsProductModelIllustrationsLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadProductModelIllustrationsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(ProductModelIllustration fresh)
    {
        ProductModelId = fresh.ProductModelId;
        IllustrationId = fresh.IllustrationId;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<ProductModelIllustration>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<ProductModelIllustration>? _productModelIllustrations;
    public ObservableRangeCollection<ProductModelIllustration> ProductModelIllustrations
    {
        get { if (_productModelIllustrations == null) ProductModelIllustrations = new ObservableRangeCollection<ProductModelIllustration>(); return _productModelIllustrations!; }
        private set => SetProperty(ref _productModelIllustrations, value);
    }

    private bool _isProductModelIllustrationsLoaded;
    public bool IsProductModelIllustrationsLoaded
    {
        get => _isProductModelIllustrationsLoaded;
        internal set => SetProperty(ref _isProductModelIllustrationsLoaded, value);
    }

    internal void UnloadProductModelIllustrationsStorage()
    {
        if (_productModelIllustrations == null) return;
        _productModelIllustrations = null;
        OnPropertyChanged(nameof(ProductModelIllustrations));

        IsProductModelIllustrationsLoaded = false;
    }
}
}
