// <auto-generated>
//     Generated from Product.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class Product : ModelEntityBase
{
    [ObservableProperty]
    private int _productId;

    [ObservableProperty]
    private string _name = null!;

    [ObservableProperty]
    private string _productNumber = null!;

    [ObservableProperty]
    private bool _makeFlag;

    [ObservableProperty]
    private bool _finishedGoodsFlag;

    [ObservableProperty]
    private string _color = null!;

    [ObservableProperty]
    private short _safetyStockLevel;

    [ObservableProperty]
    private short _reorderPoint;

    [ObservableProperty]
    private decimal _standardCost;

    [ObservableProperty]
    private decimal _listPrice;

    [ObservableProperty]
    private string _size = null!;

    [ObservableProperty]
    private string _sizeUnitMeasureCode = null!;

    [ObservableProperty]
    private string _weightUnitMeasureCode = null!;

    [ObservableProperty]
    private decimal? _weight;

    [ObservableProperty]
    private int _daysToManufacture;

    [ObservableProperty]
    private string _productLine = null!;

    [ObservableProperty]
    private string _class = null!;

    [ObservableProperty]
    private string _style = null!;

    [ObservableProperty]
    private int? _productSubcategoryId;

    [ObservableProperty]
    private int? _productModelId;

    [ObservableProperty]
    private DateTime _sellStartDate;

    [ObservableProperty]
    private DateTime? _sellEndDate;

    [ObservableProperty]
    private DateTime? _discontinuedDate;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public ProductModel? ProductModel => MainModel.Instance.ProductModels.FirstOrDefault(x => x.ProductModelId == this.ProductModelId);

    public ProductSubcategory? ProductSubcategory => MainModel.Instance.ProductSubcategories.FirstOrDefault(x => x.ProductSubcategoryId == this.ProductSubcategoryId);

    // TODO: could not auto-detect the foreign key for 'SizeUnitMeasureCodeNavigation' -> UnitMeasure.
    // Add a manual implementation in a separate partial file, e.g.:
    // public UnitMeasure? SizeUnitMeasureCodeNavigation => MainModel.Instance.UnitMeasures.FirstOrDefault(x => /* match condition */);

    // TODO: could not auto-detect the foreign key for 'WeightUnitMeasureCodeNavigation' -> UnitMeasure.
    // Add a manual implementation in a separate partial file, e.g.:
    // public UnitMeasure? WeightUnitMeasureCodeNavigation => MainModel.Instance.UnitMeasures.FirstOrDefault(x => /* match condition */);

    private ObservableCollection<BillOfMaterial>? _billOfMaterialComponents;
    public ObservableCollection<BillOfMaterial> BillOfMaterialComponents
    {
        // TODO: could not auto-detect the foreign key linking BillOfMaterial back to Product.
        // Example: new LiveFilteredCollection<BillOfMaterial>(MainModel.Instance.BillOfMaterials, x => /* match condition */, nameof(BillOfMaterial.SomeProperty))
        get { if (_billOfMaterialComponents == null) BillOfMaterialComponents = new ObservableCollection<BillOfMaterial>(); return _billOfMaterialComponents!; }
        private set => SetProperty(ref _billOfMaterialComponents, value);
    }

    private ObservableCollection<BillOfMaterial>? _billOfMaterialProductAssemblies;
    public ObservableCollection<BillOfMaterial> BillOfMaterialProductAssemblies
    {
        // TODO: could not auto-detect the foreign key linking BillOfMaterial back to Product.
        // Example: new LiveFilteredCollection<BillOfMaterial>(MainModel.Instance.BillOfMaterials, x => /* match condition */, nameof(BillOfMaterial.SomeProperty))
        get { if (_billOfMaterialProductAssemblies == null) BillOfMaterialProductAssemblies = new ObservableCollection<BillOfMaterial>(); return _billOfMaterialProductAssemblies!; }
        private set => SetProperty(ref _billOfMaterialProductAssemblies, value);
    }

    private ObservableCollection<ProductCostHistory>? _productCostHistories;
    public ObservableCollection<ProductCostHistory> ProductCostHistories
    {
        get { if (_productCostHistories == null) ProductCostHistories = new LiveFilteredCollection<ProductCostHistory>(MainModel.Instance.ProductCostHistories, x => x.ProductId == this.ProductId, nameof(ProductCostHistory.ProductId)); return _productCostHistories!; }
        private set => SetProperty(ref _productCostHistories, value);
    }

    private ObservableCollection<ProductInventory>? _productInventories;
    public ObservableCollection<ProductInventory> ProductInventories
    {
        get { if (_productInventories == null) ProductInventories = new LiveFilteredCollection<ProductInventory>(MainModel.Instance.ProductInventories, x => x.ProductId == this.ProductId, nameof(ProductInventory.ProductId)); return _productInventories!; }
        private set => SetProperty(ref _productInventories, value);
    }

    private ObservableCollection<ProductListPriceHistory>? _productListPriceHistories;
    public ObservableCollection<ProductListPriceHistory> ProductListPriceHistories
    {
        get { if (_productListPriceHistories == null) ProductListPriceHistories = new LiveFilteredCollection<ProductListPriceHistory>(MainModel.Instance.ProductListPriceHistories, x => x.ProductId == this.ProductId, nameof(ProductListPriceHistory.ProductId)); return _productListPriceHistories!; }
        private set => SetProperty(ref _productListPriceHistories, value);
    }

    private ObservableCollection<ProductProductPhoto>? _productProductPhotos;
    public ObservableCollection<ProductProductPhoto> ProductProductPhotos
    {
        get { if (_productProductPhotos == null) ProductProductPhotos = new LiveFilteredCollection<ProductProductPhoto>(MainModel.Instance.ProductProductPhotos, x => x.ProductId == this.ProductId, nameof(ProductProductPhoto.ProductId)); return _productProductPhotos!; }
        private set => SetProperty(ref _productProductPhotos, value);
    }

    private ObservableCollection<ProductReview>? _productReviews;
    public ObservableCollection<ProductReview> ProductReviews
    {
        get { if (_productReviews == null) ProductReviews = new LiveFilteredCollection<ProductReview>(MainModel.Instance.ProductReviews, x => x.ProductId == this.ProductId, nameof(ProductReview.ProductId)); return _productReviews!; }
        private set => SetProperty(ref _productReviews, value);
    }

    private ObservableCollection<ProductVendor>? _productVendors;
    public ObservableCollection<ProductVendor> ProductVendors
    {
        get { if (_productVendors == null) ProductVendors = new LiveFilteredCollection<ProductVendor>(MainModel.Instance.ProductVendors, x => x.ProductId == this.ProductId, nameof(ProductVendor.ProductId)); return _productVendors!; }
        private set => SetProperty(ref _productVendors, value);
    }

    private ObservableCollection<PurchaseOrderDetail>? _purchaseOrderDetails;
    public ObservableCollection<PurchaseOrderDetail> PurchaseOrderDetails
    {
        get { if (_purchaseOrderDetails == null) PurchaseOrderDetails = new LiveFilteredCollection<PurchaseOrderDetail>(MainModel.Instance.PurchaseOrderDetails, x => x.ProductId == this.ProductId, nameof(PurchaseOrderDetail.ProductId)); return _purchaseOrderDetails!; }
        private set => SetProperty(ref _purchaseOrderDetails, value);
    }

    private ObservableCollection<ShoppingCartItem>? _shoppingCartItems;
    public ObservableCollection<ShoppingCartItem> ShoppingCartItems
    {
        get { if (_shoppingCartItems == null) ShoppingCartItems = new LiveFilteredCollection<ShoppingCartItem>(MainModel.Instance.ShoppingCartItems, x => x.ProductId == this.ProductId, nameof(ShoppingCartItem.ProductId)); return _shoppingCartItems!; }
        private set => SetProperty(ref _shoppingCartItems, value);
    }

    private ObservableCollection<SpecialOfferProduct>? _specialOfferProducts;
    public ObservableCollection<SpecialOfferProduct> SpecialOfferProducts
    {
        get { if (_specialOfferProducts == null) SpecialOfferProducts = new LiveFilteredCollection<SpecialOfferProduct>(MainModel.Instance.SpecialOfferProducts, x => x.ProductId == this.ProductId, nameof(SpecialOfferProduct.ProductId)); return _specialOfferProducts!; }
        private set => SetProperty(ref _specialOfferProducts, value);
    }

    private ObservableCollection<TransactionHistory>? _transactionHistories;
    public ObservableCollection<TransactionHistory> TransactionHistories
    {
        get { if (_transactionHistories == null) TransactionHistories = new LiveFilteredCollection<TransactionHistory>(MainModel.Instance.TransactionHistories, x => x.ProductId == this.ProductId, nameof(TransactionHistory.ProductId)); return _transactionHistories!; }
        private set => SetProperty(ref _transactionHistories, value);
    }

    private ObservableCollection<WorkOrder>? _workOrders;
    public ObservableCollection<WorkOrder> WorkOrders
    {
        get { if (_workOrders == null) WorkOrders = new LiveFilteredCollection<WorkOrder>(MainModel.Instance.WorkOrders, x => x.ProductId == this.ProductId, nameof(WorkOrder.ProductId)); return _workOrders!; }
        private set => SetProperty(ref _workOrders, value);
    }

    public static bool IsProductsLoaded => MainModel.Instance.IsProductsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsProductsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<Product>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.ProductId).ToHashSet();
        var collection = MainModel.Instance.Products;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.ProductId, freshItem.ProductId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].ProductId)) collection.RemoveAt(i);
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadProductsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(Product fresh)
    {
        ProductId = fresh.ProductId;
        Name = fresh.Name;
        ProductNumber = fresh.ProductNumber;
        MakeFlag = fresh.MakeFlag;
        FinishedGoodsFlag = fresh.FinishedGoodsFlag;
        Color = fresh.Color;
        SafetyStockLevel = fresh.SafetyStockLevel;
        ReorderPoint = fresh.ReorderPoint;
        StandardCost = fresh.StandardCost;
        ListPrice = fresh.ListPrice;
        Size = fresh.Size;
        SizeUnitMeasureCode = fresh.SizeUnitMeasureCode;
        WeightUnitMeasureCode = fresh.WeightUnitMeasureCode;
        Weight = fresh.Weight;
        DaysToManufacture = fresh.DaysToManufacture;
        ProductLine = fresh.ProductLine;
        Class = fresh.Class;
        Style = fresh.Style;
        ProductSubcategoryId = fresh.ProductSubcategoryId;
        ProductModelId = fresh.ProductModelId;
        SellStartDate = fresh.SellStartDate;
        SellEndDate = fresh.SellEndDate;
        DiscontinuedDate = fresh.DiscontinuedDate;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<Product>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<Product>? _products;
    public ObservableCollection<Product> Products
    {
        get { if (_products == null) Products = new ObservableCollection<Product>(); return _products!; }
        private set
        {
            SetProperty(ref _products, value);
            OnPropertyChanged(nameof(IsProductsLoaded));
        }
    }

    public bool IsProductsLoaded => _products != null;

    internal void UnloadProductsStorage()
    {
        if (_products == null) return;
        _products = null;
        OnPropertyChanged(nameof(Products));
        OnPropertyChanged(nameof(IsProductsLoaded));
    }
}
}
