// <auto-generated>
//     Generated from ProductPhoto.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class ProductPhoto : ModelEntityBase
{
    public static string SqlSchema => "Production";
    public static string SqlTableName => "ProductPhoto";
    [ObservableProperty]
    private int _productPhotoId;

    [ObservableProperty]
    private byte[] _thumbNailPhoto = null!;

    [ObservableProperty]
    private string _thumbnailPhotoFileName = null!;

    [ObservableProperty]
    private byte[] _largePhoto = null!;

    [ObservableProperty]
    private string _largePhotoFileName = null!;

    [ObservableProperty]
    private DateTime _modifiedDate;

    private ObservableCollection<ProductProductPhoto>? _productProductPhotos;
    public ObservableCollection<ProductProductPhoto> ProductProductPhotos
    {
        get { if (_productProductPhotos == null) ProductProductPhotos = new LiveFilteredCollection<ProductProductPhoto>(MainModel.Instance.ProductProductPhotos, x => x.ProductPhotoId == this.ProductPhotoId, nameof(ProductProductPhoto.ProductPhotoId)); return _productProductPhotos!; }
        private set => SetProperty(ref _productProductPhotos, value);
    }

    public static bool IsProductPhotosLoaded => MainModel.Instance.IsProductPhotosLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsProductPhotosLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<ProductPhoto>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<ProductPhoto>)MainModel.Instance.ProductPhotos).ReplaceRange(fresh);

        MainModel.Instance.IsProductPhotosLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadProductPhotosStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(ProductPhoto fresh)
    {
        ProductPhotoId = fresh.ProductPhotoId;
        ThumbNailPhoto = fresh.ThumbNailPhoto;
        ThumbnailPhotoFileName = fresh.ThumbnailPhotoFileName;
        LargePhoto = fresh.LargePhoto;
        LargePhotoFileName = fresh.LargePhotoFileName;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<ProductPhoto>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<ProductPhoto>? _productPhotos;
    public ObservableRangeCollection<ProductPhoto> ProductPhotos
    {
        get { if (_productPhotos == null) ProductPhotos = new ObservableRangeCollection<ProductPhoto>(); return _productPhotos!; }
        private set => SetProperty(ref _productPhotos, value);
    }

    private bool _isProductPhotosLoaded;
    public bool IsProductPhotosLoaded
    {
        get => _isProductPhotosLoaded;
        internal set => SetProperty(ref _isProductPhotosLoaded, value);
    }

    internal void UnloadProductPhotosStorage()
    {
        if (_productPhotos == null) return;
        _productPhotos = null;
        OnPropertyChanged(nameof(ProductPhotos));

        IsProductPhotosLoaded = false;
    }
}
}
