// <auto-generated>
//     Generated from ProductListPriceHistory.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class ProductListPriceHistory : ModelEntityBase
{
    [ObservableProperty]
    private int _productId;

    [ObservableProperty]
    private DateTime _startDate;

    [ObservableProperty]
    private DateTime? _endDate;

    [ObservableProperty]
    private decimal _listPrice;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public Product? Product => MainModel.Instance.Products.FirstOrDefault(x => x.ProductId == this.ProductId);

    public static bool IsProductListPriceHistoriesLoaded => MainModel.Instance.IsProductListPriceHistoriesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsProductListPriceHistoriesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<ProductListPriceHistory>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.ProductId).ToHashSet();
        var collection = MainModel.Instance.ProductListPriceHistories;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.ProductId, freshItem.ProductId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].ProductId)) collection.RemoveAt(i);
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadProductListPriceHistoriesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(ProductListPriceHistory fresh)
    {
        ProductId = fresh.ProductId;
        StartDate = fresh.StartDate;
        EndDate = fresh.EndDate;
        ListPrice = fresh.ListPrice;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<ProductListPriceHistory>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<ProductListPriceHistory>? _productListPriceHistories;
    public ObservableCollection<ProductListPriceHistory> ProductListPriceHistories
    {
        get { if (_productListPriceHistories == null) ProductListPriceHistories = new ObservableCollection<ProductListPriceHistory>(); return _productListPriceHistories!; }
        private set
        {
            SetProperty(ref _productListPriceHistories, value);
            OnPropertyChanged(nameof(IsProductListPriceHistoriesLoaded));
        }
    }

    public bool IsProductListPriceHistoriesLoaded => _productListPriceHistories != null;

    internal void UnloadProductListPriceHistoriesStorage()
    {
        if (_productListPriceHistories == null) return;
        _productListPriceHistories = null;
        OnPropertyChanged(nameof(ProductListPriceHistories));
        OnPropertyChanged(nameof(IsProductListPriceHistoriesLoaded));
    }
}
}
