// <auto-generated>
//     Generated from ProductSubcategory.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class ProductSubcategory : ModelEntityBase
{
    [ObservableProperty]
    private int _productSubcategoryId;

    [ObservableProperty]
    private int _productCategoryId;

    [ObservableProperty]
    private string _name = null!;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public ProductCategory? ProductCategory => MainModel.Instance.ProductCategories.FirstOrDefault(x => x.ProductCategoryId == this.ProductCategoryId);

    private ObservableCollection<Product>? _products;
    public ObservableCollection<Product> Products
    {
        get { if (_products == null) Products = new LiveFilteredCollection<Product>(MainModel.Instance.Products, x => x.ProductSubcategoryId == this.ProductSubcategoryId, nameof(Product.ProductSubcategoryId)); return _products!; }
        private set => SetProperty(ref _products, value);
    }

    public static bool IsProductSubcategoriesLoaded => MainModel.Instance.IsProductSubcategoriesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsProductSubcategoriesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<ProductSubcategory>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.ProductSubcategoryId).ToHashSet();
        var collection = MainModel.Instance.ProductSubcategories;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.ProductSubcategoryId, freshItem.ProductSubcategoryId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].ProductSubcategoryId)) collection.RemoveAt(i);
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadProductSubcategoriesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(ProductSubcategory fresh)
    {
        ProductSubcategoryId = fresh.ProductSubcategoryId;
        ProductCategoryId = fresh.ProductCategoryId;
        Name = fresh.Name;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<ProductSubcategory>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<ProductSubcategory>? _productSubcategories;
    public ObservableCollection<ProductSubcategory> ProductSubcategories
    {
        get { if (_productSubcategories == null) ProductSubcategories = new ObservableCollection<ProductSubcategory>(); return _productSubcategories!; }
        private set
        {
            SetProperty(ref _productSubcategories, value);
            OnPropertyChanged(nameof(IsProductSubcategoriesLoaded));
        }
    }

    public bool IsProductSubcategoriesLoaded => _productSubcategories != null;

    internal void UnloadProductSubcategoriesStorage()
    {
        if (_productSubcategories == null) return;
        _productSubcategories = null;
        OnPropertyChanged(nameof(ProductSubcategories));
        OnPropertyChanged(nameof(IsProductSubcategoriesLoaded));
    }
}
}
