// <auto-generated>
//     Generated from ProductModelProductDescriptionCulture.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class ProductModelProductDescriptionCulture : ModelEntityBase
{
    [ObservableProperty]
    private int _productModelId;

    [ObservableProperty]
    private int _productDescriptionId;

    [ObservableProperty]
    private string _cultureId = null!;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public Culture? Culture => MainModel.Instance.Cultures.FirstOrDefault(x => x.CultureId == this.CultureId);

    public ProductDescription? ProductDescription => MainModel.Instance.ProductDescriptions.FirstOrDefault(x => x.ProductDescriptionId == this.ProductDescriptionId);

    public ProductModel? ProductModel => MainModel.Instance.ProductModels.FirstOrDefault(x => x.ProductModelId == this.ProductModelId);

    public static bool IsProductModelProductDescriptionCulturesLoaded => MainModel.Instance.IsProductModelProductDescriptionCulturesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsProductModelProductDescriptionCulturesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<ProductModelProductDescriptionCulture>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<ProductModelProductDescriptionCulture>)MainModel.Instance.ProductModelProductDescriptionCultures).ReplaceRange(fresh);

        MainModel.Instance.IsProductModelProductDescriptionCulturesLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadProductModelProductDescriptionCulturesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(ProductModelProductDescriptionCulture fresh)
    {
        ProductModelId = fresh.ProductModelId;
        ProductDescriptionId = fresh.ProductDescriptionId;
        CultureId = fresh.CultureId;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<ProductModelProductDescriptionCulture>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<ProductModelProductDescriptionCulture>? _productModelProductDescriptionCultures;
    public ObservableRangeCollection<ProductModelProductDescriptionCulture> ProductModelProductDescriptionCultures
    {
        get { if (_productModelProductDescriptionCultures == null) ProductModelProductDescriptionCultures = new ObservableRangeCollection<ProductModelProductDescriptionCulture>(); return _productModelProductDescriptionCultures!; }
        private set => SetProperty(ref _productModelProductDescriptionCultures, value);
    }

    private bool _isProductModelProductDescriptionCulturesLoaded;
    public bool IsProductModelProductDescriptionCulturesLoaded
    {
        get => _isProductModelProductDescriptionCulturesLoaded;
        internal set => SetProperty(ref _isProductModelProductDescriptionCulturesLoaded, value);
    }

    internal void UnloadProductModelProductDescriptionCulturesStorage()
    {
        if (_productModelProductDescriptionCultures == null) return;
        _productModelProductDescriptionCultures = null;
        OnPropertyChanged(nameof(ProductModelProductDescriptionCultures));

        IsProductModelProductDescriptionCulturesLoaded = false;
    }
}
}
