// <auto-generated>
//     Generated from PurchaseOrderDetail.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class PurchaseOrderDetail : ModelEntityBase
{
    [ObservableProperty]
    private int _purchaseOrderId;

    [ObservableProperty]
    private int _purchaseOrderDetailId;

    [ObservableProperty]
    private DateTime _dueDate;

    [ObservableProperty]
    private short _orderQty;

    [ObservableProperty]
    private int _productId;

    [ObservableProperty]
    private decimal _unitPrice;

    [ObservableProperty]
    private decimal _lineTotal;

    [ObservableProperty]
    private decimal _receivedQty;

    [ObservableProperty]
    private decimal _rejectedQty;

    [ObservableProperty]
    private decimal _stockedQty;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public Product? Product => MainModel.Instance.Products.FirstOrDefault(x => x.ProductId == this.ProductId);

    // TODO: could not auto-detect the foreign key for 'PurchaseOrder' -> PurchaseOrderHeader.
    // Add a manual implementation in a separate partial file, e.g.:
    // public PurchaseOrderHeader? PurchaseOrder => MainModel.Instance.PurchaseOrderHeaders.FirstOrDefault(x => /* match condition */);

    public static bool IsPurchaseOrderDetailsLoaded => MainModel.Instance.IsPurchaseOrderDetailsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsPurchaseOrderDetailsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<PurchaseOrderDetail>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.PurchaseOrderId).ToHashSet();
        var collection = MainModel.Instance.PurchaseOrderDetails;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.PurchaseOrderId, freshItem.PurchaseOrderId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].PurchaseOrderId)) collection.RemoveAt(i);

        // Explicitly flag the collection as loaded after a successful database query
        MainModel.Instance.IsPurchaseOrderDetailsLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadPurchaseOrderDetailsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(PurchaseOrderDetail fresh)
    {
        PurchaseOrderId = fresh.PurchaseOrderId;
        PurchaseOrderDetailId = fresh.PurchaseOrderDetailId;
        DueDate = fresh.DueDate;
        OrderQty = fresh.OrderQty;
        ProductId = fresh.ProductId;
        UnitPrice = fresh.UnitPrice;
        LineTotal = fresh.LineTotal;
        ReceivedQty = fresh.ReceivedQty;
        RejectedQty = fresh.RejectedQty;
        StockedQty = fresh.StockedQty;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<PurchaseOrderDetail>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<PurchaseOrderDetail>? _purchaseOrderDetails;
    public ObservableCollection<PurchaseOrderDetail> PurchaseOrderDetails
    {
        get { if (_purchaseOrderDetails == null) PurchaseOrderDetails = new ObservableCollection<PurchaseOrderDetail>(); return _purchaseOrderDetails!; }
        private set => SetProperty(ref _purchaseOrderDetails, value);
    }

    private bool _isPurchaseOrderDetailsLoaded;
    public bool IsPurchaseOrderDetailsLoaded
    {
        get => _isPurchaseOrderDetailsLoaded;
        internal set => SetProperty(ref _isPurchaseOrderDetailsLoaded, value);
    }

    internal void UnloadPurchaseOrderDetailsStorage()
    {
        if (_purchaseOrderDetails == null) return;
        _purchaseOrderDetails = null;
        OnPropertyChanged(nameof(PurchaseOrderDetails));

        // Reset the load state flag
        IsPurchaseOrderDetailsLoaded = false;
    }
}
}
