// <auto-generated>
//     Generated from PurchaseOrderHeader.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class PurchaseOrderHeader : ModelEntityBase
{
    [ObservableProperty]
    private int _purchaseOrderId;

    [ObservableProperty]
    private byte _revisionNumber;

    [ObservableProperty]
    private byte _status;

    [ObservableProperty]
    private int _employeeId;

    [ObservableProperty]
    private int _vendorId;

    [ObservableProperty]
    private int _shipMethodId;

    [ObservableProperty]
    private DateTime _orderDate;

    [ObservableProperty]
    private DateTime? _shipDate;

    [ObservableProperty]
    private decimal _subTotal;

    [ObservableProperty]
    private decimal _taxAmt;

    [ObservableProperty]
    private decimal _freight;

    [ObservableProperty]
    private decimal _totalDue;

    [ObservableProperty]
    private DateTime _modifiedDate;

    // TODO: could not auto-detect the foreign key for 'Employee' -> Employee.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Employee? Employee => MainModel.Instance.Employees.FirstOrDefault(x => /* match condition */);

    public ShipMethod? ShipMethod => MainModel.Instance.ShipMethods.FirstOrDefault(x => x.ShipMethodId == this.ShipMethodId);

    // TODO: could not auto-detect the foreign key for 'Vendor' -> Vendor.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Vendor? Vendor => MainModel.Instance.Vendors.FirstOrDefault(x => /* match condition */);

    private ObservableCollection<PurchaseOrderDetail>? _purchaseOrderDetails;
    public ObservableCollection<PurchaseOrderDetail> PurchaseOrderDetails
    {
        // TODO: could not auto-detect the foreign key linking PurchaseOrderDetail back to PurchaseOrderHeader.
        // Example: new LiveFilteredCollection<PurchaseOrderDetail>(MainModel.Instance.PurchaseOrderDetails, x => /* match condition */, nameof(PurchaseOrderDetail.SomeProperty))
        get { if (_purchaseOrderDetails == null) PurchaseOrderDetails = new ObservableCollection<PurchaseOrderDetail>(); return _purchaseOrderDetails!; }
        private set => SetProperty(ref _purchaseOrderDetails, value);
    }

    public static bool IsPurchaseOrderHeadersLoaded => MainModel.Instance.IsPurchaseOrderHeadersLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsPurchaseOrderHeadersLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<PurchaseOrderHeader>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.PurchaseOrderId).ToHashSet();
        var collection = MainModel.Instance.PurchaseOrderHeaders;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.PurchaseOrderId, freshItem.PurchaseOrderId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].PurchaseOrderId)) collection.RemoveAt(i);
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadPurchaseOrderHeadersStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(PurchaseOrderHeader fresh)
    {
        PurchaseOrderId = fresh.PurchaseOrderId;
        RevisionNumber = fresh.RevisionNumber;
        Status = fresh.Status;
        EmployeeId = fresh.EmployeeId;
        VendorId = fresh.VendorId;
        ShipMethodId = fresh.ShipMethodId;
        OrderDate = fresh.OrderDate;
        ShipDate = fresh.ShipDate;
        SubTotal = fresh.SubTotal;
        TaxAmt = fresh.TaxAmt;
        Freight = fresh.Freight;
        TotalDue = fresh.TotalDue;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<PurchaseOrderHeader>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<PurchaseOrderHeader>? _purchaseOrderHeaders;
    public ObservableCollection<PurchaseOrderHeader> PurchaseOrderHeaders
    {
        get { if (_purchaseOrderHeaders == null) PurchaseOrderHeaders = new ObservableCollection<PurchaseOrderHeader>(); return _purchaseOrderHeaders!; }
        private set
        {
            SetProperty(ref _purchaseOrderHeaders, value);
            OnPropertyChanged(nameof(IsPurchaseOrderHeadersLoaded));
        }
    }

    public bool IsPurchaseOrderHeadersLoaded => _purchaseOrderHeaders != null;

    internal void UnloadPurchaseOrderHeadersStorage()
    {
        if (_purchaseOrderHeaders == null) return;
        _purchaseOrderHeaders = null;
        OnPropertyChanged(nameof(PurchaseOrderHeaders));
        OnPropertyChanged(nameof(IsPurchaseOrderHeadersLoaded));
    }
}
}
