// <auto-generated>
//     Generated from SalesTerritory.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class SalesTerritory : ModelEntityBase
{
    [ObservableProperty]
    private int _territoryId;

    [ObservableProperty]
    private string _name = null!;

    [ObservableProperty]
    private string _countryRegionCode = null!;

    [ObservableProperty]
    private string _group = null!;

    [ObservableProperty]
    private decimal _salesYtd;

    [ObservableProperty]
    private decimal _salesLastYear;

    [ObservableProperty]
    private decimal _costYtd;

    [ObservableProperty]
    private decimal _costLastYear;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public CountryRegion? CountryRegionCodeNavigation => MainModel.Instance.CountryRegions.FirstOrDefault(x => x.CountryRegionCode == this.CountryRegionCode);

    private ObservableCollection<Customer>? _customers;
    public ObservableCollection<Customer> Customers
    {
        // TODO: could not auto-detect the foreign key linking Customer back to SalesTerritory.
        // Example: new LiveFilteredCollection<Customer>(MainModel.Instance.Customers, x => /* match condition */, nameof(Customer.SomeProperty))
        get { if (_customers == null) Customers = new ObservableCollection<Customer>(); return _customers!; }
        private set => SetProperty(ref _customers, value);
    }

    private ObservableCollection<SalesOrderHeader>? _salesOrderHeaders;
    public ObservableCollection<SalesOrderHeader> SalesOrderHeaders
    {
        // TODO: could not auto-detect the foreign key linking SalesOrderHeader back to SalesTerritory.
        // Example: new LiveFilteredCollection<SalesOrderHeader>(MainModel.Instance.SalesOrderHeaders, x => /* match condition */, nameof(SalesOrderHeader.SomeProperty))
        get { if (_salesOrderHeaders == null) SalesOrderHeaders = new ObservableCollection<SalesOrderHeader>(); return _salesOrderHeaders!; }
        private set => SetProperty(ref _salesOrderHeaders, value);
    }

    private ObservableCollection<SalesPerson>? _salesPeople;
    public ObservableCollection<SalesPerson> SalesPeople
    {
        // TODO: could not auto-detect the foreign key linking SalesPerson back to SalesTerritory.
        // Example: new LiveFilteredCollection<SalesPerson>(MainModel.Instance.SalesPersons, x => /* match condition */, nameof(SalesPerson.SomeProperty))
        get { if (_salesPeople == null) SalesPeople = new ObservableCollection<SalesPerson>(); return _salesPeople!; }
        private set => SetProperty(ref _salesPeople, value);
    }

    private ObservableCollection<SalesTerritoryHistory>? _salesTerritoryHistories;
    public ObservableCollection<SalesTerritoryHistory> SalesTerritoryHistories
    {
        // TODO: could not auto-detect the foreign key linking SalesTerritoryHistory back to SalesTerritory.
        // Example: new LiveFilteredCollection<SalesTerritoryHistory>(MainModel.Instance.SalesTerritoryHistories, x => /* match condition */, nameof(SalesTerritoryHistory.SomeProperty))
        get { if (_salesTerritoryHistories == null) SalesTerritoryHistories = new ObservableCollection<SalesTerritoryHistory>(); return _salesTerritoryHistories!; }
        private set => SetProperty(ref _salesTerritoryHistories, value);
    }

    private ObservableCollection<StateProvince>? _stateProvinces;
    public ObservableCollection<StateProvince> StateProvinces
    {
        // TODO: could not auto-detect the foreign key linking StateProvince back to SalesTerritory.
        // Example: new LiveFilteredCollection<StateProvince>(MainModel.Instance.StateProvinces, x => /* match condition */, nameof(StateProvince.SomeProperty))
        get { if (_stateProvinces == null) StateProvinces = new ObservableCollection<StateProvince>(); return _stateProvinces!; }
        private set => SetProperty(ref _stateProvinces, value);
    }

    public static bool IsSalesTerritoriesLoaded => MainModel.Instance.IsSalesTerritoriesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsSalesTerritoriesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<SalesTerritory>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.TerritoryId).ToHashSet();
        var collection = MainModel.Instance.SalesTerritories;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.TerritoryId, freshItem.TerritoryId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].TerritoryId)) collection.RemoveAt(i);

        // Explicitly flag the collection as loaded after a successful database query
        MainModel.Instance.IsSalesTerritoriesLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadSalesTerritoriesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(SalesTerritory fresh)
    {
        TerritoryId = fresh.TerritoryId;
        Name = fresh.Name;
        CountryRegionCode = fresh.CountryRegionCode;
        Group = fresh.Group;
        SalesYtd = fresh.SalesYtd;
        SalesLastYear = fresh.SalesLastYear;
        CostYtd = fresh.CostYtd;
        CostLastYear = fresh.CostLastYear;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<SalesTerritory>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<SalesTerritory>? _salesTerritories;
    public ObservableCollection<SalesTerritory> SalesTerritories
    {
        get { if (_salesTerritories == null) SalesTerritories = new ObservableCollection<SalesTerritory>(); return _salesTerritories!; }
        private set => SetProperty(ref _salesTerritories, value);
    }

    private bool _isSalesTerritoriesLoaded;
    public bool IsSalesTerritoriesLoaded
    {
        get => _isSalesTerritoriesLoaded;
        internal set => SetProperty(ref _isSalesTerritoriesLoaded, value);
    }

    internal void UnloadSalesTerritoriesStorage()
    {
        if (_salesTerritories == null) return;
        _salesTerritories = null;
        OnPropertyChanged(nameof(SalesTerritories));

        // Reset the load state flag
        IsSalesTerritoriesLoaded = false;
    }
}
}
