// <auto-generated>
//     Generated from SalesOrderHeader.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class SalesOrderHeader : ModelEntityBase
{
    [ObservableProperty]
    private int _salesOrderId;

    [ObservableProperty]
    private byte _revisionNumber;

    [ObservableProperty]
    private DateTime _orderDate;

    [ObservableProperty]
    private DateTime _dueDate;

    [ObservableProperty]
    private DateTime? _shipDate;

    [ObservableProperty]
    private byte _status;

    [ObservableProperty]
    private bool _onlineOrderFlag;

    [ObservableProperty]
    private string _salesOrderNumber = null!;

    [ObservableProperty]
    private string _purchaseOrderNumber = null!;

    [ObservableProperty]
    private string _accountNumber = null!;

    [ObservableProperty]
    private int _customerId;

    [ObservableProperty]
    private int? _salesPersonId;

    [ObservableProperty]
    private int? _territoryId;

    [ObservableProperty]
    private int _billToAddressId;

    [ObservableProperty]
    private int _shipToAddressId;

    [ObservableProperty]
    private int _shipMethodId;

    [ObservableProperty]
    private int? _creditCardId;

    [ObservableProperty]
    private string _creditCardApprovalCode = null!;

    [ObservableProperty]
    private int? _currencyRateId;

    [ObservableProperty]
    private decimal _subTotal;

    [ObservableProperty]
    private decimal _taxAmt;

    [ObservableProperty]
    private decimal _freight;

    [ObservableProperty]
    private decimal _totalDue;

    [ObservableProperty]
    private string _comment = null!;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    // TODO: could not auto-detect the foreign key for 'BillToAddress' -> Address.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Address? BillToAddress => MainModel.Instance.Addresses.FirstOrDefault(x => /* match condition */);

    public CreditCard? CreditCard => MainModel.Instance.CreditCards.FirstOrDefault(x => x.CreditCardId == this.CreditCardId);

    public CurrencyRate? CurrencyRate => MainModel.Instance.CurrencyRates.FirstOrDefault(x => x.CurrencyRateId == this.CurrencyRateId);

    public Customer? Customer => MainModel.Instance.Customers.FirstOrDefault(x => x.CustomerId == this.CustomerId);

    // TODO: could not auto-detect the foreign key for 'SalesPerson' -> SalesPerson.
    // Add a manual implementation in a separate partial file, e.g.:
    // public SalesPerson? SalesPerson => MainModel.Instance.SalesPersons.FirstOrDefault(x => /* match condition */);

    public ShipMethod? ShipMethod => MainModel.Instance.ShipMethods.FirstOrDefault(x => x.ShipMethodId == this.ShipMethodId);

    // TODO: could not auto-detect the foreign key for 'ShipToAddress' -> Address.
    // Add a manual implementation in a separate partial file, e.g.:
    // public Address? ShipToAddress => MainModel.Instance.Addresses.FirstOrDefault(x => /* match condition */);

    // TODO: could not auto-detect the foreign key for 'Territory' -> SalesTerritory.
    // Add a manual implementation in a separate partial file, e.g.:
    // public SalesTerritory? Territory => MainModel.Instance.SalesTerritories.FirstOrDefault(x => /* match condition */);

    private ObservableCollection<SalesOrderDetail>? _salesOrderDetails;
    public ObservableCollection<SalesOrderDetail> SalesOrderDetails
    {
        // TODO: could not auto-detect the foreign key linking SalesOrderDetail back to SalesOrderHeader.
        // Example: new LiveFilteredCollection<SalesOrderDetail>(MainModel.Instance.SalesOrderDetails, x => /* match condition */, nameof(SalesOrderDetail.SomeProperty))
        get { if (_salesOrderDetails == null) SalesOrderDetails = new ObservableCollection<SalesOrderDetail>(); return _salesOrderDetails!; }
        private set => SetProperty(ref _salesOrderDetails, value);
    }

    private ObservableCollection<SalesOrderHeaderSalesReason>? _salesOrderHeaderSalesReasons;
    public ObservableCollection<SalesOrderHeaderSalesReason> SalesOrderHeaderSalesReasons
    {
        // TODO: could not auto-detect the foreign key linking SalesOrderHeaderSalesReason back to SalesOrderHeader.
        // Example: new LiveFilteredCollection<SalesOrderHeaderSalesReason>(MainModel.Instance.SalesOrderHeaderSalesReasons, x => /* match condition */, nameof(SalesOrderHeaderSalesReason.SomeProperty))
        get { if (_salesOrderHeaderSalesReasons == null) SalesOrderHeaderSalesReasons = new ObservableCollection<SalesOrderHeaderSalesReason>(); return _salesOrderHeaderSalesReasons!; }
        private set => SetProperty(ref _salesOrderHeaderSalesReasons, value);
    }

    public static bool IsSalesOrderHeadersLoaded => MainModel.Instance.IsSalesOrderHeadersLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsSalesOrderHeadersLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<SalesOrderHeader>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.SalesOrderId).ToHashSet();
        var collection = MainModel.Instance.SalesOrderHeaders;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.SalesOrderId, freshItem.SalesOrderId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].SalesOrderId)) collection.RemoveAt(i);
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadSalesOrderHeadersStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(SalesOrderHeader fresh)
    {
        SalesOrderId = fresh.SalesOrderId;
        RevisionNumber = fresh.RevisionNumber;
        OrderDate = fresh.OrderDate;
        DueDate = fresh.DueDate;
        ShipDate = fresh.ShipDate;
        Status = fresh.Status;
        OnlineOrderFlag = fresh.OnlineOrderFlag;
        SalesOrderNumber = fresh.SalesOrderNumber;
        PurchaseOrderNumber = fresh.PurchaseOrderNumber;
        AccountNumber = fresh.AccountNumber;
        CustomerId = fresh.CustomerId;
        SalesPersonId = fresh.SalesPersonId;
        TerritoryId = fresh.TerritoryId;
        BillToAddressId = fresh.BillToAddressId;
        ShipToAddressId = fresh.ShipToAddressId;
        ShipMethodId = fresh.ShipMethodId;
        CreditCardId = fresh.CreditCardId;
        CreditCardApprovalCode = fresh.CreditCardApprovalCode;
        CurrencyRateId = fresh.CurrencyRateId;
        SubTotal = fresh.SubTotal;
        TaxAmt = fresh.TaxAmt;
        Freight = fresh.Freight;
        TotalDue = fresh.TotalDue;
        Comment = fresh.Comment;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<SalesOrderHeader>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<SalesOrderHeader>? _salesOrderHeaders;
    public ObservableCollection<SalesOrderHeader> SalesOrderHeaders
    {
        get { if (_salesOrderHeaders == null) SalesOrderHeaders = new ObservableCollection<SalesOrderHeader>(); return _salesOrderHeaders!; }
        private set
        {
            SetProperty(ref _salesOrderHeaders, value);
            OnPropertyChanged(nameof(IsSalesOrderHeadersLoaded));
        }
    }

    public bool IsSalesOrderHeadersLoaded => _salesOrderHeaders != null;

    internal void UnloadSalesOrderHeadersStorage()
    {
        if (_salesOrderHeaders == null) return;
        _salesOrderHeaders = null;
        OnPropertyChanged(nameof(SalesOrderHeaders));
        OnPropertyChanged(nameof(IsSalesOrderHeadersLoaded));
    }
}
}
