// <auto-generated>
//     Generated from SalesTaxRate.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class SalesTaxRate : ModelEntityBase
{
    [ObservableProperty]
    private int _salesTaxRateId;

    [ObservableProperty]
    private int _stateProvinceId;

    [ObservableProperty]
    private byte _taxType;

    [ObservableProperty]
    private decimal _taxRate;

    [ObservableProperty]
    private string _name = null!;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public StateProvince? StateProvince => MainModel.Instance.StateProvinces.FirstOrDefault(x => x.StateProvinceId == this.StateProvinceId);

    public static bool IsSalesTaxRatesLoaded => MainModel.Instance.IsSalesTaxRatesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsSalesTaxRatesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<SalesTaxRate>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<SalesTaxRate>)MainModel.Instance.SalesTaxRates).ReplaceRange(fresh);

        MainModel.Instance.IsSalesTaxRatesLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadSalesTaxRatesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(SalesTaxRate fresh)
    {
        SalesTaxRateId = fresh.SalesTaxRateId;
        StateProvinceId = fresh.StateProvinceId;
        TaxType = fresh.TaxType;
        TaxRate = fresh.TaxRate;
        Name = fresh.Name;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<SalesTaxRate>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<SalesTaxRate>? _salesTaxRates;
    public ObservableRangeCollection<SalesTaxRate> SalesTaxRates
    {
        get { if (_salesTaxRates == null) SalesTaxRates = new ObservableRangeCollection<SalesTaxRate>(); return _salesTaxRates!; }
        private set => SetProperty(ref _salesTaxRates, value);
    }

    private bool _isSalesTaxRatesLoaded;
    public bool IsSalesTaxRatesLoaded
    {
        get => _isSalesTaxRatesLoaded;
        internal set => SetProperty(ref _isSalesTaxRatesLoaded, value);
    }

    internal void UnloadSalesTaxRatesStorage()
    {
        if (_salesTaxRates == null) return;
        _salesTaxRates = null;
        OnPropertyChanged(nameof(SalesTaxRates));

        IsSalesTaxRatesLoaded = false;
    }
}
}
