// <auto-generated>
//     Generated from SalesTaxRate.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class SalesTaxRate : ModelEntityBase
{
    [ObservableProperty]
    private int _salesTaxRateId;

    [ObservableProperty]
    private int _stateProvinceId;

    [ObservableProperty]
    private byte _taxType;

    [ObservableProperty]
    private decimal _taxRate;

    [ObservableProperty]
    private string _name = null!;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public StateProvince? StateProvince => MainModel.Instance.StateProvinces.FirstOrDefault(x => x.StateProvinceId == this.StateProvinceId);

    public static bool IsSalesTaxRatesLoaded => MainModel.Instance.IsSalesTaxRatesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsSalesTaxRatesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<SalesTaxRate>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.SalesTaxRateId).ToHashSet();
        var collection = MainModel.Instance.SalesTaxRates;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.SalesTaxRateId, freshItem.SalesTaxRateId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].SalesTaxRateId)) collection.RemoveAt(i);

        // Explicitly flag the collection as loaded after a successful database query
        MainModel.Instance.IsSalesTaxRatesLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadSalesTaxRatesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(SalesTaxRate fresh)
    {
        SalesTaxRateId = fresh.SalesTaxRateId;
        StateProvinceId = fresh.StateProvinceId;
        TaxType = fresh.TaxType;
        TaxRate = fresh.TaxRate;
        Name = fresh.Name;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<SalesTaxRate>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<SalesTaxRate>? _salesTaxRates;
    public ObservableCollection<SalesTaxRate> SalesTaxRates
    {
        get { if (_salesTaxRates == null) SalesTaxRates = new ObservableCollection<SalesTaxRate>(); return _salesTaxRates!; }
        private set => SetProperty(ref _salesTaxRates, value);
    }

    private bool _isSalesTaxRatesLoaded;
    public bool IsSalesTaxRatesLoaded
    {
        get => _isSalesTaxRatesLoaded;
        internal set => SetProperty(ref _isSalesTaxRatesLoaded, value);
    }

    internal void UnloadSalesTaxRatesStorage()
    {
        if (_salesTaxRates == null) return;
        _salesTaxRates = null;
        OnPropertyChanged(nameof(SalesTaxRates));

        // Reset the load state flag
        IsSalesTaxRatesLoaded = false;
    }
}
}
