// <auto-generated>
//     Generated from SalesOrderDetail.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class SalesOrderDetail : ModelEntityBase
{
    public static string SqlSchema => "Sales";
    public static string SqlTableName => "SalesOrderDetail";
    [ObservableProperty]
    private int _salesOrderId;

    [ObservableProperty]
    private int _salesOrderDetailId;

    [ObservableProperty]
    private string _carrierTrackingNumber = null!;

    [ObservableProperty]
    private short _orderQty;

    [ObservableProperty]
    private int _productId;

    [ObservableProperty]
    private int _specialOfferId;

    [ObservableProperty]
    private decimal _unitPrice;

    [ObservableProperty]
    private decimal _unitPriceDiscount;

    [ObservableProperty]
    private decimal _lineTotal;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    // TODO: could not auto-detect the foreign key for 'SalesOrder' -> SalesOrderHeader.
    // Add a manual implementation in a separate partial file, e.g.:
    // public SalesOrderHeader? SalesOrder => MainModel.Instance.SalesOrderHeaders.FirstOrDefault(x => /* match condition */);

    // TODO: could not auto-detect the foreign key for 'SpecialOfferProduct' -> SpecialOfferProduct.
    // Add a manual implementation in a separate partial file, e.g.:
    // public SpecialOfferProduct? SpecialOfferProduct => MainModel.Instance.SpecialOfferProducts.FirstOrDefault(x => /* match condition */);

    public static bool IsSalesOrderDetailsLoaded => MainModel.Instance.IsSalesOrderDetailsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsSalesOrderDetailsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<SalesOrderDetail>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<SalesOrderDetail>)MainModel.Instance.SalesOrderDetails).ReplaceRange(fresh);

        MainModel.Instance.IsSalesOrderDetailsLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadSalesOrderDetailsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(SalesOrderDetail fresh)
    {
        SalesOrderId = fresh.SalesOrderId;
        SalesOrderDetailId = fresh.SalesOrderDetailId;
        CarrierTrackingNumber = fresh.CarrierTrackingNumber;
        OrderQty = fresh.OrderQty;
        ProductId = fresh.ProductId;
        SpecialOfferId = fresh.SpecialOfferId;
        UnitPrice = fresh.UnitPrice;
        UnitPriceDiscount = fresh.UnitPriceDiscount;
        LineTotal = fresh.LineTotal;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<SalesOrderDetail>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<SalesOrderDetail>? _salesOrderDetails;
    public ObservableRangeCollection<SalesOrderDetail> SalesOrderDetails
    {
        get { if (_salesOrderDetails == null) SalesOrderDetails = new ObservableRangeCollection<SalesOrderDetail>(); return _salesOrderDetails!; }
        private set => SetProperty(ref _salesOrderDetails, value);
    }

    private bool _isSalesOrderDetailsLoaded;
    public bool IsSalesOrderDetailsLoaded
    {
        get => _isSalesOrderDetailsLoaded;
        internal set => SetProperty(ref _isSalesOrderDetailsLoaded, value);
    }

    internal void UnloadSalesOrderDetailsStorage()
    {
        if (_salesOrderDetails == null) return;
        _salesOrderDetails = null;
        OnPropertyChanged(nameof(SalesOrderDetails));

        IsSalesOrderDetailsLoaded = false;
    }
}
}
