// <auto-generated>
//     Generated from SalesReason.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class SalesReason : ModelEntityBase
{
    [ObservableProperty]
    private int _salesReasonId;

    [ObservableProperty]
    private string _name = null!;

    [ObservableProperty]
    private string _reasonType = null!;

    [ObservableProperty]
    private DateTime _modifiedDate;

    private ObservableCollection<SalesOrderHeaderSalesReason>? _salesOrderHeaderSalesReasons;
    public ObservableCollection<SalesOrderHeaderSalesReason> SalesOrderHeaderSalesReasons
    {
        get { if (_salesOrderHeaderSalesReasons == null) SalesOrderHeaderSalesReasons = new LiveFilteredCollection<SalesOrderHeaderSalesReason>(MainModel.Instance.SalesOrderHeaderSalesReasons, x => x.SalesReasonId == this.SalesReasonId, nameof(SalesOrderHeaderSalesReason.SalesReasonId)); return _salesOrderHeaderSalesReasons!; }
        private set => SetProperty(ref _salesOrderHeaderSalesReasons, value);
    }

    public static bool IsSalesReasonsLoaded => MainModel.Instance.IsSalesReasonsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsSalesReasonsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<SalesReason>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.SalesReasonId).ToHashSet();
        var collection = MainModel.Instance.SalesReasons;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.SalesReasonId, freshItem.SalesReasonId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].SalesReasonId)) collection.RemoveAt(i);

        // Explicitly flag the collection as loaded after a successful database query
        MainModel.Instance.IsSalesReasonsLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadSalesReasonsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(SalesReason fresh)
    {
        SalesReasonId = fresh.SalesReasonId;
        Name = fresh.Name;
        ReasonType = fresh.ReasonType;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<SalesReason>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<SalesReason>? _salesReasons;
    public ObservableCollection<SalesReason> SalesReasons
    {
        get { if (_salesReasons == null) SalesReasons = new ObservableCollection<SalesReason>(); return _salesReasons!; }
        private set => SetProperty(ref _salesReasons, value);
    }

    private bool _isSalesReasonsLoaded;
    public bool IsSalesReasonsLoaded
    {
        get => _isSalesReasonsLoaded;
        internal set => SetProperty(ref _isSalesReasonsLoaded, value);
    }

    internal void UnloadSalesReasonsStorage()
    {
        if (_salesReasons == null) return;
        _salesReasons = null;
        OnPropertyChanged(nameof(SalesReasons));

        // Reset the load state flag
        IsSalesReasonsLoaded = false;
    }
}
}
