// <auto-generated>
//     Generated from ShipMethod.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class ShipMethod : ModelEntityBase
{
    [ObservableProperty]
    private int _shipMethodId;

    [ObservableProperty]
    private string _name = null!;

    [ObservableProperty]
    private decimal _shipBase;

    [ObservableProperty]
    private decimal _shipRate;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    private ObservableCollection<PurchaseOrderHeader>? _purchaseOrderHeaders;
    public ObservableCollection<PurchaseOrderHeader> PurchaseOrderHeaders
    {
        get { if (_purchaseOrderHeaders == null) PurchaseOrderHeaders = new LiveFilteredCollection<PurchaseOrderHeader>(MainModel.Instance.PurchaseOrderHeaders, x => x.ShipMethodId == this.ShipMethodId, nameof(PurchaseOrderHeader.ShipMethodId)); return _purchaseOrderHeaders!; }
        private set => SetProperty(ref _purchaseOrderHeaders, value);
    }

    private ObservableCollection<SalesOrderHeader>? _salesOrderHeaders;
    public ObservableCollection<SalesOrderHeader> SalesOrderHeaders
    {
        get { if (_salesOrderHeaders == null) SalesOrderHeaders = new LiveFilteredCollection<SalesOrderHeader>(MainModel.Instance.SalesOrderHeaders, x => x.ShipMethodId == this.ShipMethodId, nameof(SalesOrderHeader.ShipMethodId)); return _salesOrderHeaders!; }
        private set => SetProperty(ref _salesOrderHeaders, value);
    }

    public static bool IsShipMethodsLoaded => MainModel.Instance.IsShipMethodsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsShipMethodsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<ShipMethod>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<ShipMethod>)MainModel.Instance.ShipMethods).ReplaceRange(fresh);

        MainModel.Instance.IsShipMethodsLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadShipMethodsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(ShipMethod fresh)
    {
        ShipMethodId = fresh.ShipMethodId;
        Name = fresh.Name;
        ShipBase = fresh.ShipBase;
        ShipRate = fresh.ShipRate;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<ShipMethod>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<ShipMethod>? _shipMethods;
    public ObservableRangeCollection<ShipMethod> ShipMethods
    {
        get { if (_shipMethods == null) ShipMethods = new ObservableRangeCollection<ShipMethod>(); return _shipMethods!; }
        private set => SetProperty(ref _shipMethods, value);
    }

    private bool _isShipMethodsLoaded;
    public bool IsShipMethodsLoaded
    {
        get => _isShipMethodsLoaded;
        internal set => SetProperty(ref _isShipMethodsLoaded, value);
    }

    internal void UnloadShipMethodsStorage()
    {
        if (_shipMethods == null) return;
        _shipMethods = null;
        OnPropertyChanged(nameof(ShipMethods));

        IsShipMethodsLoaded = false;
    }
}
}
