// <auto-generated>
//     Generated from ShoppingCartItem.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class ShoppingCartItem : ModelEntityBase
{
    [ObservableProperty]
    private int _shoppingCartItemId;

    [ObservableProperty]
    private string _shoppingCartId = null!;

    [ObservableProperty]
    private int _quantity;

    [ObservableProperty]
    private int _productId;

    [ObservableProperty]
    private DateTime _dateCreated;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public Product? Product => MainModel.Instance.Products.FirstOrDefault(x => x.ProductId == this.ProductId);

    public static bool IsShoppingCartItemsLoaded => MainModel.Instance.IsShoppingCartItemsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsShoppingCartItemsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<ShoppingCartItem>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.ShoppingCartItemId).ToHashSet();
        var collection = MainModel.Instance.ShoppingCartItems;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.ShoppingCartItemId, freshItem.ShoppingCartItemId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].ShoppingCartItemId)) collection.RemoveAt(i);

        // Explicitly flag the collection as loaded after a successful database query
        MainModel.Instance.IsShoppingCartItemsLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadShoppingCartItemsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(ShoppingCartItem fresh)
    {
        ShoppingCartItemId = fresh.ShoppingCartItemId;
        ShoppingCartId = fresh.ShoppingCartId;
        Quantity = fresh.Quantity;
        ProductId = fresh.ProductId;
        DateCreated = fresh.DateCreated;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<ShoppingCartItem>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<ShoppingCartItem>? _shoppingCartItems;
    public ObservableCollection<ShoppingCartItem> ShoppingCartItems
    {
        get { if (_shoppingCartItems == null) ShoppingCartItems = new ObservableCollection<ShoppingCartItem>(); return _shoppingCartItems!; }
        private set => SetProperty(ref _shoppingCartItems, value);
    }

    private bool _isShoppingCartItemsLoaded;
    public bool IsShoppingCartItemsLoaded
    {
        get => _isShoppingCartItemsLoaded;
        internal set => SetProperty(ref _isShoppingCartItemsLoaded, value);
    }

    internal void UnloadShoppingCartItemsStorage()
    {
        if (_shoppingCartItems == null) return;
        _shoppingCartItems = null;
        OnPropertyChanged(nameof(ShoppingCartItems));

        // Reset the load state flag
        IsShoppingCartItemsLoaded = false;
    }
}
}
