// <auto-generated>
//     Generated from SpecialOffer.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class SpecialOffer : ModelEntityBase
{
    [ObservableProperty]
    private int _specialOfferId;

    [ObservableProperty]
    private string _description = null!;

    [ObservableProperty]
    private decimal _discountPct;

    [ObservableProperty]
    private string _type = null!;

    [ObservableProperty]
    private string _category = null!;

    [ObservableProperty]
    private DateTime _startDate;

    [ObservableProperty]
    private DateTime _endDate;

    [ObservableProperty]
    private int _minQty;

    [ObservableProperty]
    private int? _maxQty;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    private ObservableCollection<SpecialOfferProduct>? _specialOfferProducts;
    public ObservableCollection<SpecialOfferProduct> SpecialOfferProducts
    {
        get { if (_specialOfferProducts == null) SpecialOfferProducts = new LiveFilteredCollection<SpecialOfferProduct>(MainModel.Instance.SpecialOfferProducts, x => x.SpecialOfferId == this.SpecialOfferId, nameof(SpecialOfferProduct.SpecialOfferId)); return _specialOfferProducts!; }
        private set => SetProperty(ref _specialOfferProducts, value);
    }

    public static bool IsSpecialOffersLoaded => MainModel.Instance.IsSpecialOffersLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsSpecialOffersLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<SpecialOffer>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<SpecialOffer>)MainModel.Instance.SpecialOffers).ReplaceRange(fresh);

        MainModel.Instance.IsSpecialOffersLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadSpecialOffersStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(SpecialOffer fresh)
    {
        SpecialOfferId = fresh.SpecialOfferId;
        Description = fresh.Description;
        DiscountPct = fresh.DiscountPct;
        Type = fresh.Type;
        Category = fresh.Category;
        StartDate = fresh.StartDate;
        EndDate = fresh.EndDate;
        MinQty = fresh.MinQty;
        MaxQty = fresh.MaxQty;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<SpecialOffer>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<SpecialOffer>? _specialOffers;
    public ObservableRangeCollection<SpecialOffer> SpecialOffers
    {
        get { if (_specialOffers == null) SpecialOffers = new ObservableRangeCollection<SpecialOffer>(); return _specialOffers!; }
        private set => SetProperty(ref _specialOffers, value);
    }

    private bool _isSpecialOffersLoaded;
    public bool IsSpecialOffersLoaded
    {
        get => _isSpecialOffersLoaded;
        internal set => SetProperty(ref _isSpecialOffersLoaded, value);
    }

    internal void UnloadSpecialOffersStorage()
    {
        if (_specialOffers == null) return;
        _specialOffers = null;
        OnPropertyChanged(nameof(SpecialOffers));

        IsSpecialOffersLoaded = false;
    }
}
}
