// <auto-generated>
//     Generated from StateProvince.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class StateProvince : ModelEntityBase
{
    [ObservableProperty]
    private int _stateProvinceId;

    [ObservableProperty]
    private string _stateProvinceCode = null!;

    [ObservableProperty]
    private string _countryRegionCode = null!;

    [ObservableProperty]
    private bool _isOnlyStateProvinceFlag;

    [ObservableProperty]
    private string _name = null!;

    [ObservableProperty]
    private int _territoryId;

    [ObservableProperty]
    private Guid _rowguid;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public CountryRegion? CountryRegionCodeNavigation => MainModel.Instance.CountryRegions.FirstOrDefault(x => x.CountryRegionCode == this.CountryRegionCode);

    // TODO: could not auto-detect the foreign key for 'Territory' -> SalesTerritory.
    // Add a manual implementation in a separate partial file, e.g.:
    // public SalesTerritory? Territory => MainModel.Instance.SalesTerritories.FirstOrDefault(x => /* match condition */);

    private ObservableCollection<Address>? _addresses;
    public ObservableCollection<Address> Addresses
    {
        get { if (_addresses == null) Addresses = new LiveFilteredCollection<Address>(MainModel.Instance.Addresses, x => x.StateProvinceId == this.StateProvinceId, nameof(Address.StateProvinceId)); return _addresses!; }
        private set => SetProperty(ref _addresses, value);
    }

    private ObservableCollection<SalesTaxRate>? _salesTaxRates;
    public ObservableCollection<SalesTaxRate> SalesTaxRates
    {
        get { if (_salesTaxRates == null) SalesTaxRates = new LiveFilteredCollection<SalesTaxRate>(MainModel.Instance.SalesTaxRates, x => x.StateProvinceId == this.StateProvinceId, nameof(SalesTaxRate.StateProvinceId)); return _salesTaxRates!; }
        private set => SetProperty(ref _salesTaxRates, value);
    }

    public static bool IsStateProvincesLoaded => MainModel.Instance.IsStateProvincesLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsStateProvincesLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<StateProvince>>();
        var fresh = await loader.LoadAllAsync(ct);

        ((ObservableRangeCollection<StateProvince>)MainModel.Instance.StateProvinces).ReplaceRange(fresh);

        MainModel.Instance.IsStateProvincesLoaded = true;
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadStateProvincesStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(StateProvince fresh)
    {
        StateProvinceId = fresh.StateProvinceId;
        StateProvinceCode = fresh.StateProvinceCode;
        CountryRegionCode = fresh.CountryRegionCode;
        IsOnlyStateProvinceFlag = fresh.IsOnlyStateProvinceFlag;
        Name = fresh.Name;
        TerritoryId = fresh.TerritoryId;
        Rowguid = fresh.Rowguid;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<StateProvince>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableRangeCollection<StateProvince>? _stateProvinces;
    public ObservableRangeCollection<StateProvince> StateProvinces
    {
        get { if (_stateProvinces == null) StateProvinces = new ObservableRangeCollection<StateProvince>(); return _stateProvinces!; }
        private set => SetProperty(ref _stateProvinces, value);
    }

    private bool _isStateProvincesLoaded;
    public bool IsStateProvincesLoaded
    {
        get => _isStateProvincesLoaded;
        internal set => SetProperty(ref _isStateProvincesLoaded, value);
    }

    internal void UnloadStateProvincesStorage()
    {
        if (_stateProvinces == null) return;
        _stateProvinces = null;
        OnPropertyChanged(nameof(StateProvinces));

        IsStateProvincesLoaded = false;
    }
}
}
