// <auto-generated>
//     Generated from Vendor.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class Vendor : ModelEntityBase
{
    [ObservableProperty]
    private int _businessEntityId;

    [ObservableProperty]
    private string _accountNumber = null!;

    [ObservableProperty]
    private string _name = null!;

    [ObservableProperty]
    private byte _creditRating;

    [ObservableProperty]
    private bool _preferredVendorStatus;

    [ObservableProperty]
    private bool _activeFlag;

    [ObservableProperty]
    private string _purchasingWebServiceUrl = null!;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public BusinessEntity? BusinessEntity => MainModel.Instance.BusinessEntities.FirstOrDefault(x => x.BusinessEntityId == this.BusinessEntityId);

    private ObservableCollection<ProductVendor>? _productVendors;
    public ObservableCollection<ProductVendor> ProductVendors
    {
        // TODO: could not auto-detect the foreign key linking ProductVendor back to Vendor.
        // Example: new LiveFilteredCollection<ProductVendor>(MainModel.Instance.ProductVendors, x => /* match condition */, nameof(ProductVendor.SomeProperty))
        get { if (_productVendors == null) ProductVendors = new ObservableCollection<ProductVendor>(); return _productVendors!; }
        private set => SetProperty(ref _productVendors, value);
    }

    private ObservableCollection<PurchaseOrderHeader>? _purchaseOrderHeaders;
    public ObservableCollection<PurchaseOrderHeader> PurchaseOrderHeaders
    {
        // TODO: could not auto-detect the foreign key linking PurchaseOrderHeader back to Vendor.
        // Example: new LiveFilteredCollection<PurchaseOrderHeader>(MainModel.Instance.PurchaseOrderHeaders, x => /* match condition */, nameof(PurchaseOrderHeader.SomeProperty))
        get { if (_purchaseOrderHeaders == null) PurchaseOrderHeaders = new ObservableCollection<PurchaseOrderHeader>(); return _purchaseOrderHeaders!; }
        private set => SetProperty(ref _purchaseOrderHeaders, value);
    }

    public static bool IsVendorsLoaded => MainModel.Instance.IsVendorsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsVendorsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<Vendor>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.BusinessEntityId).ToHashSet();
        var collection = MainModel.Instance.Vendors;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.BusinessEntityId, freshItem.BusinessEntityId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].BusinessEntityId)) collection.RemoveAt(i);
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadVendorsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(Vendor fresh)
    {
        BusinessEntityId = fresh.BusinessEntityId;
        AccountNumber = fresh.AccountNumber;
        Name = fresh.Name;
        CreditRating = fresh.CreditRating;
        PreferredVendorStatus = fresh.PreferredVendorStatus;
        ActiveFlag = fresh.ActiveFlag;
        PurchasingWebServiceUrl = fresh.PurchasingWebServiceUrl;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<Vendor>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<Vendor>? _vendors;
    public ObservableCollection<Vendor> Vendors
    {
        get { if (_vendors == null) Vendors = new ObservableCollection<Vendor>(); return _vendors!; }
        private set
        {
            SetProperty(ref _vendors, value);
            OnPropertyChanged(nameof(IsVendorsLoaded));
        }
    }

    public bool IsVendorsLoaded => _vendors != null;

    internal void UnloadVendorsStorage()
    {
        if (_vendors == null) return;
        _vendors = null;
        OnPropertyChanged(nameof(Vendors));
        OnPropertyChanged(nameof(IsVendorsLoaded));
    }
}
}
