// <auto-generated>
//     Generated from WorkOrderRouting.cs by the ModelsProject template.
//     Regenerated whenever the source file changes.
// </auto-generated>

#nullable enable

#pragma warning disable IDE0130 // Namespace does not match folder structure

using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using MILL09.Models.Interfaces;
using MILL80.Infrastructure.Services;
using MILL80.Infrastructure;

namespace MILL09.Models
{
public partial class WorkOrderRouting : ModelEntityBase
{
    [ObservableProperty]
    private int _workOrderId;

    [ObservableProperty]
    private int _productId;

    [ObservableProperty]
    private short _operationSequence;

    [ObservableProperty]
    private short _locationId;

    [ObservableProperty]
    private DateTime _scheduledStartDate;

    [ObservableProperty]
    private DateTime _scheduledEndDate;

    [ObservableProperty]
    private DateTime? _actualStartDate;

    [ObservableProperty]
    private DateTime? _actualEndDate;

    [ObservableProperty]
    private decimal? _actualResourceHrs;

    [ObservableProperty]
    private decimal _plannedCost;

    [ObservableProperty]
    private decimal? _actualCost;

    [ObservableProperty]
    private DateTime _modifiedDate;

    public Location? Location => MainModel.Instance.Locations.FirstOrDefault(x => x.LocationId == this.LocationId);

    public WorkOrder? WorkOrder => MainModel.Instance.WorkOrders.FirstOrDefault(x => x.WorkOrderId == this.WorkOrderId);

    public static bool IsWorkOrderRoutingsLoaded => MainModel.Instance.IsWorkOrderRoutingsLoaded;

    public static Task LoadAllAsync(CancellationToken ct = default) =>
        IsWorkOrderRoutingsLoaded ? Task.CompletedTask : RefreshAllAsync(ct);

    public static async Task RefreshAllAsync(CancellationToken ct = default)
    {
        OnRefreshing();
        var loader = MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySetLoader<WorkOrderRouting>>();
        var fresh = await loader.LoadAllAsync(ct);
        var freshIds = fresh.Select(x => x.WorkOrderId).ToHashSet();
        var collection = MainModel.Instance.WorkOrderRoutings;
        foreach (var freshItem in fresh)
        {
            var existing = collection.FirstOrDefault(x => Equals(x.WorkOrderId, freshItem.WorkOrderId));
            if (existing != null) existing.CopyScalarsFrom(freshItem);
            else collection.Add(freshItem);
        }
        for (int i = collection.Count - 1; i >= 0; i--)
            if (!freshIds.Contains(collection[i].WorkOrderId)) collection.RemoveAt(i);
        OnRefreshed();
    }

    public static void UnloadAll()
    {
        OnUnloading();
        MainModel.Instance.UnloadWorkOrderRoutingsStorage();
        OnUnloaded();
    }

    static partial void OnRefreshing();
    static partial void OnRefreshed();
    static partial void OnUnloading();
    static partial void OnUnloaded();

    internal void CopyScalarsFrom(WorkOrderRouting fresh)
    {
        WorkOrderId = fresh.WorkOrderId;
        ProductId = fresh.ProductId;
        OperationSequence = fresh.OperationSequence;
        LocationId = fresh.LocationId;
        ScheduledStartDate = fresh.ScheduledStartDate;
        ScheduledEndDate = fresh.ScheduledEndDate;
        ActualStartDate = fresh.ActualStartDate;
        ActualEndDate = fresh.ActualEndDate;
        ActualResourceHrs = fresh.ActualResourceHrs;
        PlannedCost = fresh.PlannedCost;
        ActualCost = fresh.ActualCost;
        ModifiedDate = fresh.ModifiedDate;
    }

    protected override Task OnSaveAsync(CancellationToken ct) =>
        MILL80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<IEntitySaver<WorkOrderRouting>>().SaveAsync(this, ct);
}
}

namespace MILL09.Models
{
public partial class MainModel
{
    private ObservableCollection<WorkOrderRouting>? _workOrderRoutings;
    public ObservableCollection<WorkOrderRouting> WorkOrderRoutings
    {
        get { if (_workOrderRoutings == null) WorkOrderRoutings = new ObservableCollection<WorkOrderRouting>(); return _workOrderRoutings!; }
        private set
        {
            SetProperty(ref _workOrderRoutings, value);
            OnPropertyChanged(nameof(IsWorkOrderRoutingsLoaded));
        }
    }

    public bool IsWorkOrderRoutingsLoaded => _workOrderRoutings != null;

    internal void UnloadWorkOrderRoutingsStorage()
    {
        if (_workOrderRoutings == null) return;
        _workOrderRoutings = null;
        OnPropertyChanged(nameof(WorkOrderRoutings));
        OnPropertyChanged(nameof(IsWorkOrderRoutingsLoaded));
    }
}
}
