// <auto-generated>
//     Generated by the ViewModelsProject template.
// </auto-generated>
#nullable enable

using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;

namespace MILL06.ViewModels
{
    public partial class MenuViewModel : RegionBaseViewModel {
        private ObservableCollection<MenuNodeViewModel>? _menuItems;
        
        public ObservableCollection<MenuNodeViewModel> MenuItems => 
            _menuItems ??= new ObservableCollection<MenuNodeViewModel>(MenuRegistry.Instance.GetDefaultMenu());
    }
}